import type { QuizQuestion } from './courseData';

export interface ComprehensiveExamQuestion {
  id: string;
  lesson: string;
  lessonName_ar: string;
  lessonName_en: string;
  question_ar: string;
  question_en: string;
  option_a_ar: string;
  option_a_en: string;
  option_b_ar: string;
  option_b_en: string;
  option_c_ar: string;
  option_c_en: string;
  option_d_ar: string;
  option_d_en: string;
  correct_option: 'A' | 'B' | 'C' | 'D';
  explanation_ar: string;
  explanation_en: string;
}


export const COMPREHENSIVE_EXAM_QUESTIONS: ComprehensiveExamQuestion[] = [
  // --- LESSON 1-1 ---
  {
    id: "comp_1_1_q1",
    lesson: "1-1",
    lessonName_ar: "تطور تكنولوجيا المعلومات والتحول الاجتماعي",
    lessonName_en: "IT Development & Social Transformation",
    question_ar: "ما هي الملاحظة التجريبية التي تصف اتجاهاً تاريخياً لتضاعف عدد الترانزستورات في الدوائر المتكاملة كل عامين تقريباً؟",
    question_en: "What empirical observation describes a historical trend of doubling the number of transistors in integrated circuits approximately every two years?",
    option_a_ar: "الحوسبة السحابية (Cloud Computing)",
    option_a_en: "Cloud Computing",
    option_b_ar: "قانون مور (Moore's Law)",
    option_b_en: "Moore's Law",
    option_c_ar: "الحوسبة الطرفية (Edge Computing)",
    option_c_en: "Edge Computing",
    option_d_ar: "التراكب الكمي (Quantum Superposition)",
    option_d_en: "Quantum Superposition",
    correct_option: "B",
    explanation_ar: "قانون مور هو ملاحظة تجريبية صاغها غوردون مور تنص على تضاعف كثافة الترانزستورات كل سنتين تقريباً مع انخفاض التكلفة.",
    explanation_en: "Moore's Law is an empirical observation stating that transistor counts on integrated circuits double approximately every two years."
  },
  {
    id: "comp_1_1_q2",
    lesson: "1-1",
    lessonName_ar: "تطور تكنولوجيا المعلومات والتحول الاجتماعي",
    lessonName_en: "IT Development & Social Transformation",
    question_ar: "أي من الخيارات التالية يمثل التقنية أو الحدث التكنولوجي المحوري المرتبط بفترة السبعينيات والثمانينيات من القرن العشرين؟",
    question_en: "Which of the following represents the pivotal technology or event associated with the 1970s and 1980s?",
    option_a_ar: "ظهور الهواتف الذكية وتطبيقاتها المتنقلة",
    option_a_en: "Emergence of smartphones and mobile apps",
    option_b_ar: "انتشار الحواسيب الشخصية (PCs) في المكاتب والمنازل",
    option_b_en: "Spread of Personal Computers (PCs)",
    option_c_ar: "التوسع الهائل للحوسبة السحابية والذكاء الاصطناعي التوليدي",
    option_c_en: "Explosion of Cloud Computing and Generative AI",
    option_d_ar: "ظهور شبكة الويب العالمية (WWW) والتجارة الإلكترونية",
    option_d_en: "Emergence of World Wide Web and E-commerce",
    correct_option: "B",
    explanation_ar: "في السبعينيات والثمانينيات، انتشرت الحواسيب الشخصية (PCs)، مما أطلق حقبة الحوسبة الفردية بعد الحواسيب العملاقة المركزية.",
    explanation_en: "The 1970s-80s saw the widespread adoption of personal computers (PCs), democratizing computer access."
  },
  {
    id: "comp_1_1_q3",
    lesson: "1-1",
    lessonName_ar: "تطور تكنولوجيا المعلومات والتحول الاجتماعي",
    lessonName_en: "IT Development & Social Transformation",
    question_ar: "في أنظمة القيادة الذاتية للمركبات، لماذا يُعد الاعتماد على الحوسبة الطرفية (Edge Computing) ضرورة حتمية بدلاً من إرسال البيانات للسحابة؟",
    question_en: "In autonomous vehicle systems, why is Edge Computing strictly required instead of sending all sensory data to the cloud?",
    option_a_ar: "لأن الحوسبة الطرفية لا تستهلك أي طاقة كهربائية من بطارية السيارة",
    option_a_en: "Because edge computing consumes zero battery power",
    option_b_ar: "لمعالجة البيانات واتخاذ قرارات الفرملة والتوجيه فورياً وتفادي زمن التأخير (Latency) القاتل",
    option_b_en: "To process data and make instant steering/braking decisions avoiding dangerous network latency",
    option_c_ar: "لأن السحابة غير قادرة هندسياً على تخزين الخرائط الجغرافية",
    option_c_en: "Because cloud servers cannot store geographic map data",
    option_d_ar: "لتجنب دفع رسوم اشتراك الإنترنت الشهرية لشركات الاتصالات فقط",
    option_d_en: "Only to avoid paying monthly internet subscription fees",
    correct_option: "B",
    explanation_ar: "في القيادة الذاتية، التأخير بأجزاء من الثانية قد يتسبب في حادث خطير، لذا تتم المعالجة اللحظية على معالجات المركبة الطرفية دون انتظار رد السحابة.",
    explanation_en: "Latency in driving decisions can cause fatal crashes; Edge Computing allows sub-millisecond local onboard processing."
  },
  {
    id: "comp_1_1_q4",
    lesson: "1-1",
    lessonName_ar: "تطور تكنولوجيا المعلومات والتحول الاجتماعي",
    lessonName_en: "IT Development & Social Transformation",
    question_ar: "ما هو نمط العمل الذي يمارس فيه الموظف مهامه الوظيفية من المنزل أو مكان آخر خارج المقر التقليدي باستخدام الإنترنت؟",
    question_en: "What working style allows employees to perform duties from home or remote locations using the Internet?",
    option_a_ar: "التجارة الإلكترونية (E-commerce)",
    option_a_en: "E-commerce",
    option_b_ar: "الدفع غير النقدي (Cashless Payment)",
    option_b_en: "Cashless Payment",
    option_c_ar: "العمل عن بُعد (Remote Work / Telecommuting)",
    option_c_en: "Remote Work / Telecommuting",
    option_d_ar: "الحوسبة الكمومية (Quantum Computing)",
    option_d_en: "Quantum Computing",
    correct_option: "C",
    explanation_ar: "العمل عن بُعد يُمكّن العاملين من أداء واجباتهم عبر تقنيات الاتصال السحابية والإنترنت دون الحضور المادي اليومي للشركة.",
    explanation_en: "Remote work allows employees to collaborate online and accomplish tasks without physical office presence."
  },
  {
    id: "comp_1_1_q5",
    lesson: "1-1",
    lessonName_ar: "تطور تكنولوجيا المعلومات والتحول الاجتماعي",
    lessonName_en: "IT Development & Social Transformation",
    question_ar: "ما الخاصية الفيزيائية الفريدة التي تُميز الكيوبت (Qubit) في الحوسبة الكمومية عن البت التقليدي (Bit)؟",
    question_en: "What unique physical property distinguishes a quantum qubit from a classical computer bit?",
    option_a_ar: "الكيوبت يحمل دائماً القيمة 0 فقط ولا يتغير أبداً",
    option_a_en: "The qubit always holds the value 0 and never changes",
    option_b_ar: "الكيوبت يمكن أن يكون في حالة تراكب كمي (مزيج من 0 و1 في نفس اللحظة)",
    option_b_en: "The qubit can exist in superposition (a combination of 0 and 1 simultaneously)",
    option_c_ar: "الكيوبت لا يحتاج إلى أي معالجات رياضية لإجراء العمليات",
    option_c_en: "The qubit requires no mathematical processing",
    option_d_ar: "الكيوبت يخزن البيانات في ذاكرة ورقية مغناطيسية",
    option_d_en: "The qubit stores data on paper magnetic tape",
    correct_option: "B",
    explanation_ar: "يعتمد الكيوبت على مبدأ التراكب الكمي (Superposition)، مما يسمح له بتمثيل حالات متعددة في آن واحد وحل المسائل الفائقة التعقيد.",
    explanation_en: "Through quantum superposition, qubits represent linear combinations of 0 and 1 simultaneously."
  },

  // --- LESSON 1-2 ---
  {
    id: "comp_1_2_q6",
    lesson: "1-2",
    lessonName_ar: "كيف يعمل الذكاء الاصطناعي",
    lessonName_en: "How AI Works",
    question_ar: "ما هو التعريف الأكاديمي الدقيق للذكاء الاصطناعي (AI)؟",
    question_en: "What is the accurate academic definition of Artificial Intelligence (AI)?",
    option_a_ar: "برامج تشغيل الحواسيب الميكانيكية القديمة المعتمدة على البطاقات المثقوبة",
    option_a_en: "Mechanical operating systems relying on punch cards",
    option_b_ar: "تقنيات تمكّن الحواسيب من محاكاة السلوك البشري الذكي مثل التعلم والاستدلال وإصدار الأحكام",
    option_b_en: "Technologies enabling computers to reproduce intelligent human behavior like learning, reasoning, and judgment",
    option_c_ar: "تطبيقات مخصصة فقط لحساب المعادلات الحسابية البسيطة والجمع والطرح",
    option_c_en: "Applications dedicated solely to basic arithmetic operations",
    option_d_ar: "أسلاك وشبكات الاتصال السلكية التي تربط الخوادم ببعضها",
    option_d_en: "Cables and hardware wires connecting server racks",
    correct_option: "B",
    explanation_ar: "الذكاء الاصطناعي مظلة عامة تشمل جميع التقنيات الرياضية والبرمجية التي تحاكي الإدراك والذكاء والقدرة التحليلية البشرية.",
    explanation_en: "AI encompasses technologies that allow machines to exhibit cognitive and analytical human traits."
  },
  {
    id: "comp_1_2_q7",
    lesson: "1-2",
    lessonName_ar: "كيف يعمل الذكاء الاصطناعي",
    lessonName_en: "How AI Works",
    question_ar: "ما هو الفارق الجوهري بين تعلم الآلة (Machine Learning) والبرمجة التقليدية المعتمدة على القواعد الصريحة؟",
    question_en: "What fundamental difference separates Machine Learning from traditional rule-based programming?",
    option_a_ar: "البرمجة التقليدية لا تستخدم لغات البرمجة إطلاقاً",
    option_a_en: "Traditional programming never uses programming languages",
    option_b_ar: "تعلم الآلة يستنبط الأنماط والقواعد تلقائياً من البيانات دون الحاجة لكتابة كل قاعدة يدوياً",
    option_b_en: "Machine learning infers patterns automatically from data without requiring handcrafted explicit rules",
    option_c_ar: "تعلم الآلة يتطلب تدخلاً بشرياً لكتابة شرط (if/else) لكل بريد مزعج على حدة",
    option_c_en: "Machine learning requires hand-coding an if/else check for every single spam email",
    option_d_ar: "البرمجة التقليدية تتعلم ذاتياً وتتطور كلما زادت البيانات",
    option_d_en: "Traditional programming learns autonomously as data increases",
    correct_option: "B",
    explanation_ar: "في تعلم الآلة، نزود النموذج بالبيانات والأمثلة ليقوم هو باكتشاف العلاقات والأنماط، بدلاً من كتابة كل قاعدة منطقية مسبقاً.",
    explanation_en: "ML models learn representations and mappings straight from data rather than hardcoded heuristics."
  },
  {
    id: "comp_1_2_q8",
    lesson: "1-2",
    lessonName_ar: "كيف يعمل الذكاء الاصطناعي",
    lessonName_en: "How AI Works",
    question_ar: "على ماذا تعتمد خوارزميات التعلم العميق (Deep Learning) في معالجة وتحليل البيانات المعقدة كالصور والصوت؟",
    question_en: "What foundational architecture powers Deep Learning when analyzing complex data like images and audio?",
    option_a_ar: "جداول البيانات البسيطة المسجلة في قواعد البيانات النصية",
    option_a_en: "Simple tabular flat files stored in text databases",
    option_b_ar: "شبكات عصبية اصطناعية متعددة الطبقات (Multi-layered Neural Networks)",
    option_b_en: "Multi-layered Artificial Neural Networks",
    option_c_ar: "خوارزميات الفرز الترتيبي الخطي البسيطة",
    option_c_en: "Basic linear bubble sorting algorithms",
    option_d_ar: "الدوائر الإلكترونية التناظرية القديمة المعتمدة على الصمامات المفرغة",
    option_d_en: "Analog vacuum tube circuits",
    correct_option: "B",
    explanation_ar: "التعلم العميق فرع متقدم من تعلم الآلة يستخدم شبكات عصبية عميقة متعددة الطبقات لمعالجة واستخراج الميزات المعقدة.",
    explanation_en: "Deep Learning utilizes deep neural networks with multiple hidden layers to extract hierarchical features."
  },
  {
    id: "comp_1_2_q9",
    lesson: "1-2",
    lessonName_ar: "كيف يعمل الذكاء الاصطناعي",
    lessonName_en: "How AI Works",
    question_ar: "ما الميزة الاستثنائية التي ينفرد بها الذكاء الاصطناعي التوليدي (Generative AI) مقارنة بنماذج الذكاء الاصطناعي التقليدية؟",
    question_en: "What distinct ability sets Generative AI apart from traditional predictive or classification AI models?",
    option_a_ar: "قدرته على ابتكار وتوليد محتوى جديد تماماً (نصوص، صور، أكواد برمجية، أصوات)",
    option_a_en: "Its capability to generate novel content (text, synthetic images, code, audio)",
    option_b_ar: "أنه لا يحتاج إلى أي بيانات تدريب نهائياً",
    option_b_en: "It requires no training data whatsoever",
    option_d_ar: "أنه يعمل فقط دون اتصال بالإنترنت ودون الحاجة لأجهزة حاسوب",
    option_d_en: "It functions completely offline without computers",
    option_c_ar: "اقتصار عمله على تصنيف الملفات إلى مجلدات فقط",
    option_c_en: "It only classifies files into folders",
    correct_option: "A",
    explanation_ar: "الذكاء الاصطناعي التوليدي لا يكتفي بالتصنيف أو التنبؤ؛ بل يولد بيانات ومخرجات جديدة إبداعية تحاكي النتاج البشري.",
    explanation_en: "Generative AI produces novel synthesized outputs (text, imagery, media) rather than solely categorizing existing inputs."
  },
  {
    id: "comp_1_2_q10",
    lesson: "1-2",
    lessonName_ar: "كيف يعمل الذكاء الاصطناعي",
    lessonName_en: "How AI Works",
    question_ar: "ما المقصود بظاهرة «الهلوسة» (Hallucination) في نماذج الذكاء الاصطناعي التوليدي؟",
    question_en: "What is meant by 'Hallucination' in Generative AI language models?",
    option_a_ar: "توقف الخادم السحابي عن العمل بسبب انقطاع التيار الكهربائي",
    option_a_en: "Cloud servers shutting down due to power failure",
    option_b_ar: "إنتاج النموذج لمعلومات تبدو مقنعة ولغوياً سليمة لكنها غير صحيحة أو مختلقة تماماً",
    option_b_en: "The model generating plausibly phrased but factually incorrect or fabricated statements",
    option_c_ar: "سرعة استجابة النموذج الفائقة التي تتجاوز سرعة كتابة المستخدم",
    option_c_en: "Extremely rapid token output beating user typing speed",
    option_d_ar: "ترجمة النصوص بدقة 100% دون أي خطأ نحوي",
    option_d_en: "Translating texts with 100% syntactic perfection",
    correct_option: "B",
    explanation_ar: "الهلوسة تعني صياغة إجابات تبدو واثقة ومقنعة لكنها تتضمن وقائع مغلوطة أو مراجع وهمية، لذا تتطلب مراجعة بشرية مستمرة.",
    explanation_en: "Hallucination refers to the generation of confident, coherent-sounding text that is factually false or invented."
  },

  // --- LESSON 1-3 ---
  {
    id: "comp_1_3_q11",
    lesson: "1-3",
    lessonName_ar: "الذكاء الاصطناعي في الحياة اليومية والصناعة",
    lessonName_en: "AI in Daily Life and Industry",
    question_ar: "أي من الأنظمة التالية يُحلل تفضيلات وسجل سلوك المستخدم السابق لعرض مقترحات شراء أو فيديوهات ملائمة؟",
    question_en: "Which system analyzes users' previous behavior and preferences to suggest relevant purchases or videos?",
    option_a_ar: "أنظمة التوصية الذكية (Recommendation Systems)",
    option_a_en: "Smart Recommendation Systems",
    option_b_ar: "برامج مكافحة الفيروسات التقليدية",
    option_b_en: "Traditional Antivirus Software",
    option_c_ar: "محولات الطاقة الكهربائية الرقمية",
    option_c_en: "Digital Power Inverters",
    option_d_ar: "طابعات الحبر النفاث المكتبية",
    option_d_en: "Desktop Inkjet Printers",
    correct_option: "A",
    explanation_ar: "أنظمة التوصية (مثل المستخدمة في يوتيوب وأمازون) تستعين بتعلم الآلة لاكتشاف اهتمامات المستخدمين وتخصيص المحتوى المناسب.",
    explanation_en: "Recommendation systems personalize suggestions based on historical user interactions and affinity patterns."
  },
  {
    id: "comp_1_3_q12",
    lesson: "1-3",
    lessonName_ar: "الذكاء الاصطناعي في الحياة اليومية والصناعة",
    lessonName_en: "AI in Daily Life and Industry",
    question_ar: "كيف تسهم تقنية «الصيانة التنبؤية» (Predictive Maintenance) في تحسين كفاءة خطوط الإنتاج بالمصانع الحديثة؟",
    question_en: "How does Predictive Maintenance enhance manufacturing efficiency on modern production lines?",
    option_a_ar: "تستبدل جميع الآلات القديمة بروبوتات جديدة كل أسبوع دون سبب",
    option_a_en: "By replacing machines with robots every week unnecessarily",
    option_b_ar: "بتحليل بيانات الاهتزاز والحرارة من المستشعرات لاكتشاف مؤشرات الأعطال قبل حدوث التوقف المفاجئ",
    option_b_en: "By analyzing vibration and thermal telemetry from IoT sensors to detect failure signals before breakdowns",
    option_c_ar: "بتقليل ساعات العمل الأسبوعية للعمال إلى ساعة واحدة فقط",
    option_c_en: "By cutting weekly labor shifts to one hour",
    option_d_ar: "بإلغاء الحاجة لوجود كهرباء في المصانع",
    option_d_en: "By eliminating the requirement of electricity in factories",
    correct_option: "B",
    explanation_ar: "الصيانة التنبؤية تستخدم بيانات مستشعرات إنترنت الأشياء وخوارزميات الذكاء الاصطناعي للتنبؤ بموعد عطل القطع وتغييرها استباقياً.",
    explanation_en: "Predictive maintenance analyzes sensor metrics to forecast mechanical wear, scheduling repairs proactively."
  },
  {
    id: "comp_1_3_q13",
    lesson: "1-3",
    lessonName_ar: "الذكاء الاصطناعي في الحياة اليومية والصناعة",
    lessonName_en: "AI in Daily Life and Industry",
    question_ar: "ما هو الفرع التكنولوجي في الذكاء الاصطناعي الذي يُمكّن الحواسيب من فحص صور الأشعة الطبية ومراقبة جودة المنتجات بالمصانع؟",
    question_en: "What branch of AI empowers computers to inspect medical scans and perform automated quality control?",
    option_a_ar: "رؤية الحاسوب (Computer Vision)",
    option_a_en: "Computer Vision",
    option_b_ar: "الطباعة ثلاثية الأبعاد اليدوية",
    option_b_en: "Manual 3D Printing",
    option_c_ar: "توليد كلمات المرور العشوائية",
    option_c_en: "Random Password Generation",
    option_d_ar: "النسخ الاحتياطي على الأقراص المدمجة",
    option_d_en: "Optical Disc Data Backup",
    correct_option: "A",
    explanation_ar: "رؤية الحاسوب تمكّن النظم من فهم وتحليل الصور والفيديوهات لاكتشاف التشوهات الطبية والعيوب التصنيعية بدقة وسرعة هائلة.",
    explanation_en: "Computer Vision enables machines to parse and interpret visual inputs for tumor diagnosis and industrial flaw inspection."
  },
  {
    id: "comp_1_3_q14",
    lesson: "1-3",
    lessonName_ar: "الذكاء الاصطناعي في الحياة اليومية والصناعة",
    lessonName_en: "AI in Daily Life and Industry",
    question_ar: "في مجال «الزراعة الدقيقة» (Precision Agriculture)، كيف يدعم الذكاء الاصطناعي المزارعين؟",
    question_en: "In 'Precision Agriculture', how does AI assist farmers?",
    option_a_ar: "بمنع هطول الأمطار على الحقول الزراعية نهائياً",
    option_a_en: "By stopping rain clouds from passing over fields",
    option_b_ar: "بتحليل صور المحاصيل لاكتشاف الآفات مبكراً وتحسين كميات الري والأسمدة بدقة",
    option_b_en: "By analyzing crop imagery for early pest detection and optimizing targeted irrigation and fertilizer usage",
    option_c_ar: "بزراعة المحاصيل بدون بذور أو تربة وبدون ماء",
    option_c_en: "By growing plants with zero seeds, soil, or water",
    option_d_ar: "بإلغاء الحاجة لضوء الشمس لجميع أنواع النباتات",
    option_d_en: "By removing the need for sunlight for all vegetation",
    correct_option: "B",
    explanation_ar: "تساعد الزراعة الدقيقة المدعومة بالذكاء الاصطناعي على تقليل الهدر واكتشاف أمراض المحاصيل من خلال صور الطائرات بدون طيار (Drones).",
    explanation_en: "AI in smart farming diagnoses plant stress from drone imagery and targets water/fertilizer only where needed."
  },
  {
    id: "comp_1_3_q15",
    lesson: "1-3",
    lessonName_ar: "الذكاء الاصطناعي في الحياة اليومية والصناعة",
    lessonName_en: "AI in Daily Life and Industry",
    question_ar: "ما هو الفارق الأساسي بين دور الذكاء الاصطناعي التنبؤي (Predictive AI) والذكاء الاصطناعي التوليدي (Generative AI) في الشركات والمؤسسات؟",
    question_en: "What is the core distinction between Predictive AI and Generative AI within enterprise applications?",
    option_a_ar: "الذكاء التنبؤي يتوقع الاتجاهات ومعدلات الطلب المستقبلية من البيانات السابقة، بينما التوليدي يبتكر مواد وحملات وتصاميم جديدة",
    option_a_en: "Predictive AI forecasts future trends and demand from historical data, while Generative AI creates novel materials and campaigns",
    option_b_ar: "الذكاء التنبؤي مخصص فقط للألعاب، بينما الذكاء التوليدي مخصص فقط للعمليات الحسابية",
    option_b_en: "Predictive AI is solely for gaming, while Generative AI is strictly for calculators",
    option_c_ar: "الذكاء التنبؤي لا يعتمد على خوارزميات إحصائية أبداً",
    option_c_en: "Predictive AI never uses statistical algorithms",
    option_d_ar: "الذكاء التوليدي يقتصر عمله على حذف الملفات التالفة من الحواسيب",
    option_d_en: "Generative AI is limited to deleting corrupted files",
    correct_option: "A",
    explanation_ar: "الذكاء الاصطناعي التنبؤي يستشرف المستقبل ومخاطر الائتمان والأعطال، بينما التوليدي يصنع تصاميم ونصوصاً ورسائل تسويقية جديدة كلياً.",
    explanation_en: "Predictive AI forecasts probabilities and trends from past telemetry, whereas Generative AI synthesizes brand-new assets and textual responses."
  }
];

export const COMPREHENSIVE_AS_QUIZ_QUESTIONS: QuizQuestion[] = COMPREHENSIVE_EXAM_QUESTIONS.map(q => ({
  id: q.id,
  lesson: "exam-1-3",
  unit: "1",
  type: "MCQ",
  difficulty: "MEDIUM",
  source: "WEEKLY_ASSESSMENT",
  question_ar: q.question_ar,
  question_en: q.question_en,
  option_a_ar: q.option_a_ar,
  option_a_en: q.option_a_en,
  option_b_ar: q.option_b_ar,
  option_b_en: q.option_b_en,
  option_c_ar: q.option_c_ar,
  option_c_en: q.option_c_en,
  option_d_ar: q.option_d_ar,
  option_d_en: q.option_d_en,
  correct_option: q.correct_option,
  explanation_ar: q.explanation_ar,
  explanation_en: q.explanation_en,
}));
