import type { QuizQuestion } from './courseData';

export const MASSIVE_BANK_L4: QuizQuestion[] = [
  // ------------------- LESSON 1.4 (20 QUESTIONS) -------------------
  {
    id: "mb_l4_01", unit: "1", lesson: "1-4", type: "MCQ", source: "CLASSROOM", difficulty: "MEDIUM",
    question_en: "What is 'Algorithmic Bias'?",
    question_ar: "ما هو 'التحيز الخوارزمي' (Algorithmic Bias)؟",
    option_a_en: "When an AI system operates too slowly due to complex algorithms.",
    option_a_ar: "عندما يعمل نظام الذكاء الاصطناعي ببطء شديد بسبب الخوارزميات المعقدة.",
    option_b_en: "Systematic and repeatable errors in a computer system that create unfair outcomes, such as privileging one arbitrary group of users over others.",
    option_b_ar: "أخطاء منهجية ومتكررة في نظام الكمبيوتر تؤدي إلى نتائج غير عادلة، مثل تفضيل مجموعة عشوائية من المستخدمين على غيرهم.",
    option_c_en: "When a developer prefers one programming language over another.",
    option_c_ar: "عندما يفضل المطور لغة برمجة على أخرى.",
    option_d_en: "An AI deliberately deciding to harm humans.",
    option_d_ar: "ذكاء اصطناعي يقرر عمداً إيذاء البشر.",
    correct_option: "B",
    explanation_en: "Algorithmic bias usually stems from biased training data, reflecting historical human prejudices.",
    explanation_ar: "عادةً ما ينبع التحيز الخوارزمي من بيانات تدريب متحيزة، مما يعكس الأحكام المسبقة البشرية التاريخية."
  },
  {
    id: "mb_l4_02", unit: "1", lesson: "1-4", type: "MCQ", source: "HOMEWORK", difficulty: "MEDIUM",
    question_en: "Which of the following is an example of an AI privacy violation?",
    question_ar: "أي مما يلي هو مثال على 'انتهاك الخصوصية' بواسطة الذكاء الاصطناعي؟",
    option_a_en: "An AI generating a fake landscape image.",
    option_a_ar: "ذكاء اصطناعي يولد صورة وهمية للمناظر الطبيعية.",
    option_b_en: "A smart speaker constantly recording private conversations without the user's explicit consent to train advertising models.",
    option_b_ar: "مكبر صوت ذكي يسجل المحادثات الخاصة باستمرار دون موافقة صريحة من المستخدم لتدريب نماذج الإعلانات.",
    option_c_en: "An AI translating an ancient public manuscript.",
    option_c_ar: "ذكاء اصطناعي يترجم مخطوطة عامة قديمة.",
    option_d_en: "An AI beating a human at chess.",
    option_d_ar: "ذكاء اصطناعي يهزم إنساناً في الشطرنج.",
    correct_option: "B",
    explanation_en: "Recording private data without informed consent for commercial gain is a primary ethical and legal privacy violation.",
    explanation_ar: "يعد تسجيل البيانات الخاصة دون موافقة مستنيرة لتحقيق مكاسب تجارية انتهاكاً أخلاقياً وقانونياً رئيسياً للخصوصية."
  },
  {
    id: "mb_l4_03", unit: "1", lesson: "1-4", type: "MCQ", source: "WEEKLY_ASSESSMENT", difficulty: "HARD",
    question_en: "What is the 'Alignment Problem' in Artificial Intelligence?",
    question_ar: "ما هي 'مشكلة التوافق' (Alignment Problem) في الذكاء الاصطناعي؟",
    option_a_en: "Aligning text properly in UI design.",
    option_a_ar: "محاذاة النص بشكل صحيح في تصميم واجهة المستخدم.",
    option_b_en: "The challenge of ensuring that an AI system's goals and behaviors perfectly match human values and intended goals.",
    option_b_ar: "تحدي ضمان تطابق أهداف وسلوكيات نظام الذكاء الاصطناعي تماماً مع القيم والأهداف الإنسانية المقصودة.",
    option_c_en: "Aligning the robots' physical wheels to drive straight.",
    option_c_ar: "محاذاة العجلات المادية للروبوتات للقيادة بشكل مستقيم.",
    option_d_en: "Matching the database keys in SQL.",
    option_d_ar: "مطابقة مفاتيح قاعدة البيانات في SQL.",
    correct_option: "B",
    explanation_en: "If an AI is told to 'make humans smile', it might paralyze human facial muscles into a permanent smile if its goals aren't aligned with human well-being.",
    explanation_ar: "إذا طُلب من ذكاء اصطناعي 'جعل البشر يبتسمون'، فقد يشل عضلات وجه الإنسان في ابتسامة دائمة إذا لم تكن أهدافه متوافقة مع رفاهية الإنسان."
  },
  {
    id: "mb_l4_04", unit: "1", lesson: "1-4", type: "WRITTEN", source: "HOMEWORK", difficulty: "HARD",
    question_en: "Explain how 'Deepfakes' pose a threat to democratic elections.",
    question_ar: "اشرح كيف تشكل تقنية 'التزييف العميق' (Deepfakes) تهديداً للانتخابات الديمقراطية.",
    ideal_answer_en: "Deepfakes can create highly realistic, fabricated videos of political candidates saying or doing things they never did. If released right before an election, they can manipulate public opinion and spread massive misinformation before the truth can be verified.",
    ideal_answer_ar: "يمكن لتقنية التزييف العميق إنشاء مقاطع فيديو واقعية للغاية ومفبركة للمرشحين السياسيين يقولون أو يفعلون أشياء لم يفعلوها أبداً. إذا تم نشرها قبل الانتخابات مباشرة، فيمكنها التلاعب بالرأي العام ونشر معلومات مضللة هائلة قبل التحقق من الحقيقة."
  },
  {
    id: "mb_l4_05", unit: "1", lesson: "1-4", type: "MCQ", source: "CLASSROOM", difficulty: "MEDIUM",
    question_en: "What does 'Explainable AI' (XAI) aim to achieve?",
    question_ar: "ما الذي يهدف 'الذكاء الاصطناعي القابل للتفسير' (XAI) إلى تحقيقه؟",
    option_a_en: "To make AI speak with a human voice.",
    option_a_ar: "جعل الذكاء الاصطناعي يتحدث بصوت بشري.",
    option_b_en: "To create AI systems whose internal mechanics and decisions can be understood and traced by humans.",
    option_b_ar: "إنشاء أنظمة ذكاء اصطناعي يمكن للبشر فهم وتتبع آلياتها وقراراتها الداخلية.",
    option_c_en: "To make AI systems run without electricity.",
    option_c_ar: "جعل أنظمة الذكاء الاصطناعي تعمل بدون كهرباء.",
    option_d_en: "To teach AI how to teach itself.",
    option_d_ar: "تعليم الذكاء الاصطناعي كيف يعلم نفسه.",
    correct_option: "B",
    explanation_en: "XAI solves the 'black box' problem, ensuring transparency in critical areas like healthcare and law.",
    explanation_ar: "يحل XAI مشكلة 'الصندوق الأسود'، مما يضمن الشفافية في المجالات الحساسة مثل الرعاية الصحية والقانون."
  },
  {
    id: "mb_l4_06", unit: "1", lesson: "1-4", type: "MCQ", source: "WEEKLY_ASSESSMENT", difficulty: "HARD",
    question_en: "An autonomous weapon system is programmed to identify and eliminate enemy combatants without human intervention. Which ethical principle does this most directly violate?",
    question_ar: "نظام أسلحة مستقل مبرمج لتحديد وقتل مقاتلي العدو دون تدخل بشري. أي مبدأ أخلاقي ينتهك هذا بشكل مباشر؟",
    option_a_en: "Net Neutrality.",
    option_a_ar: "حيادية الشبكة.",
    option_b_en: "Meaningful Human Control (Accountability).",
    option_b_ar: "السيطرة البشرية ذات المغزى (المساءلة).",
    option_c_en: "Data Privacy.",
    option_c_ar: "خصوصية البيانات.",
    option_d_en: "Open Source Licensing.",
    option_d_ar: "ترخيص المصدر المفتوح.",
    correct_option: "B",
    explanation_en: "Delegating life-or-death decisions entirely to machines removes human accountability, leading to widespread calls for bans on Lethal Autonomous Weapons Systems (LAWS).",
    explanation_ar: "إن تفويض قرارات الحياة أو الموت بالكامل للآلات يزيل المساءلة البشرية، مما أدى إلى دعوات واسعة النطاق لحظر أنظمة الأسلحة المستقلة المميتة (LAWS)."
  },
  {
    id: "mb_l4_07", unit: "1", lesson: "1-4", type: "MCQ", source: "HOMEWORK", difficulty: "MEDIUM",
    question_en: "When an AI is generating images from text, why might it only generate images of male doctors and female nurses?",
    question_ar: "عندما يقوم الذكاء الاصطناعي بتوليد صور من النص، لماذا قد يقوم فقط بتوليد صور لأطباء ذكور وممرضات إناث؟",
    option_a_en: "The AI possesses a conscious gender bias.",
    option_a_ar: "الذكاء الاصطناعي يمتلك تحيزاً واعياً بين الجنسين.",
    option_b_en: "The AI's training dataset was statistically skewed, reflecting historical stereotypes.",
    option_b_ar: "مجموعة بيانات تدريب الذكاء الاصطناعي كانت منحرفة إحصائياً، مما يعكس الصور النمطية التاريخية.",
    option_c_en: "The text prompt was physically corrupted.",
    option_c_ar: "المُوجّه النصي (Prompt) كان تالفاً مادياً.",
    option_d_en: "AI cannot draw females as doctors.",
    option_d_ar: "الذكاء الاصطناعي لا يمكنه رسم الإناث كأطباء.",
    correct_option: "B",
    explanation_en: "AI models mirror the data they are fed. If historical image banks over-represent men as doctors, the AI learns this as the default reality.",
    explanation_ar: "تعكس نماذج الذكاء الاصطناعي البيانات التي تتلقاها. إذا كانت بنوك الصور التاريخية تمثل الرجال كأطباء بنسبة أكبر، فإن الذكاء الاصطناعي يتعلم هذا كواقع افتراضي."
  },
  {
    id: "mb_l4_08", unit: "1", lesson: "1-4", type: "MCQ", source: "CLASSROOM", difficulty: "HARD",
    question_en: "What does the concept of 'Data Sovereignty' refer to in the context of AI?",
    question_ar: "إلى ماذا يشير مفهوم 'السيادة على البيانات' (Data Sovereignty) في سياق الذكاء الاصطناعي؟",
    option_a_en: "The idea that AI models should rule the government.",
    option_a_ar: "فكرة أن نماذج الذكاء الاصطناعي يجب أن تحكم الحكومة.",
    option_b_en: "The legal concept that digital data is subject to the laws and governance structures of the country in which it is collected or physically stored.",
    option_b_ar: "المفهوم القانوني القائل بأن البيانات الرقمية تخضع لقوانين وهياكل الحوكمة في البلد الذي يتم جمعها أو تخزينها مادياً فيه.",
    option_c_en: "Data being owned by the AI itself.",
    option_c_ar: "البيانات مملوكة للذكاء الاصطناعي نفسه.",
    option_d_en: "The absolute deletion of all data.",
    option_d_ar: "الحذف المطلق لجميع البيانات.",
    correct_option: "B",
    explanation_en: "Data sovereignty is a huge issue for multinational AI companies, as they must comply with local privacy laws (like GDPR in Europe) depending on where the data physically resides.",
    explanation_ar: "تمثل سيادة البيانات مشكلة كبيرة لشركات الذكاء الاصطناعي متعددة الجنسيات، حيث يجب عليها الامتثال لقوانين الخصوصية المحلية (مثل GDPR في أوروبا) بناءً على مكان تخزين البيانات مادياً."
  },
  {
    id: "mb_l4_09", unit: "1", lesson: "1-4", type: "WRITTEN", source: "WEEKLY_ASSESSMENT", difficulty: "HARD",
    question_en: "Briefly discuss the economic ethical dilemma of AI automation regarding the workforce.",
    question_ar: "ناقش باختصار المعضلة الأخلاقية الاقتصادية لأتمتة الذكاء الاصطناعي فيما يتعلق بالقوى العاملة.",
    ideal_answer_en: "AI automation massively increases productivity and creates new technical jobs, but it simultaneously displaces millions of routine manual and cognitive jobs. The ethical dilemma is how society manages this transition—such as through universal basic income (UBI) or reskilling programs—to prevent extreme wealth inequality.",
    ideal_answer_ar: "تزيد أتمتة الذكاء الاصطناعي الإنتاجية بشكل كبير وتخلق وظائف تقنية جديدة، لكنها تؤدي في الوقت نفسه إلى إزاحة الملايين من الوظائف الروتينية اليدوية والمعرفية. المعضلة الأخلاقية هي كيفية إدارة المجتمع لهذا التحول - مثل الدخل الأساسي الشامل (UBI) أو برامج إعادة التأهيل - لمنع التفاوت الشديد في الثروة."
  },
  {
    id: "mb_l4_10", unit: "1", lesson: "1-4", type: "MCQ", source: "HOMEWORK", difficulty: "MEDIUM",
    question_en: "Which of the following is a proposed solution to combat AI Bias?",
    question_ar: "أي مما يلي يُعد حلاً مقترحاً لمكافحة تحيز الذكاء الاصطناعي (AI Bias)؟",
    option_a_en: "Building deeper neural networks.",
    option_a_ar: "بناء شبكات عصبية أعمق.",
    option_b_en: "Using diverse, representative datasets and conducting algorithmic audits.",
    option_b_ar: "استخدام مجموعات بيانات متنوعة وتمثيلية وإجراء عمليات تدقيق خوارزمية.",
    option_c_en: "Making AI models completely secret.",
    option_c_ar: "جعل نماذج الذكاء الاصطناعي سرية تماماً.",
    option_d_en: "Increasing the computer's RAM.",
    option_d_ar: "زيادة ذاكرة الوصول العشوائي (RAM) للكمبيوتر.",
    correct_option: "B",
    explanation_en: "Diversity in data ensures all groups are represented, and audits help catch biases before deployment.",
    explanation_ar: "يضمن التنوع في البيانات تمثيل جميع المجموعات، وتساعد عمليات التدقيق في اكتشاف التحيزات قبل النشر."
  },
  {
    id: "mb_l4_11", unit: "1", lesson: "1-4", type: "MCQ", source: "CLASSROOM", difficulty: "HARD",
    question_en: "What is 'Techno-solutionism' in the context of AI?",
    question_ar: "ما هي 'الحلولية التكنولوجية' (Techno-solutionism) في سياق الذكاء الاصطناعي؟",
    option_a_en: "The study of technology.",
    option_a_ar: "دراسة التكنولوجيا.",
    option_b_en: "The misguided belief that AI and technology can magically solve deep-rooted, complex social or political problems without addressing human context.",
    option_b_ar: "الاعتقاد الخاطئ بأن الذكاء الاصطناعي والتكنولوجيا يمكن أن تحل سحرياً المشاكل الاجتماعية أو السياسية العميقة والمعقدة دون معالجة السياق البشري.",
    option_c_en: "The ability of an AI to write software solutions.",
    option_c_ar: "قدرة الذكاء الاصطناعي على كتابة حلول برمجية.",
    option_d_en: "A type of AI cooling system.",
    option_d_ar: "نوع من أنظمة تبريد الذكاء الاصطناعي.",
    correct_option: "B",
    explanation_en: "Many ethical failures happen when companies deploy AI to 'solve' issues like crime or poverty, ignoring the fact that these are human issues requiring social policy, not just an algorithm.",
    explanation_ar: "تحدث العديد من الإخفاقات الأخلاقية عندما تنشر الشركات الذكاء الاصطناعي لـ 'حل' مشكلات مثل الجريمة أو الفقر، متجاهلة حقيقة أن هذه مشكلات بشرية تتطلب سياسة اجتماعية، وليس مجرد خوارزمية."
  },
  {
    id: "mb_l4_12", unit: "1", lesson: "1-4", type: "MCQ", source: "WEEKLY_ASSESSMENT", difficulty: "MEDIUM",
    question_en: "If an AI generates a beautiful painting, who legally owns the copyright currently in most jurisdictions?",
    question_ar: "إذا قام ذكاء اصطناعي بتوليد لوحة فنية جميلة، فمن يمتلك قانونياً حقوق الطبع والنشر حالياً في معظم السلطات القضائية؟",
    option_a_en: "The AI itself.",
    option_a_ar: "الذكاء الاصطناعي نفسه.",
    option_b_en: "The AI cannot hold copyright; AI-generated works are generally placed in the public domain unless significant human modification occurred.",
    option_b_ar: "لا يمكن للذكاء الاصطناعي امتلاك حقوق الطبع والنشر؛ تُوضع الأعمال المولدة بالذكاء الاصطناعي عموماً في المجال العام ما لم يحدث تعديل بشري كبير.",
    option_c_en: "The person who typed the prompt, unconditionally.",
    option_c_ar: "الشخص الذي كتب المُوجّه (Prompt)، دون قيد أو شرط.",
    option_d_en: "The government.",
    option_d_ar: "الحكومة.",
    correct_option: "B",
    explanation_en: "Currently, most copyright offices (like the US Copyright Office) rule that only human authors can claim copyright.",
    explanation_ar: "حالياً، تحكم معظم مكاتب حقوق الطبع والنشر (مثل مكتب حقوق الطبع والنشر الأمريكي) بأن المؤلفين البشريين فقط هم من يمكنهم المطالبة بحقوق الطبع والنشر."
  },
  {
    id: "mb_l4_13", unit: "1", lesson: "1-4", type: "WRITTEN", source: "HOMEWORK", difficulty: "HARD",
    question_en: "What is the 'Right to be Forgotten' and why is it difficult to implement in Large Language Models (LLMs)?",
    question_ar: "ما هو 'الحق في النسيان' (Right to be Forgotten) ولماذا يصعب تنفيذه في نماذج اللغات الكبيرة (LLMs)؟",
    ideal_answer_en: "The Right to be Forgotten allows individuals to request the deletion of their personal data. It is extremely difficult in LLMs because data is not stored as discrete files, but rather baked into millions of mathematical weights during training. You cannot simply 'delete a file'; you often have to retrain the entire model from scratch.",
    ideal_answer_ar: "يسمح 'الحق في النسيان' للأفراد بطلب حذف بياناتهم الشخصية. هذا صعب للغاية في نماذج LLM لأن البيانات لا يتم تخزينها كملفات منفصلة، بل يتم دمجها في ملايين الأوزان الرياضية أثناء التدريب. لا يمكنك ببساطة 'حذف ملف'؛ بل تضطر غالباً إلى إعادة تدريب النموذج بأكمله من الصفر."
  },
  {
    id: "mb_l4_14", unit: "1", lesson: "1-4", type: "MCQ", source: "CLASSROOM", difficulty: "HARD",
    question_en: "An insurance company uses an AI that predicts health risks by analyzing users' grocery shopping habits from a partner app. Which ethical principle is breached here?",
    question_ar: "تستخدم شركة تأمين ذكاءً اصطناعياً يتوقع المخاطر الصحية من خلال تحليل عادات تسوق البقالة للمستخدمين من تطبيق شريك. ما هو المبدأ الأخلاقي الذي تم خرقه هنا؟",
    option_a_en: "Energy efficiency.",
    option_a_ar: "كفاءة الطاقة.",
    option_b_en: "Purpose Limitation and Informed Consent (using data collected for one benign purpose for a secondary, consequential purpose without consent).",
    option_b_ar: "تقييد الغرض والموافقة المستنيرة (استخدام البيانات التي تم جمعها لغرض حميد واحد لغرض ثانوي ذي عواقب دون موافقة).",
    option_c_en: "Model Overfitting.",
    option_c_ar: "فرط تخصيص النموذج.",
    option_d_en: "Zero-shot learning.",
    option_d_ar: "التعلم بدون أمثلة.",
    correct_option: "B",
    explanation_en: "Users agreed to share grocery data for a shopping app, not to be secretly profiled for health insurance rates.",
    explanation_ar: "وافق المستخدمون على مشاركة بيانات البقالة لتطبيق تسوق، وليس لتصنيفهم سراً لتحديد أسعار التأمين الصحي."
  },
  {
    id: "mb_l4_15", unit: "1", lesson: "1-4", type: "MCQ", source: "WEEKLY_ASSESSMENT", difficulty: "MEDIUM",
    question_en: "What is 'Surveillance Capitalism'?",
    question_ar: "ما هي 'رأسمالية المراقبة' (Surveillance Capitalism)؟",
    option_a_en: "Selling physical security cameras.",
    option_a_ar: "بيع كاميرات المراقبة المادية.",
    option_b_en: "An economic system centered around the commodification of personal data, often collected without explicit awareness, to predict and influence user behavior for profit.",
    option_b_ar: "نظام اقتصادي يتمحور حول تسليع البيانات الشخصية، التي تُجمع غالباً دون وعي صريح، للتنبؤ بسلوك المستخدم والتأثير عليه من أجل الربح.",
    option_c_en: "Using AI to monitor factory machines.",
    option_c_ar: "استخدام الذكاء الاصطناعي لمراقبة آلات المصنع.",
    option_d_en: "A secure banking protocol.",
    option_d_ar: "بروتوكول مصرفي آمن.",
    correct_option: "B",
    explanation_en: "Tech giants use AI to analyze our data exhaust (likes, location, browsing) to sell highly targeted behavioral predictions to advertisers.",
    explanation_ar: "تستخدم عمالقة التكنولوجيا الذكاء الاصطناعي لتحليل عوادم بياناتنا (الإعجابات، الموقع، التصفح) لبيع تنبؤات سلوكية مستهدفة للغاية للمعلنين."
  },
  {
    id: "mb_l4_16", unit: "1", lesson: "1-4", type: "MCQ", source: "HOMEWORK", difficulty: "HARD",
    question_en: "Why is 'Facial Recognition Technology' (FRT) heavily criticized and sometimes banned by city councils?",
    question_ar: "لماذا تتعرض 'تقنية التعرف على الوجه' (FRT) لانتقادات شديدة ويتم حظرها أحياناً من قبل مجالس المدن؟",
    option_a_en: "Because it makes cameras overheat.",
    option_a_ar: "لأنها تجعل الكاميرات ترتفع حرارتها.",
    option_b_en: "Due to high rates of false positives (especially among minorities), chilling effects on free speech, and the creation of mass surveillance states.",
    option_b_ar: "بسبب ارتفاع معدلات الإيجابيات الخاطئة (خاصة بين الأقليات)، والآثار المخيفة على حرية التعبير، وإنشاء دول مراقبة جماعية.",
    option_c_en: "It requires too much electricity.",
    option_c_ar: "تتطلب الكثير من الكهرباء.",
    option_d_en: "It cannot detect faces wearing glasses.",
    option_d_ar: "لا يمكنها اكتشاف الوجوه التي ترتدي نظارات.",
    correct_option: "B",
    explanation_en: "FRT has led to wrongful arrests due to algorithmic bias, and continuous public scanning destroys anonymity in public spaces.",
    explanation_ar: "أدت FRT إلى اعتقالات خاطئة بسبب التحيز الخوارزمي، كما أن المسح العام المستمر يدمر عدم الكشف عن الهوية في الأماكن العامة."
  },
  {
    id: "mb_l4_17", unit: "1", lesson: "1-4", type: "MCQ", source: "CLASSROOM", difficulty: "MEDIUM",
    question_en: "What does 'Transparency' in AI ethics mean?",
    question_ar: "ماذا تعني 'الشفافية' (Transparency) في أخلاقيات الذكاء الاصطناعي؟",
    option_a_en: "Making the computer casing out of glass.",
    option_a_ar: "صنع غلاف الكمبيوتر من الزجاج.",
    option_b_en: "Clearly informing users when they are interacting with an AI (e.g., a chatbot) and explaining how their data is used.",
    option_b_ar: "إعلام المستخدمين بوضوح عندما يتفاعلون مع الذكاء الاصطناعي (مثل روبوت الدردشة) وشرح كيفية استخدام بياناتهم.",
    option_c_en: "Giving away the source code for free.",
    option_c_ar: "التخلي عن الكود المصدري مجاناً.",
    option_d_en: "Uploading all company files to the internet.",
    option_d_ar: "تحميل جميع ملفات الشركة على الإنترنت.",
    correct_option: "B",
    explanation_en: "Transparency ensures that people are not deceived into thinking they are talking to a human, and that they understand data usage.",
    explanation_ar: "تضمن الشفافية عدم خداع الأشخاص للاعتقاد بأنهم يتحدثون إلى إنسان، وأنهم يفهمون استخدام البيانات."
  },
  {
    id: "mb_l4_18", unit: "1", lesson: "1-4", type: "MCQ", source: "WEEKLY_ASSESSMENT", difficulty: "HARD",
    question_en: "In the context of the AI 'Trolley Problem', what is the doctrine of 'Utilitarianism'?",
    question_ar: "في سياق 'معضلة العربة' الخاصة بالذكاء الاصطناعي، ما هو مبدأ 'النفعية' (Utilitarianism)؟",
    option_a_en: "The AI should always protect the owner of the vehicle.",
    option_a_ar: "يجب على الذكاء الاصطناعي دائماً حماية مالك السيارة.",
    option_b_en: "The AI should make the decision that results in the greatest good for the greatest number of people (e.g., minimizing total casualties).",
    option_b_ar: "يجب على الذكاء الاصطناعي اتخاذ القرار الذي يؤدي إلى تحقيق أكبر قدر من الخير لأكبر عدد من الأشخاص (مثل تقليل إجمالي الخسائر البشرية).",
    option_c_en: "The AI should do nothing and let fate decide.",
    option_c_ar: "يجب على الذكاء الاصطناعي ألا يفعل شيئاً ويترك القدر يقرر.",
    option_d_en: "The AI should always brake, regardless of context.",
    option_d_ar: "يجب على الذكاء الاصطناعي دائماً الفرملة، بغض النظر عن السياق.",
    correct_option: "B",
    explanation_en: "Utilitarianism is an ethical theory that aims to maximize overall well-being, meaning an AI might sacrifice one life to save five.",
    explanation_ar: "النفعية هي نظرية أخلاقية تهدف إلى تعظيم الرفاهية العامة، مما يعني أن الذكاء الاصطناعي قد يضحي بحياة شخص واحد لإنقاذ خمسة."
  },
  {
    id: "mb_l4_19", unit: "1", lesson: "1-4", type: "WRITTEN", source: "HOMEWORK", difficulty: "MEDIUM",
    question_en: "What is a 'Botnet' and how does it relate to IoT security?",
    question_ar: "ما هي 'شبكة الروبوت' (Botnet) وكيف ترتبط بأمان إنترنت الأشياء؟",
    ideal_answer_en: "A botnet is a network of private computers or IoT devices infected with malicious software and controlled as a group without the owners' knowledge. IoT devices are prime targets because they often lack built-in security, making them easy to hijack and use for massive cyberattacks.",
    ideal_answer_ar: "شبكة الروبوت هي شبكة من أجهزة الكمبيوتر الخاصة أو أجهزة IoT المصابة ببرامج ضارة ويتم التحكم فيها كمجموعة دون علم أصحابها. تُعد أجهزة IoT أهدافاً رئيسية لأنها غالباً ما تفتقر إلى الأمان المدمج، مما يسهل اختراقها واستخدامها في هجمات إلكترونية ضخمة."
  },
  {
    id: "mb_l4_20", unit: "1", lesson: "1-4", type: "MCQ", source: "WEEKLY_ASSESSMENT", difficulty: "HARD",
    question_en: "What does 'Red Teaming' refer to in AI development?",
    question_ar: "إلى ماذا يشير مصطلح 'الفريق الأحمر' (Red Teaming) في تطوير الذكاء الاصطناعي؟",
    option_a_en: "A team that designs the user interface.",
    option_a_ar: "الفريق الذي يصمم واجهة المستخدم.",
    option_b_en: "A group of security professionals specifically hired to attack and try to break the AI model to discover vulnerabilities and biases before it is released.",
    option_b_ar: "مجموعة من محترفي الأمن يتم توظيفهم خصيصاً لمهاجمة ومحاولة كسر نموذج الذكاء الاصطناعي لاكتشاف نقاط الضعف والتحيزات قبل إصداره.",
    option_c_en: "The marketing team.",
    option_c_ar: "فريق التسويق.",
    option_d_en: "A team that optimizes the model for red-colored hardware.",
    option_d_ar: "فريق يقوم بتحسين النموذج للأجهزة ذات اللون الأحمر.",
    correct_option: "B",
    explanation_en: "Red teaming is a crucial ethical step where humans intentionally try to make the AI generate hate speech, reveal private data, or hallucinate, in order to patch those flaws.",
    explanation_ar: "الفريق الأحمر هو خطوة أخلاقية حاسمة حيث يحاول البشر عمداً جعل الذكاء الاصطناعي يولد خطاب كراهية، أو يكشف عن بيانات خاصة، أو يهلوس، من أجل إصلاح تلك العيوب."
  }
];
