import type { QuizQuestion } from './courseData';

export const MASSIVE_BANK_L2: QuizQuestion[] = [
  // ------------------- LESSON 1.2 (20 QUESTIONS) -------------------
  {
    id: "mb_l2_01", unit: "1", lesson: "1-2", type: "MCQ", source: "CLASSROOM", difficulty: "MEDIUM",
    question_en: "What is the main goal of Natural Language Processing (NLP)?",
    question_ar: "ما هو الهدف الرئيسي لمعالجة اللغات الطبيعية (NLP)؟",
    option_a_en: "To allow computers to see and understand images.",
    option_a_ar: "السماح لأجهزة الكمبيوتر برؤية وفهم الصور.",
    option_b_en: "To enable computers to understand, interpret, and generate human language.",
    option_b_ar: "تمكين أجهزة الكمبيوتر من فهم وتفسير وتوليد اللغة البشرية.",
    option_c_en: "To write faster programming code.",
    option_c_ar: "لكتابة كود برمجة بشكل أسرع.",
    option_d_en: "To physically translate documents using robotics.",
    option_d_ar: "لترجمة المستندات مادياً باستخدام الروبوتات.",
    correct_option: "B",
    explanation_en: "NLP focuses on the interaction between computers and human languages.",
    explanation_ar: "يركز الـ NLP على التفاعل بين أجهزة الكمبيوتر واللغات البشرية."
  },
  {
    id: "mb_l2_02", unit: "1", lesson: "1-2", type: "MCQ", source: "HOMEWORK", difficulty: "MEDIUM",
    question_en: "Which of the following is a direct application of Computer Vision?",
    question_ar: "أي مما يلي هو تطبيق مباشر للرؤية الحاسوبية (Computer Vision)؟",
    option_a_en: "Translating an English book to Arabic.",
    option_a_ar: "ترجمة كتاب إنجليزي إلى العربية.",
    option_b_en: "Predicting stock market trends.",
    option_b_ar: "التنبؤ باتجاهات سوق الأسهم.",
    option_c_en: "Facial recognition to unlock a smartphone.",
    option_c_ar: "التعرف على الوجه لفتح قفل الهاتف الذكي.",
    option_d_en: "Recommending a song on Spotify.",
    option_d_ar: "التوصية بأغنية على سبوتيفاي.",
    correct_option: "C",
    explanation_en: "Facial recognition uses CV to analyze the visual features of a face.",
    explanation_ar: "يستخدم التعرف على الوجه الرؤية الحاسوبية لتحليل الميزات المرئية للوجه."
  },
  {
    id: "mb_l2_03", unit: "1", lesson: "1-2", type: "MCQ", source: "WEEKLY_ASSESSMENT", difficulty: "HARD",
    question_en: "In NLP, what is the purpose of 'Tokenization'?",
    question_ar: "في معالجة اللغات الطبيعية، ما هو الغرض من 'التقطيع' (Tokenization)؟",
    option_a_en: "Translating text into another language.",
    option_a_ar: "ترجمة النص إلى لغة أخرى.",
    option_b_en: "Breaking down a stream of text into smaller units like words or subwords.",
    option_b_ar: "تقسيم دفق النص إلى وحدات أصغر مثل الكلمات أو أجزاء الكلمات.",
    option_c_en: "Analyzing the emotion behind the text.",
    option_c_ar: "تحليل العاطفة الكامنة وراء النص.",
    option_d_en: "Removing punctuation marks.",
    option_d_ar: "إزالة علامات الترقيم.",
    correct_option: "B",
    explanation_en: "Tokenization is the first step in NLP, dividing text into manageable tokens for the model.",
    explanation_ar: "التقطيع هو الخطوة الأولى في NLP، حيث يقسم النص إلى وحدات (Tokens) قابلة للإدارة للنموذج."
  },
  {
    id: "mb_l2_04", unit: "1", lesson: "1-2", type: "WRITTEN", source: "HOMEWORK", difficulty: "MEDIUM",
    question_en: "Explain what 'Sentiment Analysis' is and provide a real-world business use case.",
    question_ar: "اشرح ما هو 'تحليل المشاعر' (Sentiment Analysis) وقدم حالة استخدام تجارية في العالم الحقيقي.",
    ideal_answer_en: "Sentiment Analysis determines the emotional tone (positive, negative, neutral) behind text. Business use case: A company automatically analyzing thousands of Twitter mentions to gauge customer reaction after launching a new product.",
    ideal_answer_ar: "يحدد تحليل المشاعر النغمة العاطفية (إيجابية، سلبية، محايدة) وراء النص. حالة الاستخدام التجاري: تقوم شركة بتحليل الآلاف من الإشارات على تويتر تلقائياً لقياس رد فعل العملاء بعد إطلاق منتج جديد."
  },
  {
    id: "mb_l2_05", unit: "1", lesson: "1-2", type: "MCQ", source: "CLASSROOM", difficulty: "HARD",
    question_en: "What type of neural network is traditionally most suited for processing sequential data like sentences in NLP?",
    question_ar: "ما هو نوع الشبكة العصبية الأنسب تقليدياً لمعالجة البيانات المتسلسلة مثل الجمل في الـ NLP؟",
    option_a_en: "Convolutional Neural Networks (CNNs)",
    option_a_ar: "الشبكات العصبية التلافيفية (CNNs)",
    option_b_en: "Recurrent Neural Networks (RNNs) and LSTMs",
    option_b_ar: "الشبكات العصبية المتكررة (RNNs) والـ LSTMs",
    option_c_en: "Decision Trees",
    option_c_ar: "أشجار القرار",
    option_d_en: "K-Means Clustering",
    option_d_ar: "تجميع K-Means",
    correct_option: "B",
    explanation_en: "RNNs and LSTMs have 'memory' loops that allow them to process sequences of data over time.",
    explanation_ar: "تمتلك RNNs و LSTMs حلقات 'ذاكرة' تسمح لها بمعالجة تسلسلات البيانات بمرور الوقت."
  },
  {
    id: "mb_l2_06", unit: "1", lesson: "1-2", type: "MCQ", source: "WEEKLY_ASSESSMENT", difficulty: "HARD",
    question_en: "In Computer Vision, what mathematical operation is primarily used by a Convolutional Neural Network (CNN) to extract features like edges and textures?",
    question_ar: "في الرؤية الحاسوبية، ما هي العملية الرياضية التي تستخدمها الشبكة التلافيفية (CNN) بشكل أساسي لاستخراج الميزات مثل الحواف والأنسجة؟",
    option_a_en: "Integration",
    option_a_ar: "التكامل",
    option_b_en: "Convolution (applying a filter matrix over the image matrix)",
    option_b_ar: "الالتفاف/التلافيف (تطبيق مصفوفة تصفية على مصفوفة الصورة)",
    option_c_en: "Matrix Inversion",
    option_c_ar: "عكس المصفوفة",
    option_d_en: "Logarithmic Scaling",
    option_d_ar: "القياس اللوغاريتمي",
    correct_option: "B",
    explanation_en: "Convolution involves sliding a small filter (kernel) over the image to detect specific patterns like horizontal or vertical lines.",
    explanation_ar: "يتضمن الالتفاف تمرير مرشح صغير (نواة) فوق الصورة لاكتشاف أنماط محددة مثل الخطوط الأفقية أو الرأسية."
  },
  {
    id: "mb_l2_07", unit: "1", lesson: "1-2", type: "MCQ", source: "HOMEWORK", difficulty: "MEDIUM",
    question_en: "Which of the following represents an AI hallucination in a Large Language Model?",
    question_ar: "أي مما يلي يمثل 'هلوسة الذكاء الاصطناعي' (AI Hallucination) في نموذج لغة كبير (LLM)؟",
    option_a_en: "The AI refusing to answer a harmful question.",
    option_a_ar: "الذكاء الاصطناعي يرفض الإجابة على سؤال ضار.",
    option_b_en: "The AI generating text very slowly.",
    option_b_ar: "الذكاء الاصطناعي يولد النص ببطء شديد.",
    option_c_en: "The AI confidently presenting fabricated facts or fake references as if they were true.",
    option_c_ar: "الذكاء الاصطناعي يقدم بثقة حقائق ملفقة أو مراجع مزيفة وكأنها حقيقية.",
    option_d_en: "The AI translating a word correctly.",
    option_d_ar: "الذكاء الاصطناعي يترجم كلمة بشكل صحيح.",
    correct_option: "C",
    explanation_en: "Hallucinations occur when an LLM generates plausible but entirely false information.",
    explanation_ar: "تحدث الهلوسة عندما يولد الـ LLM معلومات تبدو معقولة ولكنها خاطئة تماماً."
  },
  {
    id: "mb_l2_08", unit: "1", lesson: "1-2", type: "MCQ", source: "CLASSROOM", difficulty: "MEDIUM",
    question_en: "What is 'Object Detection'?",
    question_ar: "ما هو 'اكتشاف الأجسام' (Object Detection)؟",
    option_a_en: "Identifying the main subject of an image.",
    option_a_ar: "تحديد الموضوع الرئيسي للصورة.",
    option_b_en: "Locating and classifying multiple distinct objects within a single image, often drawing bounding boxes around them.",
    option_b_ar: "تحديد موقع وتصنيف عدة أجسام متميزة داخل صورة واحدة، غالباً عن طريق رسم مربعات إحاطة حولها.",
    option_c_en: "Generating 3D models from text.",
    option_c_ar: "توليد نماذج ثلاثية الأبعاد من النص.",
    option_d_en: "Enhancing the resolution of a blurred image.",
    option_d_ar: "تحسين دقة صورة غير واضحة.",
    correct_option: "B",
    explanation_en: "Object detection doesn't just say 'there is a dog', it says 'here is a dog (with a bounding box) and here is a cat (with a bounding box)'.",
    explanation_ar: "اكتشاف الأجسام لا يقول فقط 'يوجد كلب'، بل يقول 'هنا كلب (في هذا المربع) وهنا قطة (في هذا المربع)'."
  },
  {
    id: "mb_l2_09", unit: "1", lesson: "1-2", type: "WRITTEN", source: "WEEKLY_ASSESSMENT", difficulty: "HARD",
    question_en: "Why is 'Context' one of the hardest challenges in Natural Language Processing? Give an example.",
    question_ar: "لماذا يُعد 'السياق' (Context) أحد أصعب التحديات في معالجة اللغات الطبيعية؟ أعطِ مثالاً.",
    ideal_answer_en: "Words can have completely different meanings depending on surrounding words. Example: 'I went to the bank to deposit money' vs 'I sat by the river bank'. An NLP model must look at the whole sentence to understand which 'bank' is meant.",
    ideal_answer_ar: "يمكن أن يكون للكلمات معاني مختلفة تماماً اعتماداً على الكلمات المحيطة. مثال: 'عين الماء صافية' مقابل 'عين الرجل تؤلمه'. يجب أن ينظر نموذج NLP إلى الجملة بأكملها لفهم أي 'عين' يُقصد بها."
  },
  {
    id: "mb_l2_10", unit: "1", lesson: "1-2", type: "MCQ", source: "HOMEWORK", difficulty: "HARD",
    question_en: "In Computer Vision, what is 'Data Augmentation' used for?",
    question_ar: "في الرؤية الحاسوبية، فيمَ يُستخدم 'تكبير البيانات' (Data Augmentation)؟",
    option_a_en: "To compress image files to save disk space.",
    option_a_ar: "لضغط ملفات الصور لتوفير مساحة على القرص.",
    option_b_en: "To artificially increase the size of the training dataset by applying transformations (rotation, flipping, zooming) to existing images, preventing overfitting.",
    option_b_ar: "لزيادة حجم مجموعة بيانات التدريب بشكل مصطنع عن طريق تطبيق تحويلات (الدوران، الانعكاس، التكبير) على الصور الموجودة، لمنع فرط التخصيص.",
    option_c_en: "To colorize black-and-white photos.",
    option_c_ar: "لتلوين الصور بالأبيض والأسود.",
    option_d_en: "To remove the background from an image.",
    option_d_ar: "لإزالة الخلفية من الصورة.",
    correct_option: "B",
    explanation_en: "Augmentation helps the model generalize by showing it the same objects from different angles and lighting.",
    explanation_ar: "يساعد تكبير البيانات النموذج على التعميم من خلال إظهار نفس الأجسام له من زوايا وإضاءة مختلفة."
  },
  {
    id: "mb_l2_11", unit: "1", lesson: "1-2", type: "MCQ", source: "CLASSROOM", difficulty: "MEDIUM",
    question_en: "Which NLP task involves determining who or what a pronoun refers to in a sentence?",
    question_ar: "ما هي مهمة NLP التي تتضمن تحديد من أو ما يشير إليه الضمير في الجملة؟",
    option_a_en: "Named Entity Recognition (NER)",
    option_a_ar: "التعرف على الكيانات المسماة (NER)",
    option_b_en: "Coreference Resolution",
    option_b_ar: "تحليل المرجعية (Coreference Resolution)",
    option_c_en: "Part-of-Speech Tagging",
    option_c_ar: "تحديد أجزاء الكلام",
    option_d_en: "Machine Translation",
    option_d_ar: "الترجمة الآلية",
    correct_option: "B",
    explanation_en: "Coreference resolution links pronouns (he, she, it) back to the entities they describe.",
    explanation_ar: "يربط تحليل المرجعية الضمائر (هو، هي، إياه) بالكيانات التي تصفها في النص."
  },
  {
    id: "mb_l2_12", unit: "1", lesson: "1-2", type: "MCQ", source: "WEEKLY_ASSESSMENT", difficulty: "HARD",
    question_en: "What does 'Zero-Shot Learning' mean in the context of advanced NLP models like GPT-4?",
    question_ar: "ماذا يعني 'التعلم بدون أمثلة' (Zero-Shot Learning) في سياق نماذج NLP المتقدمة مثل GPT-4؟",
    option_a_en: "The model learns instantly in zero seconds.",
    option_a_ar: "يتعلم النموذج على الفور في صفر ثانية.",
    option_b_en: "The model is able to perform a task it was not explicitly trained for, just by reading the prompt instructions, without needing any example pairs.",
    option_b_ar: "أن يكون النموذج قادراً على أداء مهمة لم يتم تدريبه صراحةً عليها، بمجرد قراءة تعليمات الطلب، دون الحاجة إلى أي أزواج من الأمثلة.",
    option_c_en: "The model consumes zero electrical power during inference.",
    option_c_ar: "يستهلك النموذج طاقة كهربائية صفرية أثناء الاستدلال.",
    option_d_en: "The model requires zero data to be trained initially.",
    option_d_ar: "يتطلب النموذج بيانات صفرية ليتم تدريبه في البداية.",
    correct_option: "B",
    explanation_en: "Zero-shot means giving a task to the AI (like 'translate to French') without providing examples of the translation in the prompt.",
    explanation_ar: "يعني Zero-shot إعطاء مهمة للذكاء الاصطناعي (مثل 'ترجم إلى الفرنسية') دون تقديم أمثلة للترجمة في المُوجّه (Prompt)."
  },
  {
    id: "mb_l2_13", unit: "1", lesson: "1-2", type: "MCQ", source: "HOMEWORK", difficulty: "MEDIUM",
    question_en: "Which technique allows AI to generate completely new, realistic images (like deepfakes)?",
    question_ar: "ما هي التقنية التي تسمح للذكاء الاصطناعي بتوليد صور واقعية جديدة تماماً (مثل التزييف العميق Deepfakes)؟",
    option_a_en: "Generative Adversarial Networks (GANs) or Diffusion Models.",
    option_a_ar: "شبكات التوليد التنافسية (GANs) أو نماذج الانتشار (Diffusion Models).",
    option_b_en: "Linear Regression.",
    option_b_ar: "الانحدار الخطي.",
    option_c_en: "K-Nearest Neighbors.",
    option_c_ar: "أقرب جار (KNN).",
    option_d_en: "Optical Character Recognition (OCR).",
    option_d_ar: "التعرف البصري على الحروف (OCR).",
    correct_option: "A",
    explanation_en: "GANs and Diffusion Models are generative AI architectures used specifically to create new, synthetic image data.",
    explanation_ar: "GANs ونماذج الانتشار هي بنيات ذكاء اصطناعي توليدي تُستخدم خصيصاً لإنشاء بيانات صور اصطناعية جديدة."
  },
  {
    id: "mb_l2_14", unit: "1", lesson: "1-2", type: "WRITTEN", source: "WEEKLY_ASSESSMENT", difficulty: "HARD",
    question_en: "Explain the concept of 'Word Embeddings' and how it solves the problem of vocabulary mismatch in NLP.",
    question_ar: "اشرح مفهوم 'تضمين الكلمات' (Word Embeddings) وكيف يحل مشكلة عدم تطابق المفردات في NLP.",
    ideal_answer_en: "Word embeddings represent words as dense vectors of numbers in a high-dimensional space where words with similar meanings are mathematically close to each other. It solves mismatch because the model knows 'happy' and 'joyful' are near each other, instead of treating them as completely unrelated strings.",
    ideal_answer_ar: "يمثل 'تضمين الكلمات' الكلمات كمتجهات كثيفة من الأرقام في مساحة عالية الأبعاد حيث تكون الكلمات ذات المعاني المتشابهة قريبة من بعضها رياضياً. يحل عدم التطابق لأن النموذج يعرف أن 'سعيد' و'مبتهج' متقاربان، بدلاً من التعامل معهما كسلاسل نصية غير مرتبطة تماماً."
  },
  {
    id: "mb_l2_15", unit: "1", lesson: "1-2", type: "MCQ", source: "CLASSROOM", difficulty: "MEDIUM",
    question_en: "What is 'Optical Character Recognition' (OCR)?",
    question_ar: "ما هو 'التعرف البصري على الحروف' (OCR)؟",
    option_a_en: "Using AI to write essays.",
    option_a_ar: "استخدام الذكاء الاصطناعي لكتابة المقالات.",
    option_b_en: "Using Computer Vision to convert images of typed or handwritten text into machine-encoded digital text.",
    option_b_ar: "استخدام الرؤية الحاسوبية لتحويل صور النص المكتوب أو المطبوع إلى نص رقمي مشفر آلياً.",
    option_c_en: "A physical camera lens.",
    option_c_ar: "عدسة كاميرا مادية.",
    option_d_en: "Translating voice to text.",
    option_d_ar: "ترجمة الصوت إلى نص.",
    correct_option: "B",
    explanation_en: "OCR is used in scanners and apps (like Google Lens) to pull copyable text out of images.",
    explanation_ar: "يُستخدم OCR في الماسحات الضوئية والتطبيقات (مثل Google Lens) لاستخراج نص قابل للنسخ من الصور."
  },
  {
    id: "mb_l2_16", unit: "1", lesson: "1-2", type: "MCQ", source: "WEEKLY_ASSESSMENT", difficulty: "HARD",
    question_en: "If an NLP system is suffering from catastrophic forgetting, what has likely occurred?",
    question_ar: "إذا كان نظام الـ NLP يعاني من 'النسيان الكارثي' (Catastrophic Forgetting)، فما الذي حدث على الأرجح؟",
    option_a_en: "The server lost its memory drive.",
    option_a_ar: "فقد الخادم محرك الذاكرة الخاص به.",
    option_b_en: "The neural network, upon being trained on a new task, completely overwrote the weights and 'forgot' how to perform the old tasks it previously knew.",
    option_b_ar: "الشبكة العصبية، عند تدريبها على مهمة جديدة، قامت بالكتابة فوق الأوزان بالكامل و'نسيت' كيفية أداء المهام القديمة التي كانت تعرفها مسبقاً.",
    option_c_en: "The dataset was too small.",
    option_c_ar: "مجموعة البيانات كانت صغيرة جداً.",
    option_d_en: "The system's dropout layer was disabled.",
    option_d_ar: "تم تعطيل طبقة الإسقاط (Dropout) في النظام.",
    correct_option: "B",
    explanation_en: "Catastrophic forgetting is a major issue in continual learning where fine-tuning a model on new data destroys its prior knowledge.",
    explanation_ar: "النسيان الكارثي هو مشكلة رئيسية في التعلم المستمر حيث يؤدي التدريب الدقيق لنموذج على بيانات جديدة إلى تدمير معرفته السابقة."
  },
  {
    id: "mb_l2_17", unit: "1", lesson: "1-2", type: "MCQ", source: "HOMEWORK", difficulty: "MEDIUM",
    question_en: "Which metric is commonly used to evaluate the overlap between predicted bounding boxes and ground truth boxes in Object Detection?",
    question_ar: "ما هو المقياس الشائع استخدامه لتقييم التداخل بين 'مربعات الإحاطة' المتوقعة ومربعات الحقيقة (Ground Truth) في اكتشاف الأجسام؟",
    option_a_en: "Intersection over Union (IoU)",
    option_a_ar: "التقاطع على الاتحاد (IoU)",
    option_b_en: "Mean Squared Error",
    option_b_ar: "متوسط الخطأ التربيعي",
    option_c_en: "Perplexity",
    option_c_ar: "الحيرة (Perplexity)",
    option_d_en: "Cosine Similarity",
    option_d_ar: "تشابه جيب التمام",
    correct_option: "A",
    explanation_en: "IoU divides the area of overlap by the area of union to score how perfectly the predicted box covers the actual object.",
    explanation_ar: "يقسم IoU مساحة التداخل على مساحة الاتحاد لتسجيل مدى دقة تغطية المربع المتوقع للجسم الفعلي."
  },
  {
    id: "mb_l2_18", unit: "1", lesson: "1-2", type: "MCQ", source: "CLASSROOM", difficulty: "HARD",
    question_en: "In transformers, why is 'Positional Encoding' necessary?",
    question_ar: "في المحولات (Transformers)، لماذا تعتبر 'الترميز الموضعي' (Positional Encoding) ضرورية؟",
    option_a_en: "To translate the text.",
    option_a_ar: "لترجمة النص.",
    option_b_en: "Because transformers process all words simultaneously (parallel processing) and lack a built-in sense of sequence order; positional encoding injects the order back in.",
    option_b_ar: "لأن المحولات تعالج جميع الكلمات في وقت واحد وتفتقر إلى إحساس متأصل بترتيب التسلسل؛ يقوم الترميز الموضعي بحقن الترتيب مرة أخرى.",
    option_c_en: "To encode images into text.",
    option_c_ar: "لتشفير الصور إلى نص.",
    option_d_en: "To reduce the file size of the model.",
    option_d_ar: "لتقليل حجم ملف النموذج.",
    correct_option: "B",
    explanation_en: "Unlike RNNs which read words one by one, transformers read everything at once. Without positional encoding, 'dog bites man' and 'man bites dog' would look mathematically identical.",
    explanation_ar: "على عكس RNNs التي تقرأ الكلمات واحدة تلو الأخرى، تقرأ المحولات كل شيء دفعة واحدة. بدون الترميز الموضعي، ستبدو 'الكلب يعض الرجل' و 'الرجل يعض الكلب' متطابقة رياضياً."
  },
  {
    id: "mb_l2_19", unit: "1", lesson: "1-2", type: "WRITTEN", source: "HOMEWORK", difficulty: "HARD",
    question_en: "Describe the 'Attention Mechanism' intuitively.",
    question_ar: "صف 'آلية الانتباه' (Attention Mechanism) بشكل بديهي.",
    ideal_answer_en: "The Attention Mechanism allows a neural network to 'focus' on specific parts of the input data that are most relevant to predicting the current output, much like how humans pay attention to specific words in a sentence when translating it.",
    ideal_answer_ar: "تسمح 'آلية الانتباه' للشبكة العصبية بـ 'التركيز' على أجزاء محددة من بيانات الإدخال الأكثر صلة بتوقع المخرجات الحالية، تماماً كما ينتبه البشر إلى كلمات معينة في الجملة عند ترجمتها."
  },
  {
    id: "mb_l2_20", unit: "1", lesson: "1-2", type: "MCQ", source: "WEEKLY_ASSESSMENT", difficulty: "MEDIUM",
    question_en: "What does 'Semantic Segmentation' mean in Computer Vision?",
    question_ar: "ماذا يعني 'التجزئة الدلالية' (Semantic Segmentation) في الرؤية الحاسوبية؟",
    option_a_en: "Drawing one large box around everything in an image.",
    option_a_ar: "رسم مربع واحد كبير حول كل شيء في صورة.",
    option_b_en: "Categorizing every single pixel in an image to a specific class (e.g., painting all road pixels gray, all sky pixels blue).",
    option_b_ar: "تصنيف كل بكسل في الصورة إلى فئة محددة (مثل تلوين جميع بكسلات الطريق باللون الرمادي، وكل بكسلات السماء بالأزرق).",
    option_c_en: "Only recognizing text in an image.",
    option_c_ar: "التعرف فقط على النص في الصورة.",
    option_d_en: "Adjusting the brightness of an image.",
    option_d_ar: "تعديل سطوع الصورة.",
    correct_option: "B",
    explanation_en: "Unlike object detection (which uses boxes), segmentation outlines the exact pixel boundaries of objects.",
    explanation_ar: "على عكس اكتشاف الأجسام (الذي يستخدم المربعات)، تحدد التجزئة حدود البكسل الدقيقة للأجسام."
  }
];
