import type { QuizQuestion } from './courseData';

export const MASSIVE_BANK_L3: QuizQuestion[] = [
  // ------------------- LESSON 1.3 (20 QUESTIONS) -------------------
  {
    id: "mb_l3_01", unit: "1", lesson: "les_1_3", type: "MCQ", source: "CLASSROOM", difficulty: "MEDIUM",
    question_en: "What does 'IoT' stand for?",
    question_ar: "ماذا يعني اختصار 'IoT'؟",
    option_a_en: "Internet of Technology",
    option_a_ar: "إنترنت التكنولوجيا",
    option_b_en: "Internet of Things",
    option_b_ar: "إنترنت الأشياء",
    option_c_en: "Internal Organization Transfer",
    option_c_ar: "النقل التنظيمي الداخلي",
    option_d_en: "Input Output Telemetry",
    option_d_ar: "القياس عن بعد للمدخلات والمخرجات",
    correct_option: "B",
    explanation_en: "IoT stands for Internet of Things, referring to physical objects connected to the internet.",
    explanation_ar: "يرمز IoT إلى إنترنت الأشياء، ويشير إلى الأشياء المادية المتصلة بالإنترنت."
  },
  {
    id: "mb_l3_02", unit: "1", lesson: "les_1_3", type: "MCQ", source: "HOMEWORK", difficulty: "MEDIUM",
    question_en: "Which of the following is a primary characteristic of a Smart Home device?",
    question_ar: "أي مما يلي يُعد خاصية أساسية لجهاز 'المنزل الذكي'؟",
    option_a_en: "It must run on solar power.",
    option_a_ar: "يجب أن يعمل بالطاقة الشمسية.",
    option_b_en: "It requires a physical remote control.",
    option_b_ar: "يتطلب جهاز تحكم عن بعد مادي.",
    option_c_en: "It connects to a network allowing remote monitoring, control, and automation.",
    option_c_ar: "يتصل بشبكة تتيح المراقبة عن بُعد، والتحكم، والأتمتة.",
    option_d_en: "It cannot be updated once purchased.",
    option_d_ar: "لا يمكن تحديثه بمجرد شرائه.",
    correct_option: "C",
    explanation_en: "Connectivity and automation are the defining features of smart devices.",
    explanation_ar: "الاتصال والأتمتة هما الميزتان المحددتان للأجهزة الذكية."
  },
  {
    id: "mb_l3_03", unit: "1", lesson: "les_1_3", type: "MCQ", source: "WEEKLY_ASSESSMENT", difficulty: "HARD",
    question_en: "How does 'Edge Computing' differ from traditional 'Cloud Computing' in IoT environments?",
    question_ar: "كيف تختلف 'حوسبة الحافة' (Edge Computing) عن 'الحوسبة السحابية' التقليدية في بيئات الـ IoT؟",
    option_a_en: "Edge computing relies entirely on satellite connections.",
    option_a_ar: "تعتمد حوسبة الحافة بالكامل على اتصالات الأقمار الصناعية.",
    option_b_en: "Edge computing processes data locally near the data source, reducing latency, whereas cloud computing sends all data to centralized servers.",
    option_b_ar: "حوسبة الحافة تعالج البيانات محلياً بالقرب من مصدر البيانات، مما يقلل التأخير، بينما ترسل الحوسبة السحابية جميع البيانات إلى خوادم مركزية.",
    option_c_en: "Edge computing is only used for smartphones.",
    option_c_ar: "تستخدم حوسبة الحافة للهواتف الذكية فقط.",
    option_d_en: "There is no technical difference.",
    option_d_ar: "لا يوجد فرق تقني.",
    correct_option: "B",
    explanation_en: "Edge computing is crucial for time-sensitive IoT applications (like autonomous cars) because it avoids the round-trip delay to the cloud.",
    explanation_ar: "تعتبر حوسبة الحافة حاسمة لتطبيقات إنترنت الأشياء الحساسة للوقت (مثل السيارات ذاتية القيادة) لأنها تتجنب تأخير الرحلة ذهاباً وإياباً إلى السحابة."
  },
  {
    id: "mb_l3_04", unit: "1", lesson: "les_1_3", type: "WRITTEN", source: "HOMEWORK", difficulty: "HARD",
    question_en: "Provide an example of how IoT and AI combine in 'Smart Agriculture'.",
    question_ar: "قدم مثالاً على كيفية الجمع بين إنترنت الأشياء (IoT) والذكاء الاصطناعي (AI) في 'الزراعة الذكية'.",
    ideal_answer_en: "IoT soil moisture sensors stream real-time data to a central hub. AI algorithms analyze this data alongside weather forecasts to automatically trigger irrigation systems only exactly when needed, saving water and maximizing crop yield.",
    ideal_answer_ar: "تقوم مستشعرات رطوبة التربة (IoT) ببث بيانات في الوقت الفعلي. تقوم خوارزميات الذكاء الاصطناعي بتحليل هذه البيانات مع توقعات الطقس لتشغيل أنظمة الري تلقائياً فقط عند الحاجة بالضبط، مما يوفر المياه ويزيد الغلة."
  },
  {
    id: "mb_l3_05", unit: "1", lesson: "les_1_3", type: "MCQ", source: "CLASSROOM", difficulty: "MEDIUM",
    question_en: "What protocol is commonly used by smart home devices to form low-power mesh networks?",
    question_ar: "ما هو البروتوكول الشائع استخدامه من قبل أجهزة المنزل الذكي لتكوين شبكات متداخلة (Mesh Networks) منخفضة الطاقة؟",
    option_a_en: "HTTP",
    option_a_ar: "بروتوكول HTTP",
    option_b_en: "Zigbee or Z-Wave",
    option_b_ar: "Zigbee أو Z-Wave",
    option_c_en: "Ethernet",
    option_c_ar: "إيثرنت (Ethernet)",
    option_d_en: "SMTP",
    option_d_ar: "بروتوكول SMTP",
    correct_option: "B",
    explanation_en: "Zigbee and Z-Wave are standard protocols for smart home automation because they use very little power and can route messages through each other.",
    explanation_ar: "Zigbee و Z-Wave هما بروتوكولان قياسيان لأتمتة المنزل الذكي لأنهما يستهلكان طاقة قليلة جداً ويمكنهما توجيه الرسائل عبر بعضهما البعض."
  },
  {
    id: "mb_l3_06", unit: "1", lesson: "les_1_3", type: "MCQ", source: "WEEKLY_ASSESSMENT", difficulty: "HARD",
    question_en: "Why is 'Interoperability' a major challenge in the Smart Home industry?",
    question_ar: "لماذا يُعد 'التوافقية' (Interoperability) تحدياً رئيسياً في صناعة المنازل الذكية؟",
    option_a_en: "Devices use too much electricity.",
    option_a_ar: "الأجهزة تستهلك الكثير من الكهرباء.",
    option_b_en: "Devices from different manufacturers often use proprietary protocols and cannot communicate with each other natively.",
    option_b_ar: "غالباً ما تستخدم أجهزة الشركات المصنعة المختلفة بروتوكولات مملوكة لها ولا يمكنها التواصل مع بعضها البعض محلياً.",
    option_c_en: "Wi-Fi signals are blocked by walls.",
    option_c_ar: "إشارات الـ Wi-Fi يتم حجبها بالجدران.",
    option_d_en: "People do not know how to install them.",
    option_d_ar: "الناس لا يعرفون كيفية تثبيتها.",
    correct_option: "B",
    explanation_en: "A Samsung fridge might not easily 'talk' to an Apple HomeKit thermostat without intermediary bridges, creating fragmented ecosystems (though Matter is trying to solve this).",
    explanation_ar: "ثلاجة سامسونج قد لا 'تتحدث' بسهولة مع منظم حرارة من آبل بدون جسور وسيطة، مما يخلق أنظمة بيئية مجزأة (على الرغم من أن بروتوكول Matter يحاول حل ذلك)."
  },
  {
    id: "mb_l3_07", unit: "1", lesson: "les_1_3", type: "MCQ", source: "HOMEWORK", difficulty: "MEDIUM",
    question_en: "Which of the following is an example of an IoT 'Actuator'?",
    question_ar: "أي مما يلي يعتبر مثالاً لـ 'المُشغّل' (Actuator) في إنترنت الأشياء؟",
    option_a_en: "A temperature sensor",
    option_a_ar: "مستشعر حرارة",
    option_b_en: "A camera lens",
    option_b_ar: "عدسة كاميرا",
    option_c_en: "A smart motor that automatically opens a window blind",
    option_c_ar: "محرك ذكي يفتح ستارة النافذة تلقائياً",
    option_d_en: "A database storing logs",
    option_d_ar: "قاعدة بيانات تخزن السجلات",
    correct_option: "C",
    explanation_en: "Sensors collect data; Actuators perform physical actions (moving, turning on/off) based on that data.",
    explanation_ar: "المستشعرات تجمع البيانات؛ أما المشغلات فتنفذ إجراءات مادية (تحريك، تشغيل/إيقاف) بناءً على تلك البيانات."
  },
  {
    id: "mb_l3_08", unit: "1", lesson: "les_1_3", type: "MCQ", source: "CLASSROOM", difficulty: "HARD",
    question_en: "In the context of Smart Cities, what is a 'Digital Twin'?",
    question_ar: "في سياق المدن الذكية، ما هو 'التوأم الرقمي' (Digital Twin)؟",
    option_a_en: "A backup server located in another city.",
    option_a_ar: "خادم احتياطي يقع في مدينة أخرى.",
    option_b_en: "A virtual replica of a physical city asset (like a bridge or power grid) updated in real-time via IoT sensors, used for simulation and predictive maintenance.",
    option_b_ar: "نسخة افتراضية طبق الأصل من أصول المدينة المادية (مثل جسر أو شبكة طاقة) يتم تحديثها في الوقت الفعلي عبر مستشعرات IoT، تُستخدم للمحاكاة والصيانة التنبؤية.",
    option_c_en: "Two AI assistants communicating with each other.",
    option_c_ar: "مساعدان من الذكاء الاصطناعي يتواصلان مع بعضهما البعض.",
    option_d_en: "A physical robot designed to look like a human.",
    option_d_ar: "روبوت مادي مصمم ليبدو كإنسان.",
    correct_option: "B",
    explanation_en: "Digital Twins allow city planners to simulate the impact of traffic changes or natural disasters on the digital model before trying it in the real world.",
    explanation_ar: "تسمح التوائم الرقمية لمخططي المدن بمحاكاة تأثير تغيرات المرور أو الكوارث الطبيعية على النموذج الرقمي قبل تجربتها في العالم الحقيقي."
  },
  {
    id: "mb_l3_09", unit: "1", lesson: "les_1_3", type: "WRITTEN", source: "WEEKLY_ASSESSMENT", difficulty: "HARD",
    question_en: "Explain the security risk of a 'DDoS attack' utilizing IoT smart home devices.",
    question_ar: "اشرح المخاطر الأمنية لـ 'هجوم حجب الخدمة الموزع' (DDoS attack) الذي يستغل أجهزة إنترنت الأشياء المنزلية الذكية.",
    ideal_answer_en: "IoT devices often have weak default passwords. Hackers can infect thousands of smart cameras/fridges with malware, turning them into a 'botnet'. These devices are then commanded simultaneously to flood a target website with traffic, causing it to crash.",
    ideal_answer_ar: "غالباً ما تحتوي أجهزة IoT على كلمات مرور افتراضية ضعيفة. يمكن للقراصنة إصابة الآلاف من الكاميرات/الثلاجات الذكية ببرامج ضارة، وتحويلها إلى 'شبكة روبوت' (botnet). يُطلب من هذه الأجهزة بعد ذلك إغراق موقع ويب مستهدف بحركة المرور في وقت واحد، مما يؤدي إلى تعطله."
  },
  {
    id: "mb_l3_10", unit: "1", lesson: "les_1_3", type: "MCQ", source: "HOMEWORK", difficulty: "MEDIUM",
    question_en: "What role does 5G technology play in the expansion of IoT?",
    question_ar: "ما هو الدور الذي تلعبه تقنية الجيل الخامس (5G) في توسيع نطاق إنترنت الأشياء (IoT)؟",
    option_a_en: "It replaces the need for electricity.",
    option_a_ar: "تحل محل الحاجة إلى الكهرباء.",
    option_b_en: "It provides much higher bandwidth, incredibly low latency, and allows a massive density of connected devices per square kilometer.",
    option_b_ar: "توفر نطاقاً ترددياً أعلى بكثير، وزمن انتقال (Latency) منخفض جداً، وتسمح بكثافة هائلة من الأجهزة المتصلة في الكيلومتر المربع.",
    option_c_en: "It is solely used for streaming 4K movies.",
    option_c_ar: "تُستخدم فقط لبث أفلام 4K.",
    option_d_en: "It limits the number of devices that can connect.",
    option_d_ar: "تحد من عدد الأجهزة التي يمكنها الاتصال.",
    correct_option: "B",
    explanation_en: "5G solves the network congestion problem, allowing smart cities to have millions of sensors transmitting data simultaneously in real-time.",
    explanation_ar: "تحل شبكات الجيل الخامس مشكلة ازدحام الشبكة، مما يسمح للمدن الذكية بامتلاك ملايين المستشعرات التي تنقل البيانات في وقت واحد وفي الوقت الفعلي."
  },
  {
    id: "mb_l3_11", unit: "1", lesson: "les_1_3", type: "MCQ", source: "CLASSROOM", difficulty: "HARD",
    question_en: "What is 'Geofencing' in smart home automation?",
    question_ar: "ما هو السياج الجغرافي (Geofencing) في أتمتة المنزل الذكي؟",
    option_a_en: "Building a physical electronic fence around a house.",
    option_a_ar: "بناء سياج إلكتروني مادي حول المنزل.",
    option_b_en: "Using GPS or RFID to define a virtual geographical boundary, triggering an action (like turning on lights) when a user's smartphone crosses it.",
    option_b_ar: "استخدام GPS لتعريف حدود جغرافية افتراضية، مما يؤدي إلى إطلاق إجراء (مثل تشغيل الأضواء) عندما يتخطاه الهاتف الذكي للمستخدم.",
    option_c_en: "Scanning the earth for Wi-Fi signals.",
    option_c_ar: "مسح الأرض بحثاً عن إشارات Wi-Fi.",
    option_d_en: "Encrypting local network data.",
    option_d_ar: "تشفير بيانات الشبكة المحلية.",
    correct_option: "B",
    explanation_en: "Geofencing allows homes to proactively prepare for your arrival by detecting when your phone enters the 'fence' radius.",
    explanation_ar: "يسمح السياج الجغرافي للمنازل بالاستعداد بشكل استباقي لوصولك من خلال اكتشاف وقت دخول هاتفك إلى نصف قطر 'السياج'."
  },
  {
    id: "mb_l3_12", unit: "1", lesson: "les_1_3", type: "MCQ", source: "WEEKLY_ASSESSMENT", difficulty: "MEDIUM",
    question_en: "In a smart hospital, what is the main benefit of IoT-enabled patient wristbands?",
    question_ar: "في المستشفى الذكي، ما هي الفائدة الرئيسية لأساور المرضى التي تدعم إنترنت الأشياء؟",
    option_a_en: "They play music to calm the patient.",
    option_a_ar: "تشغيل الموسيقى لتهدئة المريض.",
    option_b_en: "Continuous, real-time monitoring of vital signs and location tracking, automatically alerting nurses to emergencies.",
    option_b_ar: "المراقبة المستمرة في الوقت الفعلي للعلامات الحيوية وتتبع الموقع، لتنبيه الممرضات تلقائياً في حالات الطوارئ.",
    option_c_en: "They replace doctors entirely.",
    option_c_ar: "يحلون محل الأطباء تماماً.",
    option_d_en: "They allow the patient to access the internet.",
    option_d_ar: "يسمحون للمريض بالوصول إلى الإنترنت.",
    correct_option: "B",
    explanation_en: "Continuous monitoring catches deterioration long before a scheduled manual check by a nurse.",
    explanation_ar: "المراقبة المستمرة تكتشف التدهور قبل وقت طويل من الفحص اليدوي المجدول من قبل الممرضة."
  },
  {
    id: "mb_l3_13", unit: "1", lesson: "les_1_3", type: "WRITTEN", source: "HOMEWORK", difficulty: "HARD",
    question_en: "How can Smart Grids (an application of IoT) prevent massive blackouts?",
    question_ar: "كيف يمكن للشبكات الذكية (Smart Grids) - أحد تطبيقات IoT - منع انقطاع التيار الكهربائي الواسع؟",
    ideal_answer_en: "Smart Grids use sensors to monitor real-time electricity consumption and AI to predict demand peaks. They can automatically reroute power around damaged lines or communicate with smart homes to temporarily reduce non-essential power usage (like pausing A/C units) to balance the load and prevent a grid collapse.",
    ideal_answer_ar: "تستخدم الشبكات الذكية مستشعرات لمراقبة استهلاك الكهرباء في الوقت الفعلي والذكاء الاصطناعي لتوقع ذروة الطلب. يمكنها إعادة توجيه الطاقة تلقائياً حول الخطوط التالفة أو التواصل مع المنازل الذكية لتقليل استخدام الطاقة غير الضرورية مؤقتاً (مثل إيقاف المكيفات) لموازنة الحمل ومنع انهيار الشبكة."
  },
  {
    id: "mb_l3_14", unit: "1", lesson: "les_1_3", type: "MCQ", source: "CLASSROOM", difficulty: "HARD",
    question_en: "What is the primary function of a 'Smart Hub' (like Amazon Echo or SmartThings hub) in an IoT ecosystem?",
    question_ar: "ما هي الوظيفة الأساسية لـ 'الموزع الذكي' (مثل Amazon Echo أو SmartThings) في النظام البيئي لإنترنت الأشياء؟",
    option_a_en: "To boost Wi-Fi speed.",
    option_a_ar: "لزيادة سرعة الـ Wi-Fi.",
    option_b_en: "To act as a central bridge that translates different protocols (Wi-Fi, Zigbee, Bluetooth) so disparate devices can be controlled from one interface.",
    option_b_ar: "العمل كجسر مركزي يترجم البروتوكولات المختلفة حتى يمكن التحكم في الأجهزة المتباينة من واجهة واحدة.",
    option_c_en: "To store electricity.",
    option_c_ar: "لتخزين الكهرباء.",
    option_d_en: "To physically clean the house.",
    option_d_ar: "لتنظيف المنزل مادياً.",
    correct_option: "B",
    explanation_en: "Hubs solve the interoperability problem by speaking all the 'languages' of different smart devices and unifying them in one app.",
    explanation_ar: "تحل الموزعات مشكلة التوافق من خلال التحدث بجميع 'لغات' الأجهزة الذكية المختلفة وتوحيدها في تطبيق واحد."
  },
  {
    id: "mb_l3_15", unit: "1", lesson: "les_1_3", type: "MCQ", source: "WEEKLY_ASSESSMENT", difficulty: "MEDIUM",
    question_en: "Which ethical issue is most prominently raised by the proliferation of Smart Home cameras and microphones?",
    question_ar: "ما هي المشكلة الأخلاقية الأبرز التي يثيرها انتشار كاميرات وميكروفونات المنازل الذكية؟",
    option_a_en: "High cost of electricity.",
    option_a_ar: "ارتفاع تكلفة الكهرباء.",
    option_b_en: "Severe invasions of privacy and potential surveillance by tech companies or hackers.",
    option_b_ar: "الانتهاكات الشديدة للخصوصية والمراقبة المحتملة من قبل شركات التكنولوجيا أو القراصنة.",
    option_c_en: "The devices break too easily.",
    option_c_ar: "الأجهزة تنكسر بسهولة جداً.",
    option_d_en: "They make homes too warm.",
    option_d_ar: "تجل المنازل دافئة أكثر من اللازم.",
    correct_option: "B",
    explanation_en: "Always-on microphones and cameras inside private residences pose unprecedented privacy risks if data is not securely encrypted.",
    explanation_ar: "تشكل الميكروفونات والكاميرات التي تعمل دائماً داخل المساكن الخاصة مخاطر غير مسبوقة على الخصوصية إذا لم يتم تشفير البيانات بشكل آمن."
  },
  {
    id: "mb_l3_16", unit: "1", lesson: "les_1_3", type: "MCQ", source: "HOMEWORK", difficulty: "HARD",
    question_en: "What is 'Predictive Maintenance' in Industrial IoT (IIoT)?",
    question_ar: "ما هي 'الصيانة التنبؤية' (Predictive Maintenance) في إنترنت الأشياء الصناعي (IIoT)؟",
    option_a_en: "Fixing a machine after it breaks completely.",
    option_a_ar: "إصلاح الآلة بعد أن تنكسر تماماً.",
    option_b_en: "Using AI to analyze sensor data (vibration, heat) from machinery to predict and fix failures *before* they occur.",
    option_b_ar: "استخدام AI لتحليل بيانات المستشعرات من الآلات للتنبؤ بالأعطال وإصلاحها *قبل* حدوثها.",
    option_c_en: "Predicting the stock price of manufacturing companies.",
    option_c_ar: "التنبؤ بسعر سهم شركات التصنيع.",
    option_d_en: "Replacing all human workers with robots.",
    option_d_ar: "استبدال جميع العمال البشريين بالروبوتات.",
    correct_option: "B",
    explanation_en: "Predictive maintenance saves factories millions by preventing unexpected downtime.",
    explanation_ar: "الصيانة التنبؤية توفر للمصانع الملايين عن طريق منع التوقف غير المتوقع عن العمل."
  },
  {
    id: "mb_l3_17", unit: "1", lesson: "les_1_3", type: "MCQ", source: "CLASSROOM", difficulty: "MEDIUM",
    question_en: "What is an 'RFID tag' commonly used for in IoT?",
    question_ar: "فيم تُستخدم 'علامة RFID' بشكل شائع في إنترنت الأشياء؟",
    option_a_en: "Generating artificial intelligence.",
    option_a_ar: "توليد ذكاء اصطناعي.",
    option_b_en: "Tracking physical inventory and assets as they move through a supply chain.",
    option_b_ar: "تتبع المخزون والأصول المادية أثناء انتقالها عبر سلسلة التوريد.",
    option_c_en: "Cooling down servers.",
    option_c_ar: "تبريد الخوادم.",
    option_d_en: "Typing code.",
    option_d_ar: "كتابة الكود.",
    correct_option: "B",
    explanation_en: "RFID tags allow smart systems to instantly know what products are in a warehouse without manually scanning barcodes.",
    explanation_ar: "تسمح علامات RFID للأنظمة الذكية بمعرفة المنتجات الموجودة في المستودع على الفور دون مسح الرموز الشريطية يدوياً."
  },
  {
    id: "mb_l3_18", unit: "1", lesson: "les_1_3", type: "MCQ", source: "WEEKLY_ASSESSMENT", difficulty: "HARD",
    question_en: "In an IoT architecture, what is the role of a 'Gateway'?",
    question_ar: "في بنية إنترنت الأشياء (IoT)، ما هو دور 'البوابة' (Gateway)؟",
    option_a_en: "It acts as an intermediary that collects data from local sensors, sometimes pre-processes it, and then securely transmits it to the external cloud.",
    option_a_ar: "تعمل كوسيط يجمع البيانات من المستشعرات المحلية، ويعالجها مسبقاً أحياناً، ثم ينقلها بأمان إلى السحابة الخارجية.",
    option_b_en: "It is the main database storing all cloud data.",
    option_b_ar: "هي قاعدة البيانات الرئيسية التي تخزن جميع البيانات السحابية.",
    option_c_en: "It is a physical door in a smart home.",
    option_c_ar: "هي باب مادي في منزل ذكي.",
    option_d_en: "It writes the AI algorithms.",
    option_d_ar: "تقوم بكتابة خوارزميات الذكاء الاصطناعي.",
    correct_option: "A",
    explanation_en: "Sensors often lack the power or security features to talk directly to the cloud. The gateway bridges this gap securely.",
    explanation_ar: "غالباً ما تفتقر المستشعرات إلى الطاقة أو ميزات الأمان للتحدث مباشرة إلى السحابة. تعمل البوابة على سد هذه الفجوة بأمان."
  },
  {
    id: "mb_l3_19", unit: "1", lesson: "les_1_3", type: "WRITTEN", source: "HOMEWORK", difficulty: "HARD",
    question_en: "Describe how a Smart City utilizes IoT to optimize waste management.",
    question_ar: "صف كيف تستخدم المدينة الذكية إنترنت الأشياء (IoT) لتحسين إدارة النفايات.",
    ideal_answer_en: "Smart trash cans are equipped with ultrasonic fill-level sensors. Instead of garbage trucks driving fixed routes daily (wasting fuel and time), the IoT system calculates a dynamic, optimized route every morning, targeting only the bins that are actually full.",
    ideal_answer_ar: "تم تجهيز صناديق القمامة الذكية بمستشعرات فوق صوتية لقياس مستوى الامتلاء. بدلاً من قيادة شاحنات القمامة في مسارات ثابتة يومياً (مما يهدر الوقود)، يقوم نظام IoT بحساب مسار ديناميكي محسن كل صباح، مستهدفاً فقط الصناديق الممتلئة فعلياً."
  },
  {
    id: "mb_l3_20", unit: "1", lesson: "les_1_3", type: "MCQ", source: "WEEKLY_ASSESSMENT", difficulty: "MEDIUM",
    question_en: "Which of the following describes a 'Wearable' IoT device?",
    question_ar: "أي مما يلي يصف جهاز إنترنت أشياء 'قابل للارتداء' (Wearable)؟",
    option_a_en: "A smart refrigerator.",
    option_a_ar: "ثلاجة ذكية.",
    option_b_en: "A smartwatch that tracks your steps and heart rate.",
    option_b_ar: "ساعة ذكية تتبع خطواتك ومعدل ضربات قلبك.",
    option_c_en: "A self-driving car.",
    option_c_ar: "سيارة ذاتية القيادة.",
    option_d_en: "A smart TV.",
    option_d_ar: "تلفزيون ذكي.",
    correct_option: "B",
    explanation_en: "Wearables are IoT devices worn on the body, primarily used for health, fitness, and communication tracking.",
    explanation_ar: "الأجهزة القابلة للارتداء هي أجهزة IoT تُلبس على الجسم، وتستخدم أساساً لتتبع الصحة واللياقة البدنية والتواصل."
  }
];
