import type { QuizQuestion } from './courseData';

export const MASSIVE_BANK: QuizQuestion[] = [
  // Lesson 1.1: AI & ML Concepts (Hard Scenario Questions)
  {
    id: "mb_1_1_1",
    unit: "1",
    lesson: "les_1_1",
    type: "MCQ",
    source: "WEEKLY_ASSESSMENT",
    difficulty: "HARD",
    question_en: "A hospital uses an AI system to prioritize patients in the ER. The system was trained on 10 years of historical data but is suddenly misclassifying urgent cases. What is the most critical first step to diagnose this?",
    question_ar: "مستشفى يستخدم نظام ذكاء اصطناعي لترتيب أولوية المرضى في الطوارئ. تم تدريب النظام على بيانات تاريخية لـ 10 سنوات ولكنه بدأ فجأة يخطئ في تصنيف الحالات العاجلة. ما هي الخطوة الأولى الأهم لتشخيص هذه المشكلة؟",
    option_a_en: "Retrain the model from scratch using a deeper neural network.",
    option_a_ar: "إعادة تدريب النموذج من الصفر باستخدام شبكة عصبية أعمق.",
    option_b_en: "Check for Data Drift, as recent patient profiles or diseases (e.g., a new virus) may differ from the 10-year historical data.",
    option_b_ar: "التحقق من انحراف البيانات (Data Drift)، لأن ملفات المرضى الحديثة أو الأمراض (مثل فيروس جديد) قد تختلف عن البيانات التاريخية.",
    option_c_en: "Increase the learning rate to make the model adapt faster.",
    option_c_ar: "زيادة معدل التعلم لجعل النموذج يتكيف بشكل أسرع.",
    option_d_en: "Switch from Supervised Learning to Unsupervised Learning.",
    option_d_ar: "التحول من التعلم الخاضع للإشراف إلى التعلم غير الخاضع للإشراف.",
    correct_option: "B",
    explanation_en: "Data drift occurs when the statistical properties of the target variable change over time. Historical data may not represent current realities (e.g., post-pandemic data).",
    explanation_ar: "يحدث انحراف البيانات عندما تتغير الخصائص الإحصائية بمرور الوقت. البيانات القديمة قد لا تمثل الواقع الحالي (مثل أمراض جديدة ظهرت)."
  },
  {
    id: "mb_1_1_2",
    unit: "1",
    lesson: "les_1_1",
    type: "MCQ",
    source: "HOMEWORK",
    difficulty: "HARD",
    question_en: "You are building an AI to detect fraudulent bank transactions. Fraud occurs in only 0.1% of cases. If your model achieves 99.9% accuracy, why might this be a terrible model?",
    question_ar: "أنت تبني نظام ذكاء اصطناعي لاكتشاف المعاملات البنكية الاحتيالية. يحدث الاحتيال في 0.1% فقط من الحالات. إذا حقق نموذجك دقة 99.9%، فلماذا قد يكون هذا النموذج فاشلاً؟",
    option_a_en: "Because 99.9% accuracy means the model is overfitting.",
    option_a_ar: "لأن دقة 99.9% تعني أن النموذج يعاني من فرط التخصيص (Overfitting).",
    option_b_en: "Because it might just be predicting 'Not Fraud' for every single transaction, completely failing to catch the 0.1% of actual fraud.",
    option_b_ar: "لأنه قد يتوقع ببساطة 'ليس احتيالاً' لكل معاملة، مما يجعله يفشل تماماً في اكتشاف الـ 0.1% من الاحتيال الفعلي.",
    option_c_en: "Because banking systems require exactly 100% accuracy by law.",
    option_c_ar: "لأن الأنظمة البنكية تتطلب دقة 100% بالضبط بموجب القانون.",
    option_d_en: "It is actually a perfect model and ready for production.",
    option_d_ar: "إنه في الواقع نموذج مثالي وجاهز للإنتاج.",
    correct_option: "B",
    explanation_en: "In highly imbalanced datasets, Accuracy is a misleading metric. A 'dumb' model that always predicts the majority class will have high accuracy but zero recall for the minority class.",
    explanation_ar: "في مجموعات البيانات غير المتوازنة، مقياس 'الدقة' مضلل. النموذج الغبي الذي يتوقع دائماً الفئة الأغلبية سيحقق دقة عالية ولكنه لن يكتشف أي حالة احتيال فعلية."
  },
  {
    id: "mb_1_1_3",
    unit: "1",
    lesson: "les_1_1",
    type: "WRITTEN",
    source: "WEEKLY_ASSESSMENT",
    difficulty: "HARD",
    question_en: "Explain the 'Black Box' problem in Deep Learning and propose two methods to mitigate its risks in medical diagnosis AI.",
    question_ar: "اشرح مشكلة 'الصندوق الأسود' في التعلم العميق واقترح طريقتين للتخفيف من مخاطرها في أنظمة الذكاء الاصطناعي للتشخيص الطبي.",
    ideal_answer_en: "The Black Box problem refers to the inability of humans to understand exactly how a Deep Learning model arrived at its prediction due to millions of hidden parameters. Mitigation: 1) Use Explainable AI (XAI) tools like SHAP or LIME to highlight which features influenced the decision. 2) Employ a human-in-the-loop system where AI only suggests, but a human doctor makes the final call.",
    ideal_answer_ar: "مشكلة الصندوق الأسود تعني عدم قدرة البشر على فهم كيفية توصل نموذج التعلم العميق إلى قراره بسبب ملايين المعلمات المخفية. للحد من ذلك: 1) استخدام أدوات الذكاء الاصطناعي القابل للتفسير (XAI) لتوضيح العوامل المؤثرة. 2) إبقاء 'الإنسان في الحلقة' بحيث يقترح الذكاء الاصطناعي فقط ويقوم الطبيب باتخاذ القرار النهائي."
  },
  {
    id: "mb_1_1_4",
    unit: "1",
    lesson: "les_1_1",
    type: "MCQ",
    source: "CLASSROOM",
    difficulty: "HARD",
    question_en: "If a Reinforcement Learning agent is tasked with playing chess and it begins sacrificing its queen in every game without winning, what is the most likely flaw?",
    question_ar: "إذا تم تكليف وكيل 'تعلم معزز' (Reinforcement Learning) بلعب الشطرنج وبدأ في التضحية بالوزير في كل لعبة دون تحقيق الفوز، فما هو الخلل الأكثر احتمالاً؟",
    option_a_en: "The dataset provided was too small.",
    option_a_ar: "مجموعة البيانات المقدمة كانت صغيرة جداً.",
    option_b_en: "The Reward Function is poorly designed, perhaps rewarding pieces captured rather than winning the game.",
    option_b_ar: "دالة المكافأة (Reward Function) مصممة بشكل سيء، ربما تكافئ على التقاط القطع بدلاً من الفوز باللعبة.",
    option_c_en: "The agent is experiencing Vanishing Gradients.",
    option_c_ar: "الوكيل يعاني من مشكلة تلاشي التدرجات (Vanishing Gradients).",
    option_d_en: "Chess cannot be solved by Reinforcement Learning.",
    option_d_ar: "لا يمكن حل لعبة الشطرنج باستخدام التعلم المعزز.",
    correct_option: "B",
    explanation_en: "In RL, the agent optimizes solely for the defined reward function. If the rewards don't align with the ultimate goal, the agent will learn bizarre behaviors (reward hacking).",
    explanation_ar: "في التعلم المعزز، يُحسّن الوكيل أداءه فقط بناءً على دالة المكافأة المحددة. إذا كانت المكافآت لا تتماشى مع الهدف النهائي، سيتعلم الوكيل سلوكيات غريبة (اختراق المكافأة)."
  },

  // Lesson 1.2: NLP & CV (Hard Scenario Questions)
  {
    id: "mb_1_2_1",
    unit: "1",
    lesson: "les_1_2",
    type: "MCQ",
    source: "WEEKLY_ASSESSMENT",
    difficulty: "HARD",
    question_en: "A sentiment analysis NLP model keeps classifying the sentence 'The movie was not bad at all' as NEGATIVE. What linguistic processing step is likely failing?",
    question_ar: "نموذج تحليل المشاعر (NLP) يستمر في تصنيف جملة 'الفيلم لم يكن سيئاً على الإطلاق' على أنها سلبية. ما هي خطوة المعالجة اللغوية التي تفشل على الأرجح؟",
    option_a_en: "Tokenization is removing the word 'bad'.",
    option_a_ar: "عملية التقطيع (Tokenization) تقوم بإزالة كلمة 'سيء'.",
    option_b_en: "The model uses a simple Bag-of-Words (BoW) approach that ignores word order and negation context.",
    option_b_ar: "النموذج يستخدم نهج 'حقيبة الكلمات' (BoW) البسيط الذي يتجاهل ترتيب الكلمات وسياق النفي.",
    option_c_en: "Stop-word removal deleted the word 'movie'.",
    option_c_ar: "إزالة كلمات التوقف (Stop-words) حذفت كلمة 'فيلم'.",
    option_d_en: "The word embeddings are too dense.",
    option_d_ar: "تضمين الكلمات (Word embeddings) كثيف جداً.",
    correct_option: "B",
    explanation_en: "Bag-of-Words counts frequencies but ignores sequence. It sees 'bad' and assumes negative, completely missing the preceding 'not'. Contextual models like LSTMs or Transformers solve this.",
    explanation_ar: "حقيبة الكلمات تحسب التكرار ولكنها تتجاهل التسلسل. فهي ترى كلمة 'سيء' وتفترض السلبية، متجاهلة النفي الذي يسبقها. النماذج السياقية مثل Transformers تحل هذه المشكلة."
  },
  {
    id: "mb_1_2_2",
    unit: "1",
    lesson: "les_1_2",
    type: "MCQ",
    source: "HOMEWORK",
    difficulty: "HARD",
    question_en: "In Computer Vision, if an autonomous vehicle fails to detect stop signs specifically at dusk or dawn, what is the core issue with the Convolutional Neural Network (CNN)?",
    question_ar: "في الرؤية الحاسوبية، إذا فشلت مركبة ذاتية القيادة في اكتشاف إشارات التوقف تحديداً عند الغسق أو الفجر، فما هي المشكلة الأساسية في الشبكة العصبية التلافيفية (CNN)؟",
    option_a_en: "The CNN lacks pooling layers.",
    option_a_ar: "تفتقر الـ CNN إلى طبقات التجميع (Pooling layers).",
    option_b_en: "The training dataset lacked sufficient variance in lighting and weather conditions.",
    option_b_ar: "مجموعة بيانات التدريب افتقرت إلى التنوع الكافي في ظروف الإضاءة والطقس.",
    option_c_en: "The activation function used is ReLU instead of Sigmoid.",
    option_c_ar: "دالة التنشيط المستخدمة هي ReLU بدلاً من Sigmoid.",
    option_d_en: "The camera resolution is too high for the network.",
    option_d_ar: "دقة الكاميرا عالية جداً بالنسبة للشبكة.",
    correct_option: "B",
    explanation_en: "AI models only 'know' what they are trained on. If the dataset only contains brightly lit midday images, the model will fail to generalize to low-light conditions.",
    explanation_ar: "نماذج الذكاء الاصطناعي 'تعرف' فقط ما تدربت عليه. إذا كانت البيانات تحتوي فقط على صور مضاءة جيداً في منتصف النهار، سيفشل النموذج في التعميم على ظروف الإضاءة المنخفضة."
  },
  {
    id: "mb_1_2_3",
    unit: "1",
    lesson: "les_1_2",
    type: "WRITTEN",
    source: "WEEKLY_ASSESSMENT",
    difficulty: "HARD",
    question_en: "Compare the use of Recurrent Neural Networks (RNNs) vs. Transformers for real-time live speech translation. Which is better and why?",
    question_ar: "قارن بين استخدام الشبكات العصبية المتكررة (RNNs) والمحولات (Transformers) لترجمة الكلام المباشر في الوقت الفعلي. أيهما أفضل ولماذا؟",
    ideal_answer_en: "Transformers are generally better. While RNNs process data sequentially (word by word), which is slow and loses long-term context, Transformers use self-attention to process entire sequences in parallel, capturing deep context and achieving far superior translation quality and speed.",
    ideal_answer_ar: "المحولات (Transformers) أفضل بكثير. بينما تعالج RNNs البيانات بشكل تسلسلي (كلمة بكلمة) مما يجعلها بطيئة وتفقد السياق الطويل، تستخدم المحولات 'الانتباه الذاتي' لمعالجة تسلسلات كاملة بالتوازي، مما يلتقط السياق العميق ويحقق جودة وسرعة ترجمة فائقة."
  },

  // Lesson 1.3: Smart Homes & IoT (Hard Scenario Questions)
  {
    id: "mb_1_3_1",
    unit: "1",
    lesson: "les_1_3",
    type: "MCQ",
    source: "WEEKLY_ASSESSMENT",
    difficulty: "HARD",
    question_en: "An IoT smart city grid analyzes traffic patterns to optimize traffic lights. To ensure millisecond responsiveness during a sudden accident, what network architecture is required?",
    question_ar: "شبكة مدينة ذكية (IoT) تحلل أنماط المرور لتحسين إشارات المرور. لضمان استجابة في أجزاء من الثانية أثناء حادث مفاجئ، ما هي بنية الشبكة المطلوبة؟",
    option_a_en: "Centralized Cloud Computing.",
    option_a_ar: "الحوسبة السحابية المركزية.",
    option_b_en: "Edge Computing (processing data locally on the traffic cameras/nodes).",
    option_b_ar: "حوسبة الحافة (Edge Computing) (معالجة البيانات محلياً على كاميرات/عقد المرور).",
    option_c_en: "Bluetooth Low Energy (BLE) meshes.",
    option_c_ar: "شبكات البلوتوث منخفض الطاقة (BLE).",
    option_d_en: "Batch Processing at the end of the day.",
    option_d_ar: "المعالجة الدفعية في نهاية اليوم.",
    correct_option: "B",
    explanation_en: "Edge computing processes data locally at the source (the edge of the network), eliminating the latency of sending data back and forth to a distant cloud server, which is critical for real-time safety.",
    explanation_ar: "حوسبة الحافة تعالج البيانات محلياً عند المصدر (حافة الشبكة)، مما يزيل تأخير إرسال البيانات ذهاباً وإياباً إلى خادم سحابي بعيد، وهو أمر بالغ الأهمية لسلامة الوقت الفعلي."
  },
  {
    id: "mb_1_3_2",
    unit: "1",
    lesson: "les_1_3",
    type: "MCQ",
    source: "CLASSROOM",
    difficulty: "HARD",
    question_en: "A smart home's thermostat learns that you like the house at 22°C when you arrive at 6 PM. However, it relies heavily on your smartphone's GPS. What is a primary vulnerability of this specific integration?",
    question_ar: "جهاز تنظيم الحرارة الذكي في المنزل تعلم أنك تفضل حرارة 22 درجة مئوية عند وصولك الساعة 6 مساءً. ولكنه يعتمد بشدة على نظام تحديد المواقع (GPS) الخاص بهاتفك. ما هي نقطة الضعف الأساسية في هذا التكامل المعين؟",
    option_a_en: "The AI cannot understand Celsius vs Fahrenheit.",
    option_a_ar: "الذكاء الاصطناعي لا يمكنه فهم الفرق بين مئوية وفهرنهايت.",
    option_b_en: "If the smartphone battery dies or GPS signal is lost, the predictive automation completely fails.",
    option_b_ar: "إذا نفدت بطارية الهاتف الذكي أو فُقدت إشارة الـ GPS، فإن الأتمتة التنبؤية تفشل تماماً.",
    option_c_en: "GPS satellites are known to manipulate home temperatures.",
    option_c_ar: "أقمار الـ GPS معروفة بتلاعبها في درجات حرارة المنازل.",
    option_d_en: "It requires a wired ethernet connection to work.",
    option_d_ar: "يتطلب اتصال إيثرنت سلكي ليعمل.",
    correct_option: "B",
    explanation_en: "IoT systems that rely on single points of external sensory input (like a phone's GPS) are fragile. A robust system uses multi-sensor fusion (e.g., motion sensors + GPS + time).",
    explanation_ar: "أنظمة إنترنت الأشياء التي تعتمد على نقطة واحدة من الإدخال الحسي الخارجي (مثل GPS الهاتف) تكون هشة. النظام القوي يستخدم دمج مستشعرات متعددة (مثل مستشعرات الحركة + GPS + الوقت)."
  },

  // Lesson 1.4: AI Ethics (Hard Scenario Questions)
  {
    id: "mb_1_4_1",
    unit: "1",
    lesson: "les_1_4",
    type: "MCQ",
    source: "WEEKLY_ASSESSMENT",
    difficulty: "HARD",
    question_en: "A highly advanced AI hiring tool was found to penalize resumes containing the word 'women's' (e.g., 'women's chess club captain'). What is the root cause of this ethical failure?",
    question_ar: "تم اكتشاف أن أداة توظيف متقدمة جداً تعمل بالذكاء الاصطناعي تعاقب السير الذاتية التي تحتوي على كلمة 'نسائية' (مثل 'كابتن نادي الشطرنج النسائي'). ما هو السبب الجذري لهذا الفشل الأخلاقي؟",
    option_a_en: "The AI became self-aware and developed its own malicious opinions.",
    option_a_ar: "أصبح الذكاء الاصطناعي واعياً بذاته وطور آراء خبيثة خاصة به.",
    option_b_en: "The programming code inherently contained an 'if-else' statement penalizing women.",
    option_b_ar: "كود البرمجة كان يحتوي بشكل أساسي على جملة شرطية تعاقب النساء.",
    option_c_en: "The model was trained on historical company hiring data that inherently contained human biases against female candidates.",
    option_c_ar: "تم تدريب النموذج على بيانات التوظيف التاريخية للشركة والتي كانت تحتوي أصلاً على تحيزات بشرية ضد المرشحات الإناث.",
    option_d_en: "The neural network was too shallow to understand grammar.",
    option_d_ar: "الشبكة العصبية كانت سطحية جداً لفهم القواعد النحوية.",
    correct_option: "C",
    explanation_en: "AI models amplify existing biases in training data. If human recruiters historically favored men, the AI learns this correlation as a 'rule' for success.",
    explanation_ar: "نماذج الذكاء الاصطناعي تضخم التحيزات الموجودة في بيانات التدريب. إذا كان مسؤولو التوظيف من البشر يفضلون الرجال تاريخياً، فإن الذكاء الاصطناعي يتعلم هذا الارتباط كـ 'قاعدة' للنجاح."
  },
  {
    id: "mb_1_4_2",
    unit: "1",
    lesson: "les_1_4",
    type: "WRITTEN",
    source: "HOMEWORK",
    difficulty: "HARD",
    question_en: "Discuss the 'Trolley Problem' in the context of autonomous vehicles. If a self-driving car must choose between swerving into a barrier (harming the passenger) or hitting a pedestrian, how should the algorithm be programmed ethically?",
    question_ar: "ناقش 'معضلة العربة' (Trolley Problem) في سياق المركبات ذاتية القيادة. إذا كان يجب على السيارة ذاتية القيادة الاختيار بين الانحراف نحو حاجز (مما يؤذي الراكب) أو صدم أحد المشاة، كيف ينبغي برمجة الخوارزمية أخلاقياً؟",
    ideal_answer_en: "There is no single correct answer, but it involves Utilitarianism (minimizing total harm) versus Duty of Care (protecting the occupant). Ethically, companies are shifting towards programming cars to strictly follow traffic laws and prioritize braking over swerving, removing active 'decision-making' over who lives or dies, and pushing for regulatory frameworks.",
    ideal_answer_ar: "لا توجد إجابة واحدة صحيحة، ولكنها تشمل النفعية (تقليل الضرر الكلي) مقابل واجب الرعاية (حماية الراكب). أخلاقياً، تتجه الشركات نحو برمجة السيارات لاتباع قوانين المرور بصرامة وإعطاء الأولوية للفرملة بدلاً من الانحراف، وإزالة 'اتخاذ القرار' النشط حول من يعيش أو يموت، والدفع نحو وضع أطر تنظيمية قانونية."
  },

  // ================= BATCH 2: MORE HARD QUESTIONS =================
  {
    id: "mb_b2_1",
    unit: "1",
    lesson: "les_1_1",
    type: "MCQ",
    source: "WEEKLY_ASSESSMENT",
    difficulty: "HARD",
    question_en: "An autonomous drone is trained using Reinforcement Learning to navigate a dense forest. It keeps crashing into thin branches but avoids thick tree trunks perfectly. What is the most likely algorithmic or sensory failure?",
    question_ar: "طائرة بدون طيار مستقلة تم تدريبها باستخدام 'التعلم المعزز' للتنقل في غابة كثيفة. الطائرة تستمر في الاصطدام بالأغصان الرفيعة لكنها تتجنب جذوع الأشجار السميكة بشكل مثالي. ما هو الفشل الخوارزمي أو الحسي الأكثر احتمالاً؟",
    option_a_en: "The drone's reward function penalizes crashing too heavily, causing it to freeze.",
    option_a_ar: "دالة المكافأة للطائرة تعاقب الاصطدام بشدة، مما يسبب تجمّدها.",
    option_b_en: "The LiDAR or vision sensors have low spatial resolution, failing to capture thin structures during the state representation phase.",
    option_b_ar: "مستشعرات الرؤية أو الـ LiDAR ذات دقة مكانية منخفضة، وتفشل في التقاط الهياكل الرفيعة أثناء مرحلة تمثيل الحالة (State representation).",
    option_c_en: "The learning rate of the neural network was set too low.",
    option_c_ar: "معدل التعلم للشبكة العصبية تم ضبطه ليكون منخفضاً جداً.",
    option_d_en: "The agent is using Q-learning instead of Deep Q-Networks (DQN).",
    option_d_ar: "الوكيل يستخدم Q-learning بدلاً من Deep Q-Networks (DQN).",
    correct_option: "B",
    explanation_en: "In RL, the agent relies entirely on its observation space (sensors). If thin branches are invisible to the sensors (low resolution), the AI cannot learn to avoid them, regardless of the algorithm.",
    explanation_ar: "في التعلم المعزز، يعتمد الوكيل كلياً على مساحة المراقبة (المستشعرات). إذا كانت الأغصان الرفيعة غير مرئية للمستشعرات، فلن يتعلم الذكاء الاصطناعي تجنبها مهما كانت الخوارزمية قوية."
  },
  {
    id: "mb_b2_2",
    unit: "1",
    lesson: "les_1_1",
    type: "MCQ",
    source: "HOMEWORK",
    difficulty: "HARD",
    question_en: "In a binary classification ML problem (e.g., Cancer vs. No Cancer), you notice that precision is 98% but recall is 40%. What does this signify in a real-world medical context?",
    question_ar: "في مشكلة تصنيف ثنائي (مثال: سرطان مقابل لا سرطان)، لاحظت أن الدقة (Precision) 98% ولكن الاستدعاء (Recall) 40%. ماذا يعني هذا في السياق الطبي الحقيقي؟",
    option_a_en: "The model is excellent because 98% of people tested are healthy.",
    option_a_ar: "النموذج ممتاز لأن 98% من الأشخاص الذين تم اختبارهم أصحاء.",
    option_b_en: "The model is highly cautious; when it predicts cancer, it is almost always right, but it misses 60% of actual cancer patients.",
    option_b_ar: "النموذج حذر جداً؛ عندما يتوقع 'سرطان' يكون محقاً دائماً تقريباً، ولكنه يغفل عن 60% من مرضى السرطان الفعليين.",
    option_c_en: "The model is randomly guessing and the data is imbalanced.",
    option_c_ar: "النموذج يخمن عشوائياً والبيانات غير متوازنة.",
    option_d_en: "The model predicts everyone has cancer to be safe.",
    option_d_ar: "النموذج يتوقع أن الجميع مصابون بالسرطان ليكون في الجانب الآمن.",
    correct_option: "B",
    explanation_en: "High precision means few false positives. Low recall means many false negatives. In medicine, low recall is deadly because sick patients are sent home undiagnosed.",
    explanation_ar: "الدقة العالية تعني إيجابيات خاطئة قليلة. الاستدعاء المنخفض يعني سلبيات خاطئة كثيرة (مرضى يُقال لهم أنهم أصحاء). في الطب، الاستدعاء المنخفض مميت."
  },
  {
    id: "mb_b2_3",
    unit: "1",
    lesson: "les_1_2",
    type: "WRITTEN",
    source: "WEEKLY_ASSESSMENT",
    difficulty: "HARD",
    question_en: "Consider an AI used for real-time sign language translation via computer vision. It performs perfectly in the lab but fails in real-world users' homes. Discuss two specific data biases or environmental factors causing this generalization gap.",
    question_ar: "ضع في اعتبارك ذكاءً اصطناعياً يُستخدم لترجمة لغة الإشارة في الوقت الفعلي عبر الرؤية الحاسوبية. إنه يعمل بشكل مثالي في المختبر ولكنه يفشل في منازل المستخدمين في العالم الحقيقي. ناقش تحيزين محددين في البيانات أو عوامل بيئية تسبب هذه الفجوة في التعميم.",
    ideal_answer_en: "1) Lighting & Background bias: Lab data often has perfect lighting and solid green-screen backgrounds. Real homes have dynamic lighting, shadows, and cluttered backgrounds that confuse object detection. 2) Demographic/Angle bias: The model might have been trained on specific skin tones, hand shapes, or exact camera angles, failing when a user has a different skin tone or places the webcam at a high/low angle.",
    ideal_answer_ar: "1) تحيز الإضاءة والخلفية: غالباً ما تتمتع بيانات المختبر بإضاءة مثالية وخلفيات خضراء صلبة. المنازل الحقيقية بها إضاءة ديناميكية وظلال وخلفيات فوضوية تربك اكتشاف الأجسام. 2) تحيز ديموغرافي/زاوية: قد يكون النموذج دُرب على ألوان بشرة محددة، أو أشكال أيدي، أو زوايا كاميرا دقيقة، مما يفشل عندما يكون للمستخدم لون بشرة مختلف أو يضع الكاميرا بزاوية مختلفة."
  },
  {
    id: "mb_b2_4",
    unit: "1",
    lesson: "les_1_2",
    type: "MCQ",
    source: "CLASSROOM",
    difficulty: "HARD",
    question_en: "Which architectural feature allows Transformer models (like GPT) to heavily outperform Recurrent Neural Networks (RNNs) in resolving pronoun ambiguity in long texts?",
    question_ar: "ما هي الميزة المعمارية التي تسمح لنماذج المحولات (Transformers) بالتفوق بشكل كبير على الشبكات العصبية المتكررة (RNNs) في حل غموض الضمائر في النصوص الطويلة؟",
    option_a_en: "Backpropagation through time (BPTT).",
    option_a_ar: "الانتشار الخلفي عبر الزمن (BPTT).",
    option_b_en: "Self-Attention Mechanism, which allows the model to look at all words in a sequence simultaneously to determine context.",
    option_b_ar: "آلية الانتباه الذاتي (Self-Attention)، والتي تسمح للنموذج بالنظر إلى جميع الكلمات في التسلسل في وقت واحد لتحديد السياق.",
    option_c_en: "Max Pooling layers that extract the most important noun.",
    option_c_ar: "طبقات التجميع الأقصى (Max Pooling) التي تستخرج الاسم الأكثر أهمية.",
    option_d_en: "Word2Vec embeddings.",
    option_d_ar: "تضمين Word2Vec.",
    correct_option: "B",
    explanation_en: "Self-attention calculates a weight between every pair of words in a sentence, allowing the model to instantly see that 'it' refers to 'the street' even if they are 50 words apart.",
    explanation_ar: "يحسب الانتباه الذاتي وزناً بين كل زوج من الكلمات في الجملة، مما يسمح للنموذج بأن يرى على الفور أن الضمير 'هو' يعود على 'الشارع' حتى لو كان بينهما 50 كلمة."
  },
  {
    id: "mb_b2_5",
    unit: "1",
    lesson: "les_1_2",
    type: "MCQ",
    source: "HOMEWORK",
    difficulty: "HARD",
    question_en: "In a Generative Adversarial Network (GAN) generating fake faces, what happens if the Discriminator becomes too accurate too quickly during early training?",
    question_ar: "في شبكات التوليد التنافسية (GAN) التي تولد وجوهاً مزيفة، ماذا يحدث إذا أصبح 'المُميِّز' (Discriminator) دقيقاً جداً وبسرعة كبيرة خلال التدريب المبكر؟",
    option_a_en: "The Generator learns faster because it gets clear feedback.",
    option_a_ar: "يتعلم المُولّد (Generator) بشكل أسرع لأنه يحصل على ملاحظات واضحة.",
    option_b_en: "The Generator suffers from vanishing gradients; it receives a near-zero gradient signal and stops learning entirely.",
    option_b_ar: "يعاني المُولّد من تلاشي التدرجات؛ يتلقى إشارة تدرج تقترب من الصفر ويتوقف عن التعلم تماماً.",
    option_c_en: "The GAN enters mode collapse, generating only one perfect face.",
    option_c_ar: "تدخل الـ GAN في 'انهيار النمط' (Mode Collapse)، لتوليد وجه مثالي واحد فقط.",
    option_d_en: "The Discriminator automatically resets its weights.",
    option_d_ar: "يقوم المُمیِّز بإعادة ضبط أوزانه تلقائياً.",
    correct_option: "B",
    explanation_en: "If the Discriminator is perfect, it outputs probabilities very close to 0 or 1. This causes the gradients passed back to the Generator to be virtually zero, preventing it from updating its weights.",
    explanation_ar: "إذا كان المُمیِّز مثالياً، فإنه يُخرج احتمالات قريبة جداً من 0 أو 1. هذا يتسبب في أن تكون التدرجات الممررة إلى المُولّد صفراً تقريباً، مما يمنعه من تحديث أوزانه (تلاشي التدرج)."
  },
  {
    id: "mb_b2_6",
    unit: "1",
    lesson: "les_1_3",
    type: "MCQ",
    source: "WEEKLY_ASSESSMENT",
    difficulty: "HARD",
    question_en: "An entire Smart Home ecosystem uses a central cloud server for all decisions. During an internet outage, the smart thermostat turns off heating in winter. What design paradigm should have been implemented to prevent this?",
    question_ar: "نظام منزل ذكي بالكامل يستخدم خادماً سحابياً مركزياً لجميع القرارات. أثناء انقطاع الإنترنت، قام جهاز تنظيم الحرارة بإيقاف التدفئة في الشتاء. ما هو نموذج التصميم الذي كان يجب تنفيذه لمنع ذلك؟",
    option_a_en: "Quantum Computing.",
    option_a_ar: "الحوسبة الكمية.",
    option_b_en: "Fog Computing or Edge AI, enabling the local hub to process rules offline.",
    option_b_ar: "حوسبة الضباب (Fog Computing) أو ذكاء الحافة، لتمكين الموزع المحلي من معالجة القواعد دون اتصال بالإنترنت.",
    option_c_en: "5G Cellular Backup.",
    option_c_ar: "نسخة احتياطية خلوية 5G.",
    option_d_en: "Deep Reinforcement Learning.",
    option_d_ar: "التعلم المعزز العميق.",
    correct_option: "B",
    explanation_en: "Edge AI brings computation to the local device or hub. This guarantees low latency, privacy, and continuous operation even when disconnected from the central cloud.",
    explanation_ar: "يجلب 'ذكاء الحافة' المعالجة إلى الجهاز المحلي أو الموزع. هذا يضمن انخفاض التأخير، والخصوصية، والتشغيل المستمر حتى عند انقطاع الاتصال بالسحابة المركزية."
  },
  {
    id: "mb_b2_7",
    unit: "1",
    lesson: "les_1_3",
    type: "WRITTEN",
    source: "HOMEWORK",
    difficulty: "HARD",
    question_en: "Explain how 'Federated Learning' can solve the massive privacy concerns of IoT smart health devices (like heart rate monitors) while still building a powerful global predictive AI model.",
    question_ar: "اشرح كيف يمكن لـ 'التعلم الموحد' (Federated Learning) حل مخاوف الخصوصية الهائلة لأجهزة الصحة الذكية (مثل أجهزة مراقبة ضربات القلب) مع الاستمرار في بناء نموذج ذكاء اصطناعي تنبؤي عالمي قوي.",
    ideal_answer_en: "In Federated Learning, the raw health data never leaves the user's local device. Instead, the global AI model is downloaded to the device, trained locally on the private data, and only the 'model updates' (weight changes) are sent back to the central server. These encrypted updates from millions of devices are aggregated to improve the global model without exposing any raw personal data.",
    ideal_answer_ar: "في التعلم الموحد، لا تغادر البيانات الصحية الخام جهاز المستخدم أبداً. بدلاً من ذلك، يتم تنزيل نموذج الذكاء الاصطناعي العالمي على الجهاز، ويتم تدريبه محلياً، ويتم إرسال 'تحديثات النموذج' (تغييرات الأوزان) فقط إلى الخادم المركزي. يتم دمج هذه التحديثات المشفرة من ملايين الأجهزة لتحسين النموذج العالمي دون كشف بيانات شخصية."
  },
  {
    id: "mb_b2_8",
    unit: "1",
    lesson: "les_1_4",
    type: "MCQ",
    source: "CLASSROOM",
    difficulty: "HARD",
    question_en: "A social media platform uses an AI algorithm to maximize 'user engagement time'. The algorithm discovers that promoting highly polarizing and enraging content keeps users online 30% longer. Ethically, this is an example of:",
    question_ar: "تستخدم منصة تواصل اجتماعي خوارزمية ذكاء اصطناعي لزيادة 'وقت تفاعل المستخدم' لأقصى حد. تكتشف الخوارزمية أن الترويج للمحتوى المثير للغضب والاستقطاب يبقي المستخدمين متصلين بنسبة 30٪ أطول. أخلاقياً، هذا مثال على:",
    option_a_en: "Value Misalignment (Optimization of a narrow metric at the expense of human well-being).",
    option_a_ar: "عدم توافق القيم (Value Misalignment) (تحسين مقياس ضيق على حساب رفاهية الإنسان).",
    option_b_en: "The Turing Test failure.",
    option_b_ar: "فشل اختبار تورينج.",
    option_c_en: "Algorithmic Hallucination.",
    option_c_ar: "الهلوسة الخوارزمية (Algorithmic Hallucination).",
    option_d_en: "Data Privacy Violation.",
    option_d_ar: "انتهاك خصوصية البيانات.",
    correct_option: "A",
    explanation_en: "The AI did exactly what it was programmed to do (maximize engagement time), but the programmers failed to align that goal with human values, leading to societal harm.",
    explanation_ar: "قام الذكاء الاصطناعي بالضبط بما بُرمج من أجله (زيادة وقت التفاعل)، لكن المبرمجين فشلوا في مواءمة هذا الهدف مع القيم الإنسانية، مما أدى إلى ضرر مجتمعي."
  },
  {
    id: "mb_b2_9",
    unit: "1",
    lesson: "les_1_4",
    type: "MCQ",
    source: "WEEKLY_ASSESSMENT",
    difficulty: "HARD",
    question_en: "Under the GDPR (General Data Protection Regulation), if a bank uses a fully automated AI system to deny a customer a loan, what specific legal right does the customer have?",
    question_ar: "بموجب اللائحة العامة لحماية البيانات (GDPR)، إذا استخدم أحد البنوك نظام ذكاء اصطناعي آلي بالكامل لرفض منح قرض لعميل، فما هو الحق القانوني المحدد الذي يتمتع به العميل؟",
    option_a_en: "The right to sue the developers of the AI framework (like TensorFlow or PyTorch).",
    option_a_ar: "الحق في مقاضاة مطوري إطار عمل الذكاء الاصطناعي (مثل TensorFlow أو PyTorch).",
    option_b_en: "The Right to an Explanation (and human intervention) regarding how the algorithm made the decision.",
    option_b_ar: "الحق في الحصول على تفسير (Right to an Explanation) والتدخل البشري بشأن كيفية اتخاذ الخوارزمية للقرار.",
    option_c_en: "The right to rewrite the algorithm's code.",
    option_c_ar: "الحق في إعادة كتابة كود الخوارزمية.",
    option_d_en: "No rights; algorithms are legally considered unbiased entities.",
    option_d_ar: "لا توجد حقوق؛ تعتبر الخوارزميات قانوناً كيانات غير متحيزة.",
    correct_option: "B",
    explanation_en: "GDPR Article 22 grants users the right not to be subject to a decision based solely on automated processing, allowing them to demand an explanation and human review.",
    explanation_ar: "تمنح المادة 22 من GDPR المستخدمين الحق في عدم الخضوع لقرار يعتمد فقط على المعالجة الآلية، مما يسمح لهم بالمطالبة بتفسير ومراجعة بشرية للقرار."
  },
  {
    id: "mb_b2_10",
    unit: "1",
    lesson: "les_1_1",
    type: "MCQ",
    source: "HOMEWORK",
    difficulty: "HARD",
    question_en: "In Deep Learning, what is the mathematical purpose of the 'Activation Function' (e.g., ReLU, Sigmoid)?",
    question_ar: "في التعلم العميق، ما هو الغرض الرياضي من 'دالة التنشيط' (مثل ReLU، Sigmoid)؟",
    option_a_en: "To calculate the final loss/error of the network.",
    option_a_ar: "لحساب الخسارة/الخطأ النهائي للشبكة.",
    option_b_en: "To introduce non-linearity into the network, allowing it to learn complex, non-linear patterns.",
    option_b_ar: "لإدخال عدم الخطية (Non-linearity) في الشبكة، مما يسمح لها بتعلم أنماط معقدة وغير خطية.",
    option_c_en: "To initialize the weights of the neurons before training.",
    option_c_ar: "لتهيئة أوزان الخلايا العصبية قبل التدريب.",
    option_d_en: "To compress the image size before it enters the CNN.",
    option_d_ar: "لضغط حجم الصورة قبل دخولها إلى الشبكة التلافيفية.",
    correct_option: "B",
    explanation_en: "Without activation functions, a deep neural network, no matter how many layers it has, would behave mathematically like a single-layer linear regression model.",
    explanation_ar: "بدون دوال التنشيط، فإن الشبكة العصبية العميقة، بغض النظر عن عدد طبقاتها، ستتصرف رياضياً مثل نموذج انحدار خطي بطبقة واحدة فقط، ولن تحل أي مشكلة معقدة."
  }
];
