import type { QuizQuestion } from './courseData';

export const MASSIVE_BANK_L1: QuizQuestion[] = [
  // ------------------- LESSON 1.1 (20 QUESTIONS) -------------------
  {
    id: "mb_l1_01", unit: "1", lesson: "les_1_1", type: "MCQ", source: "CLASSROOM", difficulty: "MEDIUM",
    question_en: "Which of the following best defines Machine Learning?",
    question_ar: "أي مما يلي يحدد تعلم الآلة (Machine Learning) بشكل أفضل؟",
    option_a_en: "A machine that only follows explicitly programmed instructions.",
    option_a_ar: "آلة تتبع التعليمات المبرمجة صراحةً فقط.",
    option_b_en: "A subset of AI that allows systems to learn and improve from experience without being explicitly programmed.",
    option_b_ar: "مجموعة فرعية من الذكاء الاصطناعي تسمح للأنظمة بالتعلم والتحسين من التجربة دون برمجة صريحة.",
    option_c_en: "A physical robot designed to perform manual labor.",
    option_c_ar: "روبوت مادي مصمم لأداء العمل اليدوي.",
    option_d_en: "The process of a computer building its own hardware.",
    option_d_ar: "عملية قيام الكمبيوتر ببناء أجهزته الخاصة.",
    correct_option: "B",
    explanation_en: "Machine Learning is focused on algorithms that learn from data, distinct from traditional rule-based programming.",
    explanation_ar: "يركز تعلم الآلة على الخوارزميات التي تتعلم من البيانات، بشكل منفصل عن البرمجة التقليدية القائمة على القواعد."
  },
  {
    id: "mb_l1_02", unit: "1", lesson: "les_1_1", type: "MCQ", source: "HOMEWORK", difficulty: "MEDIUM",
    question_en: "What is the primary difference between Supervised and Unsupervised learning?",
    question_ar: "ما هو الفرق الأساسي بين التعلم الخاضع للإشراف والتعلم غير الخاضع للإشراف؟",
    option_a_en: "Supervised learning uses labeled data; unsupervised uses unlabeled data.",
    option_a_ar: "يستخدم التعلم الخاضع للإشراف بيانات مصنفة؛ بينما يستخدم غير الخاضع للإشراف بيانات غير مصنفة.",
    option_b_en: "Supervised learning requires human robots.",
    option_b_ar: "يتطلب التعلم الخاضع للإشراف روبوتات بشرية.",
    option_c_en: "Unsupervised learning is only used for image recognition.",
    option_c_ar: "يستخدم التعلم غير الخاضع للإشراف فقط للتعرف على الصور.",
    option_d_en: "There is no difference.",
    option_d_ar: "لا يوجد فرق.",
    correct_option: "A",
    explanation_en: "Labeled data (knowing the correct answers during training) is the hallmark of supervised learning.",
    explanation_ar: "البيانات المصنفة (معرفة الإجابات الصحيحة أثناء التدريب) هي السمة المميزة للتعلم الخاضع للإشراف."
  },
  {
    id: "mb_l1_03", unit: "1", lesson: "les_1_1", type: "MCQ", source: "WEEKLY_ASSESSMENT", difficulty: "HARD",
    question_en: "In a medical context, why might an AI developer choose an interpretable Decision Tree over a highly accurate Deep Neural Network?",
    question_ar: "في السياق الطبي، لماذا قد يختار مطور الذكاء الاصطناعي 'شجرة قرار' قابلة للتفسير بدلاً من شبكة عصبية عميقة عالية الدقة؟",
    option_a_en: "Decision trees are always more accurate.",
    option_a_ar: "أشجار القرار دائماً أكثر دقة.",
    option_b_en: "Deep Neural Networks cannot be run on modern computers.",
    option_b_ar: "لا يمكن تشغيل الشبكات العصبية العميقة على أجهزة الكمبيوتر الحديثة.",
    option_c_en: "Doctors need to understand the 'why' behind a diagnosis (explainability), which a Black Box neural network cannot provide easily.",
    option_c_ar: "يحتاج الأطباء إلى فهم سبب التشخيص (قابلية التفسير)، وهو ما لا توفره الشبكة العصبية 'الصندوق الأسود' بسهولة.",
    option_d_en: "Decision Trees process images faster.",
    option_d_ar: "أشجار القرار تعالج الصور بشكل أسرع.",
    correct_option: "C",
    explanation_en: "Explainability is crucial in high-stakes fields like medicine to ensure trust and accountability.",
    explanation_ar: "قابلية التفسير أمر بالغ الأهمية في المجالات عالية المخاطر مثل الطب لضمان الثقة والمساءلة."
  },
  {
    id: "mb_l1_04", unit: "1", lesson: "les_1_1", type: "MCQ", source: "CLASSROOM", difficulty: "MEDIUM",
    question_en: "Which of the following is the best example of Reinforcement Learning?",
    question_ar: "أي مما يلي هو أفضل مثال على التعلم المعزز (Reinforcement Learning)؟",
    option_a_en: "Predicting house prices based on size.",
    option_a_ar: "التنبؤ بأسعار المنازل بناءً على المساحة.",
    option_b_en: "Grouping customers based on purchasing behavior.",
    option_b_ar: "تجميع العملاء بناءً على سلوك الشراء.",
    option_c_en: "An AI agent learning to play chess by being rewarded for winning and penalized for losing.",
    option_c_ar: "وكيل ذكاء اصطناعي يتعلم لعب الشطرنج من خلال مكافأته على الفوز ومعاقبته على الخسارة.",
    option_d_en: "Translating text from English to Arabic.",
    option_d_ar: "ترجمة النص من الإنجليزية إلى العربية.",
    correct_option: "C",
    explanation_en: "Reinforcement learning is based on taking actions in an environment to maximize a reward.",
    explanation_ar: "يعتمد التعلم المعزز على اتخاذ إجراءات في بيئة لزيادة المكافأة إلى أقصى حد."
  },
  {
    id: "mb_l1_05", unit: "1", lesson: "les_1_1", type: "WRITTEN", source: "HOMEWORK", difficulty: "HARD",
    question_en: "Describe the concept of 'Overfitting' and give a real-world example.",
    question_ar: "صف مفهوم 'فرط التخصيص' (Overfitting) وأعطِ مثالاً من العالم الحقيقي.",
    ideal_answer_en: "Overfitting happens when a model learns the training data too well, including its noise, but fails to generalize to new data. Example: A model predicting student grades memorizes past test answers perfectly but fails completely on a new, slightly different exam.",
    ideal_answer_ar: "يحدث فرط التخصيص عندما يتعلم النموذج بيانات التدريب بشكل مبالغ فيه (بما في ذلك الضوضاء)، لكنه يفشل في التعميم على بيانات جديدة. مثال: نموذج يتنبأ بدرجات الطلاب، يحفظ إجابات الاختبارات السابقة بشكل مثالي ولكنه يفشل تماماً في امتحان جديد مختلف قليلاً."
  },
  {
    id: "mb_l1_06", unit: "1", lesson: "les_1_1", type: "MCQ", source: "WEEKLY_ASSESSMENT", difficulty: "HARD",
    question_en: "What happens if you train an ML model on heavily imbalanced data (e.g., 99% healthy, 1% sick) without adjusting class weights?",
    question_ar: "ماذا يحدث إذا قمت بتدريب نموذج تعلم آلة على بيانات غير متوازنة بشدة (مثلاً 99% أصحاء، 1% مرضى) دون تعديل أوزان الفئات؟",
    option_a_en: "The model will become biased towards predicting the majority class to maximize raw accuracy.",
    option_a_ar: "سيصبح النموذج متحيزاً نحو التنبؤ بالفئة الأغلبية لتعظيم الدقة الخام.",
    option_b_en: "The model will perfectly learn both classes.",
    option_b_ar: "سيتعلم النموذج كلا الفئتين بشكل مثالي.",
    option_c_en: "The model will crash during training.",
    option_c_ar: "سينهار النموذج أثناء التدريب.",
    option_d_en: "It automatically balances itself.",
    option_d_ar: "يوازن نفسه تلقائياً.",
    correct_option: "A",
    explanation_en: "A naive model will just guess the majority class to easily score 99% accuracy, completely ignoring the minority class.",
    explanation_ar: "النموذج الساذج سيخمن فقط الفئة الأغلبية ليسجل دقة 99% بسهولة، متجاهلاً الفئة الأقلية تماماً."
  },
  {
    id: "mb_l1_07", unit: "1", lesson: "les_1_1", type: "MCQ", source: "CLASSROOM", difficulty: "MEDIUM",
    question_en: "What is 'Feature Extraction' in the context of Machine Learning?",
    question_ar: "ما هو 'استخراج الميزات' (Feature Extraction) في سياق تعلم الآلة؟",
    option_a_en: "Downloading data from the internet.",
    option_a_ar: "تنزيل البيانات من الإنترنت.",
    option_b_en: "The process of transforming raw data into meaningful inputs that the algorithm can understand.",
    option_b_ar: "عملية تحويل البيانات الخام إلى مدخلات ذات مغزى يمكن للخوارزمية فهمها.",
    option_c_en: "Extracting the final results from the model.",
    option_c_ar: "استخراج النتائج النهائية من النموذج.",
    option_d_en: "A type of deep learning network.",
    option_d_ar: "نوع من شبكات التعلم العميق.",
    correct_option: "B",
    explanation_en: "Feature extraction involves selecting or transforming variables (like converting an image into a matrix of pixel values) so the ML model can process it.",
    explanation_ar: "يتضمن استخراج الميزات تحديد أو تحويل المتغيرات (مثل تحويل صورة إلى مصفوفة من قيم البكسل) حتى يتمكن النموذج من معالجتها."
  },
  {
    id: "mb_l1_08", unit: "1", lesson: "les_1_1", type: "MCQ", source: "HOMEWORK", difficulty: "HARD",
    question_en: "Which evaluation metric is MOST appropriate when the cost of a 'False Negative' is extremely high (e.g., failing to detect a bomb)?",
    question_ar: "أي مقياس تقييم هو الأنسب عندما تكون تكلفة 'السلبية الخاطئة' (False Negative) عالية جداً (مثل الفشل في اكتشاف قنبلة)؟",
    option_a_en: "Precision (الدقة المحددة)",
    option_a_ar: "الدقة (Precision)",
    option_b_en: "Recall (Sensitivity / الاستدعاء)",
    option_b_ar: "الاستدعاء (Recall)",
    option_c_en: "Accuracy (الدقة العامة)",
    option_c_ar: "الدقة الكلية (Accuracy)",
    option_d_en: "F1-Score",
    option_d_ar: "مقياس F1",
    correct_option: "B",
    explanation_en: "Recall measures how many of the actual positive cases we caught. High recall ensures we don't miss the bombs (minimize false negatives), even if we get some false alarms (low precision).",
    explanation_ar: "يقيس الاستدعاء عدد الحالات الإيجابية الفعلية التي اكتشفناها. الاستدعاء العالي يضمن عدم تفويت القنابل (تقليل السلبيات الخاطئة)، حتى لو حصلنا على إنذارات كاذبة (انخفاض الدقة المحددة)."
  },
  {
    id: "mb_l1_09", unit: "1", lesson: "les_1_1", type: "WRITTEN", source: "WEEKLY_ASSESSMENT", difficulty: "MEDIUM",
    question_en: "Briefly explain how Deep Learning differs from traditional Machine Learning in terms of feature engineering.",
    question_ar: "اشرح باختصار كيف يختلف 'التعلم العميق' عن 'تعلم الآلة' التقليدي فيما يتعلق بهندسة الميزات (Feature Engineering).",
    ideal_answer_en: "In traditional ML, a human expert must manually perform feature extraction. In Deep Learning, the neural network automatically extracts its own features directly from raw data (like pixels) across its hidden layers.",
    ideal_answer_ar: "في تعلم الآلة التقليدي، يجب على الخبير البشري استخراج الميزات يدوياً. في التعلم العميق، تقوم الشبكة العصبية تلقائياً باستخراج الميزات الخاصة بها مباشرة من البيانات الخام عبر طبقاتها المخفية."
  },
  {
    id: "mb_l1_10", unit: "1", lesson: "les_1_1", type: "MCQ", source: "CLASSROOM", difficulty: "MEDIUM",
    question_en: "Which algorithm is commonly used for Unsupervised Learning (Clustering)?",
    question_ar: "أي خوارزمية تُستخدم بشكل شائع للتعلم غير الخاضع للإشراف (التجميع - Clustering)؟",
    option_a_en: "Linear Regression",
    option_a_ar: "الانحدار الخطي (Linear Regression)",
    option_b_en: "Support Vector Machines (SVM)",
    option_b_ar: "آلات المتجهات الداعمة (SVM)",
    option_c_en: "K-Means",
    option_c_ar: "خوارزمية K-Means",
    option_d_en: "Random Forest",
    option_d_ar: "الغابة العشوائية (Random Forest)",
    correct_option: "C",
    explanation_en: "K-Means groups unlabeled data into 'K' distinct clusters based on similarity.",
    explanation_ar: "تجمع خوارزمية K-Means البيانات غير المصنفة في مجموعات 'K' متميزة بناءً على التشابه."
  },
  {
    id: "mb_l1_11", unit: "1", lesson: "les_1_1", type: "MCQ", source: "HOMEWORK", difficulty: "HARD",
    question_en: "You notice your neural network's loss function decreases on training data but drastically increases on validation data over epochs. What is happening?",
    question_ar: "تلاحظ أن دالة الخسارة للشبكة العصبية تنخفض في بيانات التدريب ولكنها ترتفع بشكل كبير في بيانات التحقق عبر الـ Epochs. ماذا يحدث؟",
    option_a_en: "Underfitting",
    option_a_ar: "نقص التخصيص (Underfitting)",
    option_b_en: "Overfitting",
    option_b_ar: "فرط التخصيص (Overfitting)",
    option_c_en: "Perfect Convergence",
    option_c_ar: "تقارب مثالي",
    option_d_en: "Data Leakage",
    option_d_ar: "تسرب البيانات",
    correct_option: "B",
    explanation_en: "When training error goes down but validation error goes up, the model is memorizing the training set and failing to generalize (overfitting).",
    explanation_ar: "عندما ينخفض خطأ التدريب ولكن يرتفع خطأ التحقق، فإن النموذج يحفظ مجموعة التدريب ويفشل في التعميم (فرط التخصيص)."
  },
  {
    id: "mb_l1_12", unit: "1", lesson: "les_1_1", type: "MCQ", source: "WEEKLY_ASSESSMENT", difficulty: "MEDIUM",
    question_en: "What is a 'Dataset' in the context of AI?",
    question_ar: "ما هي 'مجموعة البيانات' (Dataset) في سياق الذكاء الاصطناعي؟",
    option_a_en: "A piece of code that runs the AI.",
    option_a_ar: "قطعة من الكود لتشغيل الذكاء الاصطناعي.",
    option_b_en: "A collection of related data used to train, test, or validate an ML model.",
    option_b_ar: "مجموعة من البيانات ذات الصلة تُستخدم لتدريب أو اختبار أو التحقق من نموذج تعلم الآلة.",
    option_c_en: "The final output of the AI.",
    option_c_ar: "المخرجات النهائية للذكاء الاصطناعي.",
    option_d_en: "A hardware component for storing memory.",
    option_d_ar: "مكون مادي لتخزين الذاكرة.",
    correct_option: "B",
    explanation_en: "A dataset is the foundation of any ML model, acting as the 'experience' from which it learns.",
    explanation_ar: "مجموعة البيانات هي أساس أي نموذج ML، وتعمل كـ 'التجربة' التي يتعلم منها."
  },
  {
    id: "mb_l1_13", unit: "1", lesson: "les_1_1", type: "WRITTEN", source: "CLASSROOM", difficulty: "HARD",
    question_en: "Why do we typically split a dataset into Training, Validation, and Testing sets instead of just Training and Testing?",
    question_ar: "لماذا نقوم عادةً بتقسيم مجموعة البيانات إلى مجموعات (تدريب، وتحقق، واختبار) بدلاً من (تدريب واختبار) فقط؟",
    ideal_answer_en: "The Validation set is used to tune the model's hyperparameters during training (preventing overfitting). The Testing set is kept completely unseen until the very end to provide an unbiased evaluation of the final model's real-world performance.",
    ideal_answer_ar: "تُستخدم مجموعة التحقق لضبط المعلمات الفائقة (Hyperparameters) للنموذج أثناء التدريب. يتم إبقاء مجموعة الاختبار مخفية تماماً حتى النهاية لتوفير تقييم غير متحيز لأداء النموذج النهائي في العالم الحقيقي."
  },
  {
    id: "mb_l1_14", unit: "1", lesson: "les_1_1", type: "MCQ", source: "HOMEWORK", difficulty: "MEDIUM",
    question_en: "What type of learning is used by Netflix to recommend movies based on what similar users watched?",
    question_ar: "ما نوع التعلم الذي تستخدمه نتفليكس (Netflix) للتوصية بالأفلام بناءً على ما شاهده المستخدمون المشابهون؟",
    option_a_en: "Supervised Classification",
    option_a_ar: "تصنيف خاضع للإشراف",
    option_b_en: "Unsupervised Clustering / Recommender Systems",
    option_b_ar: "تجميع غير خاضع للإشراف / أنظمة التوصية",
    option_c_en: "Reinforcement Learning",
    option_c_ar: "تعلم معزز",
    option_d_en: "Natural Language Processing",
    option_d_ar: "معالجة اللغات الطبيعية",
    correct_option: "B",
    explanation_en: "Recommender systems often use unsupervised techniques (like collaborative filtering) to find hidden patterns and similarities among users.",
    explanation_ar: "تستخدم أنظمة التوصية غالباً تقنيات غير خاضعة للإشراف (مثل التصفية التعاونية) للعثور على أنماط وأوجه تشابه خفية بين المستخدمين."
  },
  {
    id: "mb_l1_15", unit: "1", lesson: "les_1_1", type: "MCQ", source: "WEEKLY_ASSESSMENT", difficulty: "HARD",
    question_en: "In a Neural Network, what is the role of an 'Epoch'?",
    question_ar: "في الشبكة العصبية، ما هو دور 'الحقبة' (Epoch)؟",
    option_a_en: "It represents a single neuron's calculation.",
    option_a_ar: "يمثل عملية حسابية لخلية عصبية واحدة.",
    option_b_en: "It is one complete forward and backward pass of ALL training examples through the network.",
    option_b_ar: "يمثل دورة كاملة للأمام والخلف لجميع أمثلة التدريب عبر الشبكة.",
    option_c_en: "It defines the learning rate.",
    option_c_ar: "يحدد معدل التعلم.",
    option_d_en: "It is the final layer of the network.",
    option_d_ar: "هو الطبقة النهائية للشبكة.",
    correct_option: "B",
    explanation_en: "An epoch means the model has seen the entire dataset once. Training usually requires many epochs.",
    explanation_ar: "يعني الـ Epoch أن النموذج قد رأى مجموعة البيانات بأكملها مرة واحدة. عادة ما يتطلب التدريب العديد من الـ Epochs."
  },
  {
    id: "mb_l1_16", unit: "1", lesson: "les_1_1", type: "MCQ", source: "CLASSROOM", difficulty: "MEDIUM",
    question_en: "Which of the following is NOT a typical application of Artificial Intelligence?",
    question_ar: "أي مما يلي لا يعتبر تطبيقاً نموذجياً للذكاء الاصطناعي؟",
    option_a_en: "Self-driving cars",
    option_a_ar: "السيارات ذاتية القيادة",
    option_b_en: "Voice assistants like Siri",
    option_b_ar: "المساعدات الصوتية مثل سيري",
    option_c_en: "A standard mechanical clock",
    option_c_ar: "ساعة ميكانيكية عادية",
    option_d_en: "Email spam filters",
    option_d_ar: "عوامل تصفية البريد العشوائي (Spam)",
    correct_option: "C",
    explanation_en: "A mechanical clock relies entirely on physical gears, not data or algorithms.",
    explanation_ar: "تعتمد الساعة الميكانيكية كلياً على التروس المادية، وليس البيانات أو الخوارزميات."
  },
  {
    id: "mb_l1_17", unit: "1", lesson: "les_1_1", type: "WRITTEN", source: "HOMEWORK", difficulty: "HARD",
    question_en: "Explain the 'Bias-Variance Tradeoff' in simple terms.",
    question_ar: "اشرح 'مفاضلة الانحياز والتباين' (Bias-Variance Tradeoff) بعبارات بسيطة.",
    ideal_answer_en: "It's the balance between a model being too simple (High Bias/Underfitting) and a model being too complex and memorizing noise (High Variance/Overfitting). The goal is to find the sweet spot where the model is complex enough to capture patterns but general enough to handle new data.",
    ideal_answer_ar: "إنه التوازن بين أن يكون النموذج بسيطاً جداً (انحياز عالي / نقص تخصيص) وأن يكون معقداً جداً ويحفظ الضوضاء (تباين عالي / فرط تخصيص). الهدف هو إيجاد النقطة المثالية حيث يكون النموذج معقداً بما يكفي لالتقاط الأنماط ولكنه عام بما يكفي للتعامل مع البيانات الجديدة."
  },
  {
    id: "mb_l1_18", unit: "1", lesson: "les_1_1", type: "MCQ", source: "WEEKLY_ASSESSMENT", difficulty: "HARD",
    question_en: "What is 'Gradient Descent'?",
    question_ar: "ما هو 'انحدار التدرج' (Gradient Descent)؟",
    option_a_en: "An optimization algorithm used to minimize the loss function by iteratively moving towards the steepest descent.",
    option_a_ar: "خوارزمية تحسين تُستخدم لتقليل دالة الخسارة عن طريق التحرك التكراري نحو الانحدار الأكثر حدة.",
    option_b_en: "A method to increase the number of layers in a neural network.",
    option_b_ar: "طريقة لزيادة عدد الطبقات في شبكة عصبية.",
    option_c_en: "A technique used to clean corrupted datasets.",
    option_c_ar: "تقنية تستخدم لتنظيف مجموعات البيانات الفاسدة.",
    option_d_en: "A metric that measures model accuracy.",
    option_d_ar: "مقياس يقيس دقة النموذج.",
    correct_option: "A",
    explanation_en: "Gradient descent is how neural networks learn: by tweaking weights step-by-step in the direction that reduces the error (loss).",
    explanation_ar: "انحدار التدرج هو كيفية تعلم الشبكات العصبية: عن طريق تعديل الأوزان خطوة بخطوة في الاتجاه الذي يقلل من الخطأ (الخسارة)."
  },
  {
    id: "mb_l1_19", unit: "1", lesson: "les_1_1", type: "MCQ", source: "CLASSROOM", difficulty: "MEDIUM",
    question_en: "Which type of algorithm would you use to predict the exact temperature for tomorrow?",
    question_ar: "ما نوع الخوارزمية التي ستستخدمها للتنبؤ بدرجة الحرارة الدقيقة للغد؟",
    option_a_en: "Classification",
    option_a_ar: "التصنيف (Classification)",
    option_b_en: "Regression",
    option_b_ar: "الانحدار (Regression)",
    option_c_en: "Clustering",
    option_c_ar: "التجميع (Clustering)",
    option_d_en: "Reinforcement Learning",
    option_d_ar: "التعلم المعزز",
    correct_option: "B",
    explanation_en: "Regression predicts a continuous numerical value (like temperature), while classification predicts discrete categories (like 'Hot' or 'Cold').",
    explanation_ar: "يتنبأ الانحدار بقيمة رقمية مستمرة (مثل درجة الحرارة)، بينما يتنبأ التصنيف بفئات منفصلة (مثل 'حار' أو 'بارد')."
  },
  {
    id: "mb_l1_20", unit: "1", lesson: "les_1_1", type: "MCQ", source: "HOMEWORK", difficulty: "HARD",
    question_en: "Why is 'Data Normalization' (or Scaling) important before training a neural network?",
    question_ar: "لماذا تعد 'تسوية البيانات' (Data Normalization / Scaling) مهمة قبل تدريب الشبكة العصبية؟",
    option_a_en: "It converts text data to images.",
    option_a_ar: "تقوم بتحويل البيانات النصية إلى صور.",
    option_b_en: "It ensures all numerical features are on a similar scale (e.g., 0 to 1), preventing large values from dominating the gradient descent process.",
    option_b_ar: "يضمن أن جميع الميزات الرقمية على مقياس مشابه (مثلاً 0 إلى 1)، مما يمنع القيم الكبيرة من السيطرة على عملية انحدار التدرج.",
    option_c_en: "It encrypts the data for privacy.",
    option_c_ar: "تقوم بتشفير البيانات من أجل الخصوصية.",
    option_d_en: "It reduces the size of the dataset.",
    option_d_ar: "تقلل من حجم مجموعة البيانات.",
    correct_option: "B",
    explanation_en: "If one feature is in thousands (like Salary) and another is a fraction (like Age ratio), the model struggles to balance weights. Scaling stabilizes learning.",
    explanation_ar: "إذا كانت إحدى الميزات بالآلاف والأخرى كسرية، فإن النموذج يعاني لموازنة الأوزان. التسوية (Scaling) تعمل على استقرار التعلم."
  }
];
