import type { QuizQuestion } from './courseData';

export const OFFICIAL_ASSESSMENTS_L3: QuizQuestion[] = [
  // ==================== PERIOD 1: CLASSROOM TASKS (مهام أدائية - الفترة الأولى) ====================
  {
    id: "off_l3_c1_w1",
    lesson: "1-3",
    unit: "1",
    type: "WRITTEN",
    source: "CLASSROOM",
    difficulty: "MEDIUM",
    question_ar: "اشرح كيف أصبحت تقنيات مثل منصات الفيديو والمساعدات الصوتية جزءاً من الخدمات اليومية، وما هو الدور الأساسي للذكاء الاصطناعي فيها؟",
    question_en: "Explain how technologies such as video platforms and voice assistants have become part of daily services, and what is the primary role of AI in them?",
    ideal_answer_ar: "أصبحت منصات الفيديو (مثل يوتيوب) والمساعدات الصوتية (مثل سيري ومساعد جوجل) خدمات يومية لا غنى عنها؛ حيث يقوم الذكاء الاصطناعي في منصات الفيديو بتحليل سلوك وتفضيلات المستخدمين السابقة لتقديم توصيات شخصية مخصصة، بينما يقوم في المساعدات الصوتية بمعالجة اللغة الطبيعية والتعرف على الصوت لفهم الأوامر وتنفيذ المهام التلقائية وتقديم الإجابات الفورية.",
    ideal_answer_en: "Video platforms (like YouTube) and voice assistants (like Siri and Google Assistant) have become integral to daily life. AI powers video platforms by analyzing past user behaviors and preferences to deliver personalized recommendations, while in voice assistants it utilizes Natural Language Processing (NLP) and speech recognition to understand voice commands and execute tasks instantly.",
    explanation_ar: "يركز السؤال على دور الذكاء الاصطناعي في تحليل السلوك والتوصيات في الفيديو، ومعالجة الصوت واللغة في المساعدات الذكية.",
    explanation_en: "Focuses on AI's role in behavior analysis and recommendation systems for video platforms, and voice recognition and NLP for voice assistants."
  },
  {
    id: "off_l3_c1_w2",
    lesson: "1-3",
    unit: "1",
    type: "WRITTEN",
    source: "CLASSROOM",
    difficulty: "MEDIUM",
    question_ar: "وضح المقصود بـ «الذكاء الاصطناعي للتشخيص بالصور» في مجال الرعاية الصحية، وكيف يسهم في الكشف عن الأمراض؟",
    question_en: "Clarify what is meant by 'AI for Image Diagnosis' in healthcare, and how it contributes to disease detection?",
    ideal_answer_ar: "يقصد به استخدام خوارزميات التعلم العميق ورؤية الحاسوب لتحليل الصور الطبية مثل صور الأشعة السينية (X-rays) والرنين المغناطيسي (MRI) والتصوير المقطعي (CT scan). ويسهم في الكشف المبكر والدقيق عن الأورام والأمراض المختلفة بدقة تضاهي أو تعزز قدرات الأطباء البشريين وتقلل احتمالية الخطأ.",
    ideal_answer_en: "It refers to using computer vision and deep learning algorithms to examine and analyze medical images such as X-rays, MRIs, and CT scans. It contributes to early, highly accurate detection of tumors and diseases, augmenting doctors' diagnostic capabilities and minimizing diagnostic errors.",
    explanation_ar: "الذكاء الاصطناعي يدعم الأطباء في رصد الآفات والأورام الدقيقة من خلال فحص آلاف الصور الطبية بدقة وسرعة.",
    explanation_en: "AI aids physicians in detecting lesions and abnormalities across medical scans quickly and accurately."
  },
  {
    id: "off_l3_c1_m1",
    lesson: "1-3",
    unit: "1",
    type: "MCQ",
    source: "CLASSROOM",
    difficulty: "EASY",
    question_ar: "أي من الخيارات التالية يُعد مثاالً على نظام يتنبأ بالتفضيلات من بيانات السلوك السابق ويعرض التوصيات؟",
    question_en: "Which of the following is an example of a system that predicts preferences from past behavioral data and displays recommendations?",
    option_a_ar: "نظام التوصية",
    option_a_en: "Recommendation System",
    option_b_ar: "المساعد الصوتي",
    option_b_en: "Voice Assistant",
    option_c_ar: "الترجمة الآلية",
    option_c_en: "Machine Translation",
    option_d_ar: "التعرف على الوجه",
    option_d_en: "Facial Recognition",
    correct_option: "A",
    explanation_ar: "نظام التوصية هو الذي يحلل سجل المشاهدة والشراء للتنبؤ بالمواد التي يفضلها المستخدم.",
    explanation_en: "A Recommendation System analyzes historical behavioral data to suggest relevant content or products."
  },
  {
    id: "off_l3_c1_m2",
    lesson: "1-3",
    unit: "1",
    type: "MCQ",
    source: "CLASSROOM",
    difficulty: "EASY",
    question_ar: "ما هي الخدمة التي تقوم بترجمة النص تلقائياً إلى لغات مختلفة كما ورد في خدمات الذكاء الاصطناعي اليومية؟",
    question_en: "Which service automatically translates text into different languages as mentioned in daily AI services?",
    option_a_ar: "نظام التوصية",
    option_a_en: "Recommendation System",
    option_b_ar: "المساعد الصوتي",
    option_b_en: "Voice Assistant",
    option_c_ar: "الترجمة الآلية",
    option_c_en: "Machine Translation",
    option_d_ar: "التعرف على الوجه",
    option_d_en: "Facial Recognition",
    correct_option: "C",
    explanation_ar: "الترجمة الآلية (Machine Translation) مثل Google Translate و DeepL هي الخدمة المتخصصة في نقل النصوص بدقة بين اللغات المختلفة.",
    explanation_en: "Machine Translation automatically translates text across languages using neural language models."
  },

  // ==================== PERIOD 1: HOMEWORK (أداءات منزلية - الفترة الأولى) ====================
  {
    id: "off_l3_h1_w1",
    lesson: "1-3",
    unit: "1",
    type: "WRITTEN",
    source: "HOMEWORK",
    difficulty: "MEDIUM",
    question_ar: "اذكر أربع خدمات أساسية للذكاء الاصطناعي في الحياة اليومية مع بيان دور الذكاء الاصطناعي في كل خدمة؟",
    question_en: "Mention four fundamental AI services in daily life, explaining the role of AI in each service?",
    ideal_answer_ar: "1. نظم التوصية (يوتيوب/أمازون): تحليل السلوك والتفضيلات لترشيح الفيديوهات والمنتجات.\n2. المساعدات الصوتية (Siri/Google Assistant): التعرف على الصوت وفهم اللغة الطبيعية لتنفيذ الأوامر.\n3. التعرف على الوجه (Face Unlock): تحليل الملامح لفتح الهواتف والتأكد من الهوية.\n4. الترجمة الآلية: استخدام معالجة اللغة الطبيعية للترجمة الفورية الدقيقة بين اللغات.",
    ideal_answer_en: "1. Recommendation Systems (YouTube/Amazon): Analyzing user behavior to suggest products and videos.\n2. Voice Assistants (Siri/Google Assistant): Speech recognition and NLP to execute commands.\n3. Facial Recognition (Phone unlock): Biometric landmark analysis for security and identification.\n4. Machine Translation: Neural NLP models converting texts accurately across languages.",
    explanation_ar: "الخدمات اليومية الأربعة الأساسية المعتمدة على الذكاء الاصطناعي كما وردت في كتاب الوزارة.",
    explanation_en: "The four primary daily AI applications highlighted in the official curriculum."
  },
  {
    id: "off_l3_h1_w2",
    lesson: "1-3",
    unit: "1",
    type: "WRITTEN",
    source: "HOMEWORK",
    difficulty: "MEDIUM",
    question_ar: "ما هو الدور الذي يلعبه الذكاء الاصطناعي في قطاع التصنيع؟ اذكر مثالين توضيحيين.",
    question_en: "What role does AI play in the manufacturing sector? Give two illustrative examples.",
    ideal_answer_ar: "يلعب الذكاء الاصطناعي دوراً محورياً في أتمتة ورفع كفاءة الإنتاج وتقليل التكاليف. من أبرز الأمثلة:\n1. فحص جودة المنتج: استخدام كاميرات الرؤية الحاسوبية لفحص المنتجات على خط الإنتاج ورصد العيوب الدقيقة آلياً.\n2. الصيانة التنبؤية (Predictive Maintenance): تحليل بيانات المستشعرات في الآلات للتنبؤ بالأعطال قبل حدوثها وإجراء الصيانة الاستباقية لتجنب توقف المصنع.",
    ideal_answer_en: "AI plays a vital role in automating production lines, boosting efficiency, and cutting costs. Examples:\n1. Automated Quality Inspection: Computer vision cameras detecting manufacturing defects instantly on assembly lines.\n2. Predictive Maintenance: Analyzing machine sensor telemetry to forecast failures before they occur and servicing equipment proactively.",
    explanation_ar: "التصنيع يعتمد على الذكاء الاصطناعي بشكل رئيسي في فحص الجودة والصيانة التنبؤية.",
    explanation_en: "Manufacturing relies heavily on AI for automated defect inspection and predictive maintenance."
  },
  {
    id: "off_l3_h1_m1",
    lesson: "1-3",
    unit: "1",
    type: "MCQ",
    source: "HOMEWORK",
    difficulty: "EASY",
    question_ar: "ما هو المصطلح الذي يشير إلى نظام الذكاء الاصطناعي الذي يتعرف على الصوت، وفهم الأوامر، وتنفيذها مثل (Siri) ومساعد جوجل؟",
    question_en: "What term refers to the AI system that recognizes voice, understands commands, and executes them like Siri and Google Assistant?",
    option_a_ar: "نظام التوصية",
    option_a_en: "Recommendation System",
    option_b_ar: "المساعد الصوتي",
    option_b_en: "Voice Assistant",
    option_c_ar: "الترجمة الآلية",
    option_c_en: "Machine Translation",
    option_d_ar: "التعرف على الوجه",
    option_d_en: "Facial Recognition",
    correct_option: "B",
    explanation_ar: "المساعد الصوتي (Voice Assistant) هو النظام المصمم للتفاعل الصوتي المباشر وتنفيذ طلبات المستخدم.",
    explanation_en: "A voice assistant is designed for auditory user interaction, processing verbal commands."
  },
  {
    id: "off_l3_h1_m2",
    lesson: "1-3",
    unit: "1",
    type: "MCQ",
    source: "HOMEWORK",
    difficulty: "EASY",
    question_ar: "أي من القطاعات الصناعية التالية ترتبط بمهمة «تحسين مسارات التوصيل»؟",
    question_en: "Which of the following industrial sectors is linked to the task of 'optimizing delivery routes'?",
    option_a_ar: "الرعاية الصحية",
    option_a_en: "Healthcare",
    option_b_ar: "الزراعة",
    option_b_en: "Agriculture",
    option_c_ar: "التصنيع",
    option_c_en: "Manufacturing",
    option_d_ar: "الخدمات اللوجستية",
    option_d_en: "Logistics",
    correct_option: "D",
    explanation_ar: "قطاع الخدمات اللوجستية والشحن والنقل هو المعني بتحسين مسارات أساطيل التوصيل وتوفير الوقود والوقت.",
    explanation_en: "Logistics focuses on route optimization, fleet scheduling, and delivery efficiency."
  },

  // ==================== PERIOD 2: CLASSROOM TASKS (مهام أدائية - الفترة الثانية) ====================
  {
    id: "off_l3_c2_w1",
    lesson: "1-3",
    unit: "1",
    type: "WRITTEN",
    source: "CLASSROOM",
    difficulty: "MEDIUM",
    question_ar: "وضح كيف يتم استخدام الذكاء الاصطناعي في قطاع الزراعة ودوره في مراقبة المحاصيل والآفات.",
    question_en: "Explain how AI is used in the agricultural sector and its role in monitoring crops and pests.",
    ideal_answer_ar: "يُستخدم الذكاء الاصطناعي في الزراعة الذكية عبر تحليل صور الأقمار الصناعية والطائرات بدون طيار (الدرونز) لتقييم صحة النباتات، والتنبؤ بموعد الحصاد المناسب، والكشف المبكر عن الآفات الزراعية وأمراض التربة لتوجيه رش المبيدات بدقة وترشيد استهلاك المياه والأسمدة.",
    ideal_answer_en: "AI is utilized in smart farming by processing satellite and drone imagery to evaluate crop health, forecast harvest timing, detect pests and diseases early, and optimize targeted pesticide spraying and irrigation.",
    explanation_ar: "الزراعة الذكية تعتمد على رؤية الحاسوب والاستشعار عن بعد لمراقبة نمو المحاصيل ومكافحة الآفات.",
    explanation_en: "Smart agriculture uses computer vision and remote sensing to monitor crop growth and control pests."
  },
  {
    id: "off_l3_c2_w2",
    lesson: "1-3",
    unit: "1",
    type: "WRITTEN",
    source: "CLASSROOM",
    difficulty: "MEDIUM",
    question_ar: "اذكر أربعة مهام يمكن أن يؤديها الذكاء الاصطناعي في معالجة البيانات المعقدة والتعرف على الصور والأصوات.",
    question_en: "Mention four tasks that AI can perform in processing complex data and recognizing images and sounds.",
    ideal_answer_ar: "1. تصنيف الصور واكتشاف الأجسام (مثل فحص الصور الطبية، والتعرف على الوجوه).\n2. معالجة وتوليد الكلام واللغات الطبيعية (المساعدات الصوتية، الترجمة الفورية).\n3. استخراج الأنماط والتنبؤ الإحصائي (مثل التنبؤ بأعطال الآلات في المصانع، والتنبؤ بالطقس).\n4. أنظمة الملاحة الذكية والتوجيه الآلي (تحديد مسارات المركبات الذاتية وتفادي العوائق).",
    ideal_answer_en: "1. Image classification and object detection (medical imaging, facial recognition).\n2. Natural Language Processing and speech synthesis (voice assistants, translation).\n3. Pattern extraction and predictive analytics (machine failure forecasting, weather prediction).\n4. Autonomous navigation and motion planning (pathfinding and obstacle avoidance).",
    explanation_ar: "إبراز قدرات الذكاء الاصطناعي المتعددة في الرؤية، واللغة، والتنبؤ، والتحكم الذكي.",
    explanation_en: "Highlights AI's versatile competencies across vision, language, forecasting, and autonomous control."
  },
  {
    id: "off_l3_c2_m1",
    lesson: "1-3",
    unit: "1",
    type: "MCQ",
    source: "CLASSROOM",
    difficulty: "EASY",
    question_ar: "ما هي الصناعة التي تستخدم الذكاء الاصطناعي للكشف عن الأمراض من صور الأشعة السينية والتصوير المقطعي؟",
    question_en: "Which industry uses AI to detect diseases from X-ray and CT scan images?",
    option_a_ar: "الرعاية الصحية",
    option_a_en: "Healthcare",
    option_b_ar: "الزراعة",
    option_b_en: "Agriculture",
    option_c_ar: "التصنيع",
    option_c_en: "Manufacturing",
    option_d_ar: "الخدمات اللوجستية",
    option_d_en: "Logistics",
    correct_option: "A",
    explanation_ar: "الرعاية الصحية تستخدم خوارزميات التشخيص بالصور لتحليل الأشعة والتصوير المقطعي.",
    explanation_en: "Healthcare utilizes diagnostic computer vision for radiography and scan evaluations."
  },
  {
    id: "off_l3_c2_m2",
    lesson: "1-3",
    unit: "1",
    type: "MCQ",
    source: "CLASSROOM",
    difficulty: "EASY",
    question_ar: "أي من الخيارات الآتية يمثل المهمة الرئيسية للذكاء الاصطناعي في قطاع الزراعة؟",
    question_en: "Which of the following represents the main task of AI in the agricultural sector?",
    option_a_ar: "تحسين مسارات التوصيل",
    option_a_en: "Optimizing delivery routes",
    option_b_ar: "التنبؤ بموعد الحصاد والكشف عن الآفات والأمراض",
    option_b_en: "Predicting harvest time and detecting pests and diseases",
    option_c_ar: "فحص جودة المنتج والصيانة التنبؤية",
    option_c_en: "Product quality inspection and predictive maintenance",
    option_d_ar: "تحليل الصور الطبية واكتشاف الأدوية",
    option_d_en: "Medical image analysis and drug discovery",
    correct_option: "B",
    explanation_ar: "في قطاع الزراعة، يساعد الذكاء الاصطناعي في التنبؤ بموعد الحصاد والكشف عن الآفات والأمراض في المحاصيل.",
    explanation_en: "In agriculture, AI's primary tasks include yield forecasting and automated pest/disease detection."
  },

  // ==================== PERIOD 2: HOMEWORK (أداءات منزلية - الفترة الثانية) ====================
  {
    id: "off_l3_h2_w1",
    lesson: "1-3",
    unit: "1",
    type: "WRITTEN",
    source: "HOMEWORK",
    difficulty: "HARD",
    question_ar: "اشرح مقولة «الذكاء الاصطناعي بارع في إيجاد الأنماط في البيانات، لكن الحكم البشري لا يزال ضرورياً».",
    question_en: "Explain the statement: 'AI excels at finding patterns in data, but human judgment remains essential.'",
    ideal_answer_ar: "الذكاء الاصطناعي يتميز بقدرة حسابية فائقة على معالجة ملايين السجلات واستخراج الأنماط الخفية والاستدلال الاحتمالي بسرعة. ومع ذلك، يفتقر الذكاء الاصطناعي إلى الفهم الأخلاقي، والوعي بالسياق الإنساني، والحس السليم (Common Sense). لذلك فإن القرارات المصيرية (كالقرارات الطبية والقضائية والقرارات التي تمس الحقوق) تتطلب حتماً إشرافاً وحكماً بشرياً لضمان العدالة وتحديد المسؤولية.",
    ideal_answer_en: "AI possesses superhuman computational prowess in parsing massive datasets, finding latent correlations, and probabilistic inference. However, it lacks moral reasoning, contextual common sense, and real-world empathy. Therefore, critical high-stakes decisions (e.g. medical triage, judicial verdicts, civil rights) fundamentally require human oversight to maintain accountability and fairness.",
    explanation_ar: "التمييز بين كفاءة الذكاء الاصطناعي الرياضية التحليلية وبين ضرورة الحكمة والضمير البشري.",
    explanation_en: "Distinguishes between AI computational efficiency and indispensable human wisdom and ethics."
  },
  {
    id: "off_l3_h2_w2",
    lesson: "1-3",
    unit: "1",
    type: "WRITTEN",
    source: "HOMEWORK",
    difficulty: "MEDIUM",
    question_ar: "اذكر ثلاثة احتياطات للاستخدام المتعلقة بالذكاء الاصطناعي.",
    question_en: "Mention three precautions for using AI.",
    ideal_answer_ar: "1. الحذر من ظاهرة الهلوسة (Hallucination) والتحقق دوماً من دقة المعلومات الناتجة.\n2. الانتباه لمشكلة الصندوق الأسود وصعوبة تفسير كيفية الوصول للقرارات.\n3. مراعاة الخصوصية وحماية البيانات الشخصية وحقوق الملكية الفكرية المستخدمة في تدريب النماذج.",
    ideal_answer_en: "1. Guarding against hallucinations and fact-checking generated outputs.\n2. Being aware of the black-box problem where model decision pathways are opaque.\n3. Protecting data privacy, safeguarding personal details, and respecting intellectual property in training datasets.",
    explanation_ar: "احتياطات الاستخدام: الهلوسة، الصندوق الأسود، الخصوصية وحقوق التأليف.",
    explanation_en: "Core precautions: Hallucination mitigation, black-box opacity awareness, and privacy/copyright governance."
  },
  {
    id: "off_l3_h2_m1",
    lesson: "1-3",
    unit: "1",
    type: "MCQ",
    source: "HOMEWORK",
    difficulty: "EASY",
    question_ar: "ما هو المصطلح الذي يصف توليد معلومات غير صحيحة أو غير مدعومة تبدو مقنعة من قبل الذكاء الاصطناعي؟",
    question_en: "What term describes the generation of incorrect or unsupported information that sounds plausible by an AI?",
    option_a_ar: "مشكلة الصندوق الأسود",
    option_a_en: "Black Box Problem",
    option_b_ar: "الهلوسة",
    option_b_en: "Hallucination",
    option_c_ar: "التمييز أو التحيز",
    option_c_en: "Discrimination / Bias",
    option_d_ar: "بيانات التدريب غير الكافية",
    option_d_en: "Insufficient Training Data",
    correct_option: "B",
    explanation_ar: "الهلوسة (Hallucination) هي ظاهرة توليد نصوص أو إجابات غير حقيقية ولكنها مصاغة بثقة تبدو مقنعة للمستخدم.",
    explanation_en: "Hallucination refers to generative AI generating factually untrue or fabricated responses with persuasive tone."
  },
  {
    id: "off_l3_h2_m2",
    lesson: "1-3",
    unit: "1",
    type: "MCQ",
    source: "HOMEWORK",
    difficulty: "MEDIUM",
    question_ar: "ماذا يقصد بمشكلة «الصندوق الأسود» في سياق تطبيقات الذكاء الاصطناعي؟",
    question_en: "What is meant by the 'Black Box Problem' in the context of AI applications?",
    option_a_ar: "توليد معلومات غير صحيحة تبدو مقنعة للمستخدم",
    option_a_en: "Generating incorrect information that appears convincing to the user",
    option_b_ar: "عدم الوضوح حول كيفية توصل الذكاء الاصطناعي إلى حكمه أو قراره",
    option_b_en: "Lack of clarity about how the AI reached its judgment or decision",
    option_c_ar: "استخدام أعمال محمية بحقوق المؤلف كبيانات تدريب",
    option_c_en: "Using copyrighted works as training data",
    option_d_ar: "نقص بيانات التدريب أو عدم تمثيلها للواقع بدقة",
    option_d_en: "Lack of training data or failure to represent reality accurately",
    correct_option: "B",
    explanation_ar: "مشكلة الصندوق الأسود تعني أن الشبكة العصبية المعقدة تتخذ قرارات دون أن يتمكن المطور أو المستخدم من معرفة الآلية الدقيقة للقرار.",
    explanation_en: "The Black Box problem arises when internal weights and computations are opaque to human interpretation."
  },

  // ==================== WEEKLY ASSESSMENT: MODEL A (التقييمات الأسبوعية - النموذج A) ====================
  {
    id: "off_l3_wka_w1",
    lesson: "1-3",
    unit: "1",
    type: "WRITTEN",
    source: "WEEKLY_ASSESSMENT",
    difficulty: "MEDIUM",
    question_ar: "اشرح كيفية استخدام أنظمة التوصية في الحياة اليومية مع ذكر أمثلة تطبيقية مثل يوتيوب وأمازون؟",
    question_en: "Explain how recommendation systems are used in daily life, providing practical examples such as YouTube and Amazon?",
    ideal_answer_ar: "تعتمد أنظمة التوصية على تحليل السلوك الرقمي للمستخدم (تاريخ المشاهدة، والبحث، والتقييمات، والمشتريات السابقة) ومقارنتها بسلوك مستخدمين آخرين لتخمين اهتماماته. في يوتيوب، تقترح المنصة مقاطع فيديو إضافية تبقي المستخدم متفاعلاً، وفي أمازون، تقترح منتجات مكملة أو بديلة اشتراها أشخاص لديهم نفس الاهتمام، مما يسهل الوصول للمعلومات ويزيد من فعالية التجارة.",
    ideal_answer_en: "Recommendation systems track behavioral digital breadcrumbs (view histories, searches, purchases) and filter them against collaborative patterns. YouTube surfaces personalized video queues to maximize engagement, while Amazon offers related merchandise that users with analogous preferences bought, streamlining discovery.",
    explanation_ar: "شرح آلية عمل نظم التوصية ودورها في منصات المحتوى والتجارة الإلكترونية.",
    explanation_en: "Mechanisms of recommendation algorithms across media streaming and e-commerce platforms."
  },
  {
    id: "off_l3_wka_w2",
    lesson: "1-3",
    unit: "1",
    type: "WRITTEN",
    source: "WEEKLY_ASSESSMENT",
    difficulty: "MEDIUM",
    question_ar: "اذكر استخدامات الذكاء الاصطناعي في الرعاية الصحية؟",
    question_en: "Mention the uses of AI in healthcare?",
    ideal_answer_ar: "1. التشخيص الدقيق للصور الطبية (الأشعة السينية، الرنين المغناطيسي، المقطعي) لرصد الأورام مبكراً.\n2. تسريع اكتشاف الأدوية وتصميم الجزيئات العلاجية.\n3. مراقبة المؤشرات الحيوية للمرضى والتنبؤ بالتدهور الصحي المفاجئ.\n4. السجلات الطبية الذكية والمساعدة في تنظيم الإجراءات السريرية.",
    ideal_answer_en: "1. Diagnostic medical imaging for early tumor detection across X-rays, MRIs, and CT scans.\n2. Accelerated drug discovery and molecular simulation.\n3. Real-time patient vital sign monitoring and early warning systems.\n4. Automated clinical documentation and administrative optimization.",
    explanation_ar: "تطبيقات الذكاء الاصطناعي في الطب: تحليل الصور، اكتشاف الأدوية، المراقبة.",
    explanation_en: "Medical AI applications: Image analysis, pharmaceutical discovery, vital monitoring."
  },
  {
    id: "off_l3_wka_w3",
    lesson: "1-3",
    unit: "1",
    type: "WRITTEN",
    source: "WEEKLY_ASSESSMENT",
    difficulty: "HARD",
    question_ar: "اذكر أربعة قطاعات صناعية رئيسية يتم فيها إدخال تقنيات الذكاء الاصطناعي مع بيان دور كل قطاع باختصار؟",
    question_en: "Mention four major industrial sectors where AI technologies are adopted, briefly stating the role in each sector?",
    ideal_answer_ar: "1. قطاع التصنيع: فحص جودة المنتجات على خطوط الإنتاج بالرؤية الحاسوبية والصيانة التنبؤية للآلات.\n2. قطاع الرعاية الصحية: تشخيص الأمراض من الصور الطبية وتطوير الأدوية وتخصيص العلاج.\n3. قطاع الزراعة: التنبؤ بمواعيد الحصاد والكشف عن الآفات ومراقبة رطوبة التربة عبر الطائرات بدون طيار.\n4. قطاع الخدمات اللوجستية: تحسين وتخطيط مسارات الشحن والتوصيل وإدارة المستودعات الذكية.",
    ideal_answer_en: "1. Manufacturing: Automated defect detection and predictive machinery maintenance.\n2. Healthcare: Medical image diagnostics, drug design, and patient monitoring.\n3. Agriculture: Crop yield prediction, pest detection, and precision irrigation via drones.\n4. Logistics: Route optimization for delivery fleets and automated warehouse management.",
    explanation_ar: "القطاعات الأربعة المقررة في المنهج: التصنيع، الرعاية الصحية، الزراعة، الخدمات اللوجستية.",
    explanation_en: "The four core sectors in the curriculum: Manufacturing, Healthcare, Agriculture, and Logistics."
  },
  {
    id: "off_l3_wka_w4",
    lesson: "1-3",
    unit: "1",
    type: "WRITTEN",
    source: "WEEKLY_ASSESSMENT",
    difficulty: "HARD",
    question_ar: "اشرح ما يبرع فيه الذكاء الاصطناعي وما يتطلب الحذر عند استخدامه فيما يتعلق بالقرارات ذات البعد الأخلاقي والخصوصية؟",
    question_en: "Explain what AI excels at and what requires caution when used regarding ethical decisions and privacy?",
    ideal_answer_ar: "ما يبرع فيه الذكاء الاصطناعي: معالجة كميات هائلة من البيانات، والتعرف فائق السرعة على الأنماط والتصنيف، والاستدلال الاحتمالي الدقيق في البيئات الرقمية.\nما يتطلب الحذر الشديد: اتخاذ القرارات الأخلاقية، ومخاطر التحيز والتمييز ضد فئات معينة، وتتبع وسرقة البيانات الشخصية للمستخدمين، وتوليد معلومات مضللة، وغياب المحاسبة؛ حيث يتطلب البعد الأخلاقي إدراكاً إنسانياً وتحديداً قانونياً للمسؤولية لا تملكه الآلة.",
    ideal_answer_en: "What AI excels at: Processing massive data arrays, high-speed pattern recognition, classification, and statistical probability inference.\nWhat requires caution: Making moral choices, mitigating algorithmic bias, preventing intrusive surveillance and privacy breaches, combating misinformation, and establishing liability; ethics mandates human judgment and legal accountability beyond machine capabilities.",
    explanation_ar: "المقارنة بين الكفاءة الرياضية للذكاء الاصطناعي والحذر الواجب في الجوانب الأخلاقية والإنسانية.",
    explanation_en: "Contrasting mathematical computational aptitude with ethical, privacy, and accountability perils."
  },
  {
    id: "off_l3_wka_m1",
    lesson: "1-3",
    unit: "1",
    type: "MCQ",
    source: "WEEKLY_ASSESSMENT",
    difficulty: "EASY",
    question_ar: "أي من الخدمات التالية تُستخدم لفتح الهاتف الذكي والكشف عن وجوه الأشخاص في الصور والتعرف عليها تلقائياً؟",
    question_en: "Which of the following services is used to unlock smartphones and automatically detect and recognize faces in photos?",
    option_a_ar: "نظام التوصية",
    option_a_en: "Recommendation System",
    option_b_ar: "المساعد الصوتي",
    option_b_en: "Voice Assistant",
    option_c_ar: "الترجمة الآلية",
    option_c_en: "Machine Translation",
    option_d_ar: "التعرف على الوجه",
    option_d_en: "Facial Recognition",
    correct_option: "D",
    explanation_ar: "تقنية التعرف على الوجه (Facial Recognition) تعتمد على رؤية الحاسوب لتمييز ملامح المستخدمين بدقة.",
    explanation_en: "Facial recognition utilizes computer vision to identify facial landmarks for biometrics."
  },
  {
    id: "off_l3_wka_m2",
    lesson: "1-3",
    unit: "1",
    type: "MCQ",
    source: "WEEKLY_ASSESSMENT",
    difficulty: "MEDIUM",
    question_ar: "ما هي التقنية المستخدمة في فحص جودة المنتج والتنبؤ بأعطال الآلات قبل وقوعها؟",
    question_en: "What technology is used for inspecting product quality and predicting machine breakdowns before they happen?",
    option_a_ar: "الذكاء الاصطناعي للتشخيص بالصور",
    option_a_en: "AI for image diagnosis",
    option_b_ar: "الذكاء الاصطناعي في التصنيع والصيانة التنبؤية",
    option_b_en: "AI in manufacturing and predictive maintenance",
    option_c_ar: "نظم التوصية والمساعد الصوتي",
    option_c_en: "Recommendation systems and voice assistants",
    option_d_ar: "الترجمة الآلية وشبكات التواصل",
    option_d_en: "Machine translation and social networks",
    correct_option: "B",
    explanation_ar: "الصيانة التنبؤية وفحص الجودة الآلي هما الاستخدامان الرئيسيان للذكاء الاصطناعي في قطاع التصنيع.",
    explanation_en: "Predictive maintenance and automated QA are the hallmark AI manufacturing deployments."
  },
  {
    id: "off_l3_wka_m3",
    lesson: "1-3",
    unit: "1",
    type: "MCQ",
    source: "WEEKLY_ASSESSMENT",
    difficulty: "EASY",
    question_ar: "من ضمن احتياطات الاستخدام للذكاء الاصطناعي، ماذا تعني ظاهرة «الهلوسة»؟",
    question_en: "Among the precautions of using AI, what does the phenomenon of 'Hallucination' mean?",
    option_a_ar: "عدم معرفة كيف توصل النظام لقراره",
    option_a_en: "Not knowing how the system reached its decision",
    option_b_ar: "توليد معلومات غير صحيحة أو غير مدعومة تبدو مقنعة",
    option_b_en: "Generating incorrect or unsupported information that sounds plausible",
    option_c_ar: "وجود تحيز في بيانات التدريب",
    option_c_en: "Presence of bias in training data",
    option_d_ar: "انتهاك حقوق المؤلف للبيانات",
    option_d_en: "Infringement of data copyright",
    correct_option: "B",
    explanation_ar: "الهلوسة تعني اختلاق معلومات غير حقيقية أو استشهادات وهمية تبدو ظاهرياً صحيحة ومقنعة.",
    explanation_en: "Hallucination is generating fabricated or false assertions packaged convincingly."
  },
  {
    id: "off_l3_wka_m4",
    lesson: "1-3",
    unit: "1",
    type: "MCQ",
    source: "WEEKLY_ASSESSMENT",
    difficulty: "MEDIUM",
    question_ar: "أي من الآتي يُعد الوصف الصحيح لما يبرع فيه الذكاء الاصطناعي؟",
    question_en: "Which of the following is the correct description of what AI excels at?",
    option_a_ar: "إيجاد وتصنيف الأنماط في البيانات المعقدة والاستدلال الاحتمالي",
    option_a_en: "Finding and classifying patterns in complex data and probabilistic inference",
    option_b_ar: "اتخاذ الأحكام الأخلاقية المطلقة بدون بشر",
    option_b_en: "Making absolute moral judgments without humans",
    option_c_ar: "ضمان خلو المخرجات تماماً من أي تحيز مستقبلي",
    option_c_en: "Guaranteeing outputs are completely free of future bias",
    option_d_ar: "حفظ البيانات الشخصية وحمايتها بسرية تامة",
    option_d_en: "Preserving personal data and guarding it with total confidentiality",
    correct_option: "A",
    explanation_ar: "يبرع الذكاء الاصطناعي في معالجة الأنماط المعقدة وحساب الاحتمالات الرياضية بسرعة فائقة.",
    explanation_en: "AI's distinct edge is discovering multi-dimensional patterns and mathematical probability modeling."
  },

  // ==================== WEEKLY ASSESSMENT: MODEL B (النموذج B) ====================
  {
    id: "off_l3_wkb_w1",
    lesson: "1-3",
    unit: "1",
    type: "WRITTEN",
    source: "WEEKLY_ASSESSMENT",
    difficulty: "EASY",
    question_ar: "اذكر دور الذكاء الاصطناعي في المساعدات الصوتية مع ذكر مثالين.",
    question_en: "Mention the role of AI in voice assistants, providing two examples.",
    ideal_answer_ar: "دور الذكاء الاصطناعي يتمثل في تحويل الموجات الصوتية إلى نصوص وفهم المعنى الدلالي للأوامر (معالجة اللغة الطبيعية NLP)، وتوليد الكلام المنطوق للرد وتنفيذ المهام التلقائية.\nأمثلة:\n1. مساعد آبل سيري (Siri).\n2. مساعد جوجل (Google Assistant).",
    ideal_answer_en: "AI transcribes acoustic waveforms into textual tokens, deciphers intent through NLP, executes programmatic tasks, and generates synthesized speech responses.\nExamples:\n1. Apple Siri.\n2. Google Assistant.",
    explanation_ar: "المساعدات الصوتية تجمع بين التعرف على الكلام ومعالجة اللغة الطبيعية وتوليف الصوت.",
    explanation_en: "Voice assistants bridge acoustic recognition, intent decoding, and synthesized audio."
  },
  {
    id: "off_l3_wkb_w2",
    lesson: "1-3",
    unit: "1",
    type: "WRITTEN",
    source: "WEEKLY_ASSESSMENT",
    difficulty: "MEDIUM",
    question_ar: "ناقش دور الذكاء الاصطناعي في قطاعي الزراعة والخدمات اللوجستية في تحسين العمليات والإنتاجية؟",
    question_en: "Discuss the role of AI in the agriculture and logistics sectors in improving operations and productivity?",
    ideal_answer_ar: "في قطاع الزراعة: تحليل صور المحاصيل للتنبؤ بالحصاد ورصد الآفات والأمراض وتوجيه الري الذكي، مما يزيد المحصول ويوفر الموارد.\nفي قطاع الخدمات اللوجستية: حساب المسارات المثلى لشاحنات التوصيل بالاعتماد على حركة المرور اللحظية، وتوزيع الشحنات وإدارة المستودعات آلياً، مما يقلل استهلاك الوقود ويختصر زمن التوصيل.",
    ideal_answer_en: "In Agriculture: Aerial drone image parsing forecasts yields, isolates crop pathogens, and drives targeted irrigation to maximize harvest efficiency.\nIn Logistics: Real-time traffic pathfinding algorithms calculate optimum delivery routes, automate inventory dispatch, and drastically curtail fuel emissions and transit durations.",
    explanation_ar: "تحسين العمليات والإنتاجية في الزراعة واللوجستيات عبر الأتمتة والتحليل اللحظي.",
    explanation_en: "Operational optimization across precision agriculture and dynamic logistics pathfinding."
  },
  {
    id: "off_l3_wkb_w3",
    lesson: "1-3",
    unit: "1",
    type: "WRITTEN",
    source: "WEEKLY_ASSESSMENT",
    difficulty: "HARD",
    question_ar: "وضح باختصار احتياطات الاستخدام المرتبطة ببيانات التدريب المتحيزة والقرارات عالية الأثر وتحديد المسؤولية؟",
    question_en: "Briefly explain usage precautions regarding biased training data, high-impact decisions, and assigning accountability?",
    ideal_answer_ar: "1. بيانات التدريب المتحيزة: إذا كانت بيانات التدريب تحتوي على تمييز تاريخي أو نقص تمثيل، فإن النموذج سيعيد إنتاج هذا التمييز ضد فئات معينة.\n2. القرارات عالية الأثر: القرارات التي تؤثر على حياة البشر (مثل التشخيص الطبي، القبول الجامعي، التوظيف) لا يجب تركها للذكاء الاصطناعي منفرداً.\n3. تحديد المسؤولية: يجب تحديد من يتحمل الخطأ (المطور، الشركة المشغلة، المستخدم) لضمان المساءلة القانونية والأخلاقية.",
    ideal_answer_en: "1. Biased Training Data: Skewed historical records cause models to institutionalize prejudice against specific demographics.\n2. High-Impact Decisions: Critical determinations (healthcare triage, hiring, judicial sentences) must never operate without human verification.\n3. Liability & Accountability: Explicit frameworks must govern whether the developer, operator, or end-user assumes responsibility when faults occur.",
    explanation_ar: "احتياطات المسؤولية والتحيز في القرارات الحساسة.",
    explanation_en: "Ethical boundaries concerning algorithmic discrimination and high-stakes accountability."
  },
  {
    id: "off_l3_wkb_w4",
    lesson: "1-3",
    unit: "1",
    type: "WRITTEN",
    source: "WEEKLY_ASSESSMENT",
    difficulty: "MEDIUM",
    question_ar: "اشرح سبب ضرورة وجود تأكيد من طبيب بشري للتشخيص الطبي بدلاً من الاعتماد على الذكاء الاصطناعي وحده؟",
    question_en: "Explain why human physician confirmation is necessary for medical diagnoses rather than relying solely on AI?",
    ideal_answer_ar: "لأن الذكاء الاصطناعي نظام احتمالي قد يتعرض للهلوسة أو يخطئ في تشخيص الحالات النادرة غير الممثلة في بيانات التدريب (مشكلة الصندوق الأسود). كما أن الطبيب البشري يمتلك القدرة على تقييم الحالة السريرية الشاملة للمريض، والتواصل الإنساني، وتحمل المسؤولية القانونية والأخلاقية عن سلامة المريض.",
    ideal_answer_en: "Because AI operates on statistical probability and can suffer from hallucinations, edge-case failures, or black-box errors. A human doctor synthesizes holistic clinical history, empathy, and bodily examination, while bearing direct ethical and legal malpractice responsibility.",
    explanation_ar: "المسؤولية القانونية والتقييم السريري الشامل يفرضان الإشراف الطبي البشري.",
    explanation_en: "Legal liability, comprehensive holistic care, and empathy necessitate human clinical oversight."
  },
  {
    id: "off_l3_wkb_m1",
    lesson: "1-3",
    unit: "1",
    type: "MCQ",
    source: "WEEKLY_ASSESSMENT",
    difficulty: "EASY",
    question_ar: "خدمة يومية تستخدم لفهم الكلام وتنفيذ الأوامر الصوتية مثل Siri ومساعد جوجل هي:",
    question_en: "A daily service used to understand speech and execute voice commands like Siri and Google Assistant is:",
    option_a_ar: "نظام التوصية",
    option_a_en: "Recommendation System",
    option_b_ar: "المساعد الصوتي",
    option_b_en: "Voice Assistant",
    option_c_ar: "الترجمة الآلية",
    option_c_en: "Machine Translation",
    option_d_ar: "التعرف على الوجه",
    option_d_en: "Facial Recognition",
    correct_option: "B",
    explanation_ar: "المساعد الصوتي هو النظام الذي يتعامل مع الكلام والأوامر الصوتية.",
    explanation_en: "Voice assistants specialize in voice interaction and spoken commands."
  },
  {
    id: "off_l3_wkb_m2",
    lesson: "1-3",
    unit: "1",
    type: "MCQ",
    source: "WEEKLY_ASSESSMENT",
    difficulty: "EASY",
    question_ar: "قطاع صناعي يستخدم الذكاء الاصطناعي لتحسين مسارات التوصيل هو:",
    question_en: "An industrial sector using AI to optimize delivery routes is:",
    option_a_ar: "الرعاية الصحية",
    option_a_en: "Healthcare",
    option_b_ar: "الزراعة",
    option_b_en: "Agriculture",
    option_c_ar: "التصنيع",
    option_c_en: "Manufacturing",
    option_d_ar: "الخدمات اللوجستية",
    option_d_en: "Logistics",
    correct_option: "D",
    explanation_ar: "الخدمات اللوجستية تختص بالنقل والتوزيع وتخطيط المسارات.",
    explanation_en: "Logistics encompasses route optimization and delivery fleet coordination."
  },
  {
    id: "off_l3_wkb_m3",
    lesson: "1-3",
    unit: "1",
    type: "MCQ",
    source: "WEEKLY_ASSESSMENT",
    difficulty: "MEDIUM",
    question_ar: "ما هو المصطلح الذي يعبر عن عدم وضوح كيفية توصل الذكاء الاصطناعي إلى حكمه أو قراره؟",
    question_en: "What term denotes the lack of clarity on how AI reaches its judgment or decision?",
    option_a_ar: "الهلوسة",
    option_a_en: "Hallucination",
    option_b_ar: "مشكلة الصندوق الأسود",
    option_b_en: "Black Box Problem",
    option_c_ar: "التمييز أو التحيز",
    option_c_en: "Discrimination or Bias",
    option_d_ar: "الاستدلال الاحتمالي",
    option_d_en: "Probabilistic Inference",
    correct_option: "B",
    explanation_ar: "مشكلة الصندوق الأسود (Black Box) تعبر عن غموض المسار الاستنتاجي للشبكات العصبية العميقة.",
    explanation_en: "The black box problem represents the opacity of deep neural activations during inference."
  },
  {
    id: "off_l3_wkb_m4",
    lesson: "1-3",
    unit: "1",
    type: "MCQ",
    source: "WEEKLY_ASSESSMENT",
    difficulty: "MEDIUM",
    question_ar: "من ضمن المهام التي يجيدها الذكاء الاصطناعي:",
    question_en: "Among the tasks that AI excels at:",
    option_a_ar: "اتخاذ القرارات الأخلاقية المعقدة",
    option_a_en: "Making complex ethical decisions",
    option_b_ar: "التعرف على الصور والأصوات والنصوص وتوليد المحتوى",
    option_b_en: "Recognizing images, sounds, text, and generating content",
    option_c_ar: "ضمان دقة النتائج المطلقة دون بيانات تدريب",
    option_c_en: "Guaranteeing absolute precision without training data",
    option_d_ar: "حماية الخصوصية الشخصية تلقائياً",
    option_d_en: "Protecting personal privacy automatically",
    correct_option: "B",
    explanation_ar: "يجيد الذكاء الاصطناعي معالجة وتوليد الوسائط المتعددة (صور، نصوص، أصوات).",
    explanation_en: "AI is exceptionally capable of multimodal perceptual pattern matching and content synthesis."
  },

  // ==================== WEEKLY ASSESSMENT: MODEL C (النموذج C) ====================
  {
    id: "off_l3_wkc_w1",
    lesson: "1-3",
    unit: "1",
    type: "WRITTEN",
    source: "WEEKLY_ASSESSMENT",
    difficulty: "EASY",
    question_ar: "اشرح ثلاث خدمات يمكن أن يؤديها الذكاء الاصطناعي في الحياة اليومية.",
    question_en: "Explain three services that AI can perform in daily life.",
    ideal_answer_ar: "1. المساعدات الصوتية الذكية: تنظيم المواعيد، وضبط المنبهات، والإجابة عن الأسئلة بالأوامر الصوتية.\n2. أنظمة التوصية: اقتراح الموسيقى والأفلام والمنتجات التي تناسب الذوق الشخصي.\n3. تقنيات التعرف على الوجه: حماية الهواتف وتسهيل عمليات تسجيل الدخول والدفع الرقمي.",
    ideal_answer_en: "1. Voice Assistants: Hands-free task management, alarms, and conversational search.\n2. Recommendation Engines: Curating tailored music, video, and e-commerce shopping suggestions.\n3. Facial Recognition: Securing biometric device unlocking and mobile transaction authorization.",
    explanation_ar: "تطبيقات يومية شائعة للذكاء الاصطناعي في حياة المستخدم اليومية.",
    explanation_en: "Everyday consumer AI touchpoints in contemporary life."
  },
  {
    id: "off_l3_wkc_w2",
    lesson: "1-3",
    unit: "1",
    type: "WRITTEN",
    source: "WEEKLY_ASSESSMENT",
    difficulty: "MEDIUM",
    question_ar: "اذكر مثالين لإسهام الذكاء الاصطناعي في قطاع التصنيع.",
    question_en: "Mention two examples of AI contributions to the manufacturing sector.",
    ideal_answer_ar: "1. مراقبة جودة الإنتاج: رصد العيوب والتشققات الدقيقة في المنتجات المصنوعة بسرعة تفوق العين البشرية.\n2. الصيانة التنبؤية: الاستماع للاهتزازات ودرجات حرارة التوربينات والمحركات للتنبؤ بموعد العطل واستبدال القطع قبل توقف المصنع.",
    ideal_answer_en: "1. Quality Control Inspection: High-speed computer vision detecting microscopic fissures on assembly lines.\n2. Predictive Maintenance: Vibration and thermal telemetry analysis anticipating motor fatigue before breakdowns.",
    explanation_ar: "إسهام الذكاء الاصطناعي في جودة التصنيع وتقليل التوقف غير المخطط له.",
    explanation_en: "AI's industrial value in zero-defect quality control and uptime maximization."
  },
  {
    id: "off_l3_wkc_w3",
    lesson: "1-3",
    unit: "1",
    type: "WRITTEN",
    source: "WEEKLY_ASSESSMENT",
    difficulty: "HARD",
    question_ar: "وضح الأبعاد المتعلقة بمشكلة الصندوق الأسود وقضايا الحقوق عند استخدام أعمال محمية بحقوق المؤلف كبيانات تدريب؟",
    question_en: "Explain the dimensions concerning the black box problem and copyright issues when using protected works as training data?",
    ideal_answer_ar: "1. مشكلة الصندوق الأسود: تجعل من الصعب تتبع أسباب خطأ الذكاء الاصطناعي أو تبرير قراراته للمستخدمين والسلطات الرقابية.\n2. حقوق الملكية الفكرية: تدريب النماذج التوليدية على نصوص وصور وفنون لفنانين ومؤلفين دون إذن أو تعويض يثير نزاعات قانونية حول انتهاك حقوق المؤلف وما إذا كانت المخرجات تعد سرقة أدبية أم اقتباساً عادلاً.",
    ideal_answer_en: "1. Black Box Dimension: The opacity prevents users, engineers, and regulators from understanding decision rationale or proving lack of bias.\n2. Intellectual Property Dimension: Scraped creative works trained into generative models without consent or attribution spur legal disputes over copyright infringement versus fair use.",
    explanation_ar: "الصندوق الأسود يعيق الشفافية، وتدريب النماذج يثير معضلات قانونية حول حقوق الملكية الفكرية.",
    explanation_en: "Black-box architectures impair auditability, while web-scraping IP triggers copyright contention."
  },
  {
    id: "off_l3_wkc_w4",
    lesson: "1-3",
    unit: "1",
    type: "WRITTEN",
    source: "WEEKLY_ASSESSMENT",
    difficulty: "HARD",
    question_ar: "وضح الفروق الجوهرية بين ما يبرع فيه الذكاء الاصطناعي من إيجاد الأنماط وبين الجوانب التي تتطلب الحذر الشديد مثل الخصوصية والأخلاق؟",
    question_en: "Clarify the essential differences between what AI excels at (pattern detection) and areas demanding acute caution like privacy and ethics?",
    ideal_answer_ar: "يبرع الذكاء الاصطناعي في الاستقراء الرياضي، واكتشاف الأنماط المعقدة ضمن ملايين البيانات، ومضاهاة التفضيلات بدقة متناهية. ولكن في المقابل، فإن الخصوصية والأخلاق تتطلبان فهماً للحقوق الفردية، وحساسية تجاه الكرامة الإنسانية، وتطبيقاً لمبادئ العدالة التي تتجاوز مجرد الحسابات الرقمية. والذكاء الاصطناعي يفتقر للضمير ولا يمكنه موازنة القيم الأخلاقية عند تعارضها دون توجيه بشري صارم.",
    ideal_answer_en: "AI is unparalleled at statistical pattern mining and multi-parameter optimization. However, human privacy and ethics require moral consciousness, contextual wisdom, and value-based judgments that cannot be distilled purely into loss-function mathematics. AI has no consciousness or moral agency.",
    explanation_ar: "الذكاء الاصطناعي أداة حسابية قوية تفتقر إلى الضمير الأخلاقي والوعي الحقوقي.",
    explanation_en: "AI is a statistical computation tool devoid of moral conscience and legal understanding."
  },
  {
    id: "off_l3_wkc_m1",
    lesson: "1-3",
    unit: "1",
    type: "MCQ",
    source: "WEEKLY_ASSESSMENT",
    difficulty: "EASY",
    question_ar: "نظام يتنبأ بالتفضيلات من بيانات السلوك السابق ويعرض التوصيات في منصات مثل يوتيوب وأمازون يسمى:",
    question_en: "A system that predicts preferences from past behavioral data and shows recommendations on platforms like YouTube and Amazon is called:",
    option_a_ar: "نظام التوصية",
    option_a_en: "Recommendation System",
    option_b_ar: "المساعد الصوتي",
    option_b_en: "Voice Assistant",
    option_c_ar: "الترجمة الآلية",
    option_c_en: "Machine Translation",
    option_d_ar: "التعرف على الوجه",
    option_d_en: "Facial Recognition",
    correct_option: "A",
    explanation_ar: "نظام التوصية يدرس سلوك المستخدم السابق لتوقع اهتماماته المستقبلية.",
    explanation_en: "A recommendation engine models historical preferences to suggest future items."
  },
  {
    id: "off_l3_wkc_m2",
    lesson: "1-3",
    unit: "1",
    type: "MCQ",
    source: "WEEKLY_ASSESSMENT",
    difficulty: "EASY",
    question_ar: "أي من الصناعات التالية تستخدم الذكاء الاصطناعي للتنبؤ بموعد الحصاد والكشف عن الآفات والأمراض؟",
    question_en: "Which of the following industries uses AI to predict harvest timing and detect pests and diseases?",
    option_a_ar: "الرعاية الصحية",
    option_a_en: "Healthcare",
    option_b_ar: "الزراعة",
    option_b_en: "Agriculture",
    option_c_ar: "التصنيع",
    option_c_en: "Manufacturing",
    option_d_ar: "الخدمات اللوجستية",
    option_d_en: "Logistics",
    correct_option: "B",
    explanation_ar: "الزراعة تستخدم الذكاء الاصطناعي لمراقبة الحصاد ومكافحة الآفات.",
    explanation_en: "Agriculture uses AI for crop harvest forecasting and pest surveillance."
  },
  {
    id: "off_l3_wkc_m3",
    lesson: "1-3",
    unit: "1",
    type: "MCQ",
    source: "WEEKLY_ASSESSMENT",
    difficulty: "MEDIUM",
    question_ar: "القرارات ذات البعد الأخلاقي التي قد تؤدي إلى تمييز أو تحيز تُعد ضمن:",
    question_en: "Decisions with an ethical dimension that may lead to discrimination or bias are categorized under:",
    option_a_ar: "ما يبرع فيه الذكاء الاصطناعي",
    option_a_en: "What AI excels at",
    option_b_ar: "ما يتطلب الحذر عند استخدام الذكاء الاصطناعي",
    option_b_en: "What requires caution when using AI",
    option_c_ar: "المهارات الأساسية للتعلم العميق",
    option_c_en: "Basic skills of deep learning",
    option_d_ar: "دور أنظمة التوصية اليومية",
    option_d_en: "The role of daily recommendation systems",
    correct_option: "B",
    explanation_ar: "القرارات الأخلاقية والتحيز تندرج تحت الاحتياطات والجوانب التي تتطلب حذراً ورقابة بشرية مستمرة.",
    explanation_en: "Ethical bias risks fall under mandatory cautionary governance in AI deployment."
  },
  {
    id: "off_l3_wkc_m4",
    lesson: "1-3",
    unit: "1",
    type: "MCQ",
    source: "WEEKLY_ASSESSMENT",
    difficulty: "EASY",
    question_ar: "يُعرف التحيز في أنظمة الذكاء الاصطناعي على أنه:",
    question_en: "Bias in AI systems is defined as:",
    option_a_ar: "نمط قد يؤدي إلى نتائج غير عادلة",
    option_a_en: "A pattern that may lead to unfair outcomes",
    option_b_ar: "الهلوسة",
    option_b_en: "Hallucination",
    option_c_ar: "التراكب الكمي",
    option_c_en: "Quantum Superposition",
    option_d_ar: "الاستدلال الاحتمالي",
    option_d_en: "Probabilistic Inference",
    correct_option: "A",
    explanation_ar: "التحيز الخوارزمي هو نمط منهجي في مخرجات النظام يقود لنتائج غير متكافئة أو غير عادلة.",
    explanation_en: "Algorithmic bias is a systemic deviation resulting in unfair or discriminatory decisions."
  }
];
