import type { QuizQuestion } from './courseData';

export const OFFICIAL_ASSESSMENTS_L4: QuizQuestion[] = [
  // ==================== PERIOD 1: CLASSROOM TASKS (مهام أدائية - الفترة الأولى) ====================
  {
    id: "off_l4_c1_w1",
    lesson: "1-4",
    unit: "1",
    type: "WRITTEN",
    source: "CLASSROOM",
    difficulty: "MEDIUM",
    question_ar: "ما المقصود بمصطلح «التحيز الخوارزمي» في أنظمة الذكاء الاصطناعي، وما هي أبرز أشكاله أو أمثلته؟",
    question_en: "What is meant by 'Algorithmic Bias' in AI systems, and what are its prominent forms or examples?",
    ideal_answer_ar: "التحيز الخوارزمي هو حدوث أخطاء منهجية ومتكررة في مخرجات نظام الذكاء الاصطناعي ينتج عنها معاملة غير متكافئة أو غير عادلة لفئات معينة من الأفراد.\nأبرز أشكاله وأمثلته:\n1. أنظمة التوظيف الآلية التي تفضل الذكور على الإناث بناءً على بيانات توظيف تاريخية غير متوازنة.\n2. أنظمة التعرف على الوجه التي تنخفض دقتها بشكل ملحوظ مع أصحاب البشرة الداكنة بسبب نقص تمثيلهم في بيانات التدريب.",
    ideal_answer_en: "Algorithmic bias refers to systematic, repeatable errors in AI outputs that result in unfair privileges or penalties for specific demographic groups.\nKey examples:\n1. Automated resume screening tools favoring male applicants due to historically skewed hiring datasets.\n2. Facial recognition algorithms exhibiting higher error rates for individuals with darker skin tones due to underrepresentation in training archives.",
    explanation_ar: "التحيز الخوارزمي يعكس أخطاء منهجية تمييزية ناتجة عن خلل في البيانات أو الخوارزميات.",
    explanation_en: "Algorithmic bias manifests systemic discrimination rooted in skewed training data or algorithmic modeling."
  },
  {
    id: "off_l4_c1_w2",
    lesson: "1-4",
    unit: "1",
    type: "WRITTEN",
    source: "CLASSROOM",
    difficulty: "MEDIUM",
    question_ar: "وضح الأسباب الرئيسية لنشوء التحيز الخوارزمي في أنظمة الذكاء الاصطناعي؟",
    question_en: "Clarify the primary causes of algorithmic bias arising in AI systems?",
    ideal_answer_ar: "ينشأ التحيز الخوارزمي من عدة أسباب رئيسية:\n1. بيانات التدريب المتحيزة تاريخياً: احتواء البيانات التاريخية على تمييز مسبق يعيد النظام تعلمه وتكراره.\n2. نقص تمثيل فئات معينة (Under-representation): عدم كفاية البيانات الخاصة بأقليات أو شرائح اجتماعية معينة في مجموعة البيانات.\n3. اختيار غير سليم للمتغيرات (Feature Selection): الاعتماد على متغيرات بديلة (Proxies) ترتبط بشكل غير مباشر بصفات محمية كالرمز البريدي أو النوع.\n4. تحيز المطورين وتصميم النظام: إدخال افتراضات غير دقيقة أثناء بناء النماذج أو تقييمها بمقاييس مضللة.",
    ideal_answer_en: "Algorithmic bias stems from:\n1. Historically biased training datasets replicating systemic societal prejudices.\n2. Demographic underrepresentation leading to poor generalization for minority groups.\n3. Flawed feature engineering and proxy variables that covertly correlate with protected traits (e.g. zip codes as racial proxies).\n4. Developer assumptions and unrepresentative benchmark metrics during validation.",
    explanation_ar: "الأسباب الأربعة لنشوء التحيز: بيانات تاريخية غير عادلة، نقص التمثيل، المتغيرات البديلة، وتصميم النماذج.",
    explanation_en: "The four pillars of bias origins: historical disparity, data sparsity, proxy features, and developer design choices."
  },
  {
    id: "off_l4_c1_m1",
    lesson: "1-4",
    unit: "1",
    type: "MCQ",
    source: "CLASSROOM",
    difficulty: "EASY",
    question_ar: "أي من الخيارات التالية يُعد سبباً غير مناسب أو غير صحيح لنشوء التحيز الخوارزمي؟",
    question_en: "Which of the following is NOT an appropriate or true cause for algorithmic bias to emerge?",
    option_a_ar: "بيانات التدريب متحيزة",
    option_a_en: "Biased training data",
    option_b_ar: "انعكاس نزعات تمييزية سابقة في البيانات",
    option_b_en: "Reflection of past discriminatory tendencies in data",
    option_c_ar: "سرعة معالجة الحاسوب بطيئة",
    option_c_en: "Slow computer processing speed",
    option_d_ar: "وجود بيانات غير كافية عن سمات معينة",
    option_d_en: "Insufficient data regarding specific attributes",
    correct_option: "C",
    explanation_ar: "سرعة المعالجة الحاسوبية تتعلق بالأداء العتادي والزمن وليس لها أي علاقة بنشوء التحيز الخوارزمي أو العدالة.",
    explanation_en: "Hardware clock speed pertains strictly to compute latency, bearing zero causal relevance to algorithmic discrimination."
  },
  {
    id: "off_l4_c1_m2",
    lesson: "1-4",
    unit: "1",
    type: "MCQ",
    source: "CLASSROOM",
    difficulty: "EASY",
    question_ar: "ماذا يمثل مصطلح «التحيز الخوارزمي» في أنظمة الذكاء الاصطناعي؟",
    question_en: "What does the term 'Algorithmic Bias' represent in AI systems?",
    option_a_ar: "نمط في مخرجات الذكاء الاصطناعي قد يؤدي إلى نتائج غير عادلة أو ضارة",
    option_a_en: "A pattern in AI outputs that may lead to unfair or harmful outcomes",
    option_b_ar: "تقنية تتيح للبشر فهم سبب اتخاذ الذكاء الاصطناعي حكماً معيناً",
    option_b_en: "A technique enabling humans to understand why AI made a specific judgment",
    option_c_ar: "التعامل المناسب مع البيانات الشخصية وحمايتها",
    option_c_en: "Appropriate handling and protection of personal data",
    option_d_ar: "تحديد الجهات المسؤولة عن النظام وقراراته وآثاره",
    option_d_en: "Determining parties liable for system decisions and impacts",
    correct_option: "A",
    explanation_ar: "التحيز الخوارزمي هو نمط في مخرجات النظام يؤدي لنتائج غير عادلة أو متحيزة ضد أشخاص أو فئات.",
    explanation_en: "Algorithmic bias is a systemic trend yielding unfair, asymmetric, or injurious consequences."
  },

  // ==================== PERIOD 1: HOMEWORK (أداءات منزلية - الفترة الأولى) ====================
  {
    id: "off_l4_h1_w1",
    lesson: "1-4",
    unit: "1",
    type: "WRITTEN",
    source: "HOMEWORK",
    difficulty: "MEDIUM",
    question_ar: "اشرح كيف أدى تطور تقنية الذكاء الاصطناعي إلى ظهور قضايا جديدة تتعلق بالخصوصية والمراقبة في الأماكن العامة.",
    question_en: "Explain how the advancement of AI technology has introduced new concerns regarding privacy and surveillance in public spaces.",
    ideal_answer_ar: "مع دمج خوارزميات التعرف على الوجه المتقدمة ورؤية الحاسوب بكاميرات المراقبة في الشوارع والمطارات والمراكز التجارية، أصبح بالإمكان تتبع حركة وسلوك الأفراد دون موافقتهم الصريحة أو علمهم. كما أدى الجمع الجماعي للبيانات الرقمية وتتبع الموقع الجغرافي وتحليل السلوك عبر الإنترنت إلى تآكل مفهوم المساحة الخاصة للأفراد وزيادة مخاطر استغلال البيانات لأغراض المراقبة الجماعية أو التسويق التطفلي دون ضمانات كافية.",
    ideal_answer_en: "Equipping public surveillance cameras with facial recognition and computer vision allows continuous, passive biometric tracking of individuals without consent. Paired with massive behavioural online telemetry aggregation, this erodes civilian anonymity, enabling invasive profiling and mass monitoring without regulatory oversight.",
    explanation_ar: "انتشار التعرف على الوجه والتتبع اللحظي يهدد الخصوصية ويخلق مراقبة جماعية غير مسبوقة.",
    explanation_en: "Ubiquitous facial recognition and behavioral tracking threaten personal liberty and anonymized movement."
  },
  {
    id: "off_l4_h1_w2",
    lesson: "1-4",
    unit: "1",
    type: "WRITTEN",
    source: "HOMEWORK",
    difficulty: "MEDIUM",
    question_ar: "ما المقصود بمصطلح «بيانات التدريب» في أنظمة الذكاء الاصطناعي، وكيف يؤثر نقص تمثيلها على المخرجات؟",
    question_en: "What is meant by 'training data' in AI systems, and how does lack of representation affect outputs?",
    ideal_answer_ar: "بيانات التدريب هي مجموعة الأمثلة والبيانات الرقمية التي يتغذى عليها نموذج الذكاء الاصطناعي ليتعلم منها الأنماط والعلاقات قبل دخوله حيز التشغيل. يؤثر نقص تمثيل فئات معينة في هذه البيانات على تدني دقة النموذج تجاه تلك الفئات، مما يجعله يصدر أحكاماً خاطئة أو متحيزة ضدهم لأن النموذج لم يتعلم خصائصهم بشكل كافٍ أثناء التدريب.",
    ideal_answer_en: "Training data constitutes the dataset of labeled or unlabeled inputs supplied to a machine learning model to optimize its parameters and identify latent correlations. Demographic underrepresentation produces performance degradation and skew for omitted groups, causing false positives or erroneous classifications.",
    explanation_ar: "بيانات التدريب هي الأساس المعرفي للنظام؛ وأي نقص فيها ينتج عنه تحيز وضعف في دقة المخرجات.",
    explanation_en: "Training data is the cognitive bedrock; omissions inevitably corrupt generalizability and fairness."
  },
  {
    id: "off_l4_h1_m1",
    lesson: "1-4",
    unit: "1",
    type: "MCQ",
    source: "HOMEWORK",
    difficulty: "EASY",
    question_ar: "أي من الخيارات الآتية يمثل المفهوم الدقيق لـ «بيانات التدريب»؟",
    question_en: "Which of the following represents the precise concept of 'Training Data'?",
    option_a_ar: "الأمثلة التي يتعلم منها نظام الذكاء الاصطناعي أنماطه قبل استخدامه",
    option_a_en: "The examples from which the AI system learns its patterns prior to deployment",
    option_b_ar: "تقنية تتيح للبشر فهم سبب اتخاذ الذكاء الاصطناعي حكماً معيناً",
    option_b_en: "A technique enabling humans to understand why AI made a specific judgment",
    option_c_ar: "تحديد الجهات المسؤولة عن النظام وقراراته وآثاره",
    option_c_en: "Determining parties liable for system decisions and impacts",
    option_d_ar: "عدم التمييز ظلماً ضد أي شخص أو مجموعة",
    option_d_en: "Not discriminating unfairly against any person or group",
    correct_option: "A",
    explanation_ar: "بيانات التدريب هي العينات والأمثلة التي يتم تزويد الخوارزمية بها لتتعلم الأنماط وتضبط أوزانها.",
    explanation_en: "Training data refers to empirical samples fed into models to optimize parameter weights."
  },
  {
    id: "off_l4_h1_m2",
    lesson: "1-4",
    unit: "1",
    type: "MCQ",
    source: "HOMEWORK",
    difficulty: "EASY",
    question_ar: "ما هي إحدى قضايا الخصوصية المرتبطة بالذكاء الاصطناعي؟",
    question_en: "What is one of the primary privacy concerns associated with AI?",
    option_a_ar: "تحسين سرعة حوسبة الذكاء الاصطناعي",
    option_a_en: "Enhancing AI computational speed",
    option_b_ar: "إنشاء الذكاء الاصطناعي لأعمال إبداعية",
    option_b_en: "AI creating artistic works",
    option_c_ar: "التعرف على الأفراد وتتبعهم من خلال تقنية التعرف على الوجه",
    option_c_en: "Identifying and tracking individuals through facial recognition technology",
    option_d_ar: "زيادة كفاءة المعالجات الدقيقة",
    option_d_en: "Increasing microprocessor efficiency",
    correct_option: "C",
    explanation_ar: "تتبع الأفراد في الأماكن العامة والتعرف على هوياتهم دون إذن يُعد من أخطر انتهاكات الخصوصية.",
    explanation_en: "Passive biometric facial tracking in public areas constitutes an acute privacy violation."
  },

  // ==================== PERIOD 2: CLASSROOM TASKS (مهام أدائية - الفترة الثانية) ====================
  {
    id: "off_l4_c2_w1",
    lesson: "1-4",
    unit: "1",
    type: "WRITTEN",
    source: "CLASSROOM",
    difficulty: "HARD",
    question_ar: "ما المقصود بمصطلح «الذكاء الاصطناعي القابل للتفسير (XAI)»، ولماذا يُعد أسلوباً أساسياً للتغلب على مشكلة الصندوق الأسود؟",
    question_en: "What is meant by 'Explainable AI (XAI)', and why is it an essential approach to overcome the black box problem?",
    ideal_answer_ar: "الذكاء الاصطناعي القابل للتفسير (Explainable AI - XAI) هو مجموعة من التقنيات والأساليب التي تجعل مخرجات وعمليات نماذج الذكاء الاصطناعي مفهومة وشفافة للخبراء والبشر، موضحاً العوامل التي أدت لاتخاذ قرار معين.\nيُعد أسلوباً أساسياً للتغلب على مشكلة الصندوق الأسود لأنه يفك غموض الشبكات المعقدة، ويتيح التحقق من عدم وجود تحيز خفي، وتسهيل اكتشاف الأخطاء، وبناء الثقة لدى الأطباء والقضاة والمستخدمين، وضمان الامتثال للوائح القانونية.",
    ideal_answer_en: "Explainable AI (XAI) comprises techniques designed to clarify decision logic, feature contributions, and internal reasoning pathways of machine learning models to humans.\nIt is essential to conquering the black box problem because it demystifies opaque neural topologies, enables auditing for latent bias, facilitates root-cause bug debugging, builds clinical and judicial trust, and meets legal compliance mandates.",
    explanation_ar: "الذكاء الاصطناعي القابل للتفسير هو الحل التقني والرقابي لتفكيك غموض الصندوق الأسود.",
    explanation_en: "XAI serves as the technical remedy to penetrate black-box opacity and audit algorithmic reasoning."
  },
  {
    id: "off_l4_c2_w2",
    lesson: "1-4",
    unit: "1",
    type: "WRITTEN",
    source: "CLASSROOM",
    difficulty: "MEDIUM",
    question_ar: "قارن بإيجاز بين مفهوم «المسؤولية» ومفهوم «المساءلة» في سياق أنظمة الذكاء الاصطناعي؟",
    question_en: "Compare briefly between the concepts of 'Responsibility' and 'Accountability' in the context of AI systems?",
    ideal_answer_ar: "المسؤولية (Responsibility): تتعلق بتحديد وتوزيع الأدوار والواجبات الإلزامية على جميع الأطراف المعنية (المطور لتوفير بيانات غير متحيزة، والمشغل لضمان عمل النظام بأمان، والمستخدم لاستعماله بطريقة سليمة).\nالمساءلة (Accountability): تعني تحديد الجهة المحددة التي يمكن محاسبتها ومطالبتها قانونياً وأخلاقياً بتقديم تفسيرات أو تعويضات عند وقوع ضرر أو خطأ ناتج عن النظام.",
    ideal_answer_en: "Responsibility: Pertains to demarcating roles, operational duties, and best practices across developers, operators, and end-users proactively.\nAccountability: Pertains to determining enforceable liability—specifying which party is legally, morally, and financially answerable to explain outcomes and rectify damages when failures happen.",
    explanation_ar: "المسؤولية هي الواجبات وتوزيع الأدوار، بينما المساءلة هي المحاسبة القانونية والأخلاقية عند وقوع الخطأ.",
    explanation_en: "Responsibility dictates duties, whereas accountability enforces punitive/remedial liability upon failure."
  },
  {
    id: "off_l4_c2_m1",
    lesson: "1-4",
    unit: "1",
    type: "MCQ",
    source: "CLASSROOM",
    difficulty: "EASY",
    question_ar: "ما هو المصطلح الذي يصف التقنية التي تتيح للبشر فهم العوامل والسبب الذي أدى بالذكاء الاصطناعي إلى اتخاذ حكم معين؟",
    question_en: "What term describes the technique enabling humans to understand factors and causes leading AI to make a specific judgment?",
    option_a_ar: "الحوسبة السحابية",
    option_a_en: "Cloud Computing",
    option_b_ar: "الذكاء الاصطناعي القابل للتفسير (XAI)",
    option_b_en: "Explainable AI (XAI)",
    option_c_ar: "الحوسبة الطرفية",
    option_c_en: "Edge Computing",
    option_d_ar: "التحيز الخوارزمي",
    option_d_en: "Algorithmic Bias",
    correct_option: "B",
    explanation_ar: "الذكاء الاصطناعي القابل للتفسير (XAI) هو التقنية المتخصصة في إيضاح آلية صدور القرارات وتبريرها.",
    explanation_en: "Explainable AI (XAI) exposes the rationale behind model predictions."
  },
  {
    id: "off_l4_c2_m2",
    lesson: "1-4",
    unit: "1",
    type: "MCQ",
    source: "CLASSROOM",
    difficulty: "MEDIUM",
    question_ar: "ما الفرق الأساسي بين «المسؤولية» و«المساءلة» كما تم توضيحه في الدرس؟",
    question_en: "What is the primary difference between 'Responsibility' and 'Accountability' as explained in the lesson?",
    option_a_ar: "المسؤولية تعني إظهار عملية اتخاذ القرار بينما المساءلة تعني سرعة المعالجة",
    option_a_en: "Responsibility means displaying the decision process, while accountability means processing speed",
    option_b_ar: "المسؤولية تتعلق بتحديد أدوار وواجبات الأطراف، بينما تعني المساءلة تحديد الجهات التي يمكن محاسبتها وفق أدوارها",
    option_b_en: "Responsibility concerns defining roles and duties of parties, while accountability means identifying liable parties subject to sanctions based on roles",
    option_c_ar: "المساءلة هي التقنية التي تفهم منطق الذكاء الاصطناعي بينما المسؤولية هي جمع البيانات",
    option_c_en: "Accountability is the tech that understands AI logic, while responsibility is data collection",
    option_d_ar: "لا يوجد أي فرق بينهما فهما مصطلحان مترادفان تماماً",
    option_d_en: "There is no difference; they are completely synonymous terms",
    correct_option: "B",
    explanation_ar: "المسؤولية تحدد الأدوار والواجبات، بينما المساءلة تحدد من تجري محاسبته عن النتائج والأضرار.",
    explanation_en: "Responsibility defines roles and obligations; accountability identifies who answers for consequences."
  },

  // ==================== PERIOD 2: HOMEWORK (أداءات منزلية - الفترة الثانية) ====================
  {
    id: "off_l4_h2_w1",
    lesson: "1-4",
    unit: "1",
    type: "WRITTEN",
    source: "HOMEWORK",
    difficulty: "MEDIUM",
    question_ar: "اذكر المبادئ الأربعة الأساسية لأخلاقيات الذكاء الاصطناعي مع شرح مبدأ «العدالة» باختصار.",
    question_en: "Mention the four fundamental principles of AI ethics, briefly explaining the principle of 'Fairness'.",
    ideal_answer_ar: "المبادئ الأربعة الأساسية هي:\n1. العدالة (Fairness).\n2. الشفافية (Transparency).\n3. حماية الخصوصية (Privacy Protection).\n4. المساءلة (Accountability).\nشرح مبدأ العدالة: يقتضي تصميم وتشغيل أنظمة الذكاء الاصطناعي بحيث لا تميز ظلماً أو تحيزاً ضد أي شخص أو فئة بسبب العرق، أو النوع، أو الدين، أو أي صفة محمية قانونياً، وضمان تكافؤ الفرص في جميع المخرجات.",
    ideal_answer_en: "The four pillars of AI ethics are:\n1. Fairness\n2. Transparency\n3. Privacy Protection\n4. Accountability\nFairness definition: Demands that AI algorithms neither perpetuate discriminatory harm nor bias judgments against individuals based on protected attributes (gender, ethnicity, socioeconomics), ensuring equitable parity.",
    explanation_ar: "المبادئ الأخلاقية الأربعة المقررة، والعدالة تعني النزاهة والمساواة وعدم التمييز.",
    explanation_en: "The four canon ethical principles, with Fairness commanding non-discriminatory parity."
  },
  {
    id: "off_l4_h2_w2",
    lesson: "1-4",
    unit: "1",
    type: "WRITTEN",
    source: "HOMEWORK",
    difficulty: "MEDIUM",
    question_ar: "وضح المقصود بكل من مبدأ «الشفافية» ومبدأ «حماية الخصوصية» في إطار الاستخدام المسؤول للذكاء الاصطناعي.",
    question_en: "Clarify what is meant by both 'Transparency' and 'Privacy Protection' in the context of responsible AI use.",
    ideal_answer_ar: "الشفافية (Transparency): إتاحة معلومات واضحة ومناسبة للمستخدمين وأصحاب المصلحة حول كيفية عمل النظام، والبيانات المستخدمة في تدريبه، وحدوده، والمنطق العام لاتخاذ القرار دون تعمية.\nحماية الخصوصية (Privacy Protection): التعامل المسؤول والقانوني مع البيانات الشخصية والحساسة للمستخدمين، وتطبيق التشفير، وضمان عدم جمع البيانات أو مشاركتها أو استخدامها لأغراض المراقبة دون إذن صريح ومستنير.",
    ideal_answer_en: "Transparency: Disclosing clear, intelligible specifications concerning operational scope, training corpus origin, capability limitations, and algorithmic reasoning mechanics.\nPrivacy Protection: Enforcing cryptographic safeguards and governance protocols that prohibit unconsented harvesting, sharing, or covert tracking of personal identity data.",
    explanation_ar: "الشفافية تضمن وضوح المعلومات وحدود النظام، والخصوصية تضمن سرية البيانات وحمايتها.",
    explanation_en: "Transparency demystifies system mechanisms; privacy safeguards sensitive biometric and behavioral information."
  },
  {
    id: "off_l4_h2_m1",
    lesson: "1-4",
    unit: "1",
    type: "MCQ",
    source: "HOMEWORK",
    difficulty: "EASY",
    question_ar: "من بين المبادئ الأساسية لأخلاقيات الذكاء الاصطناعي، ما هو المبدأ الذي يقتضي عدم التمييز ظلماً ضد أي شخص أو مجموعة بعينها؟",
    question_en: "Among the foundational principles of AI ethics, which principle dictates non-discrimination against any person or group?",
    option_a_ar: "الشفافية",
    option_a_en: "Transparency",
    option_b_ar: "المساءلة",
    option_b_en: "Accountability",
    option_c_ar: "العدالة",
    option_c_en: "Fairness",
    option_d_ar: "حماية الخصوصية",
    option_d_en: "Privacy Protection",
    correct_option: "C",
    explanation_ar: "العدالة (Fairness) تمنع التمييز الظالم وتضمن تكافؤ الفرص في الأحكام والقرارات.",
    explanation_en: "Fairness is the principle dedicated to preventing prejudicial discrimination."
  },
  {
    id: "off_l4_h2_m2",
    lesson: "1-4",
    unit: "1",
    type: "MCQ",
    source: "HOMEWORK",
    difficulty: "EASY",
    question_ar: "ما هو المبدأ الذي يشير إلى إتاحة معلومات واضحة ومناسبة عن النظام واستخدامه وعملية اتخاذ القرار وحدوده؟",
    question_en: "What principle refers to providing clear and appropriate information about the system, its use, decision process, and limitations?",
    option_a_ar: "العدالة",
    option_a_en: "Fairness",
    option_b_ar: "الشفافية",
    option_b_en: "Transparency",
    option_c_ar: "حماية الخصوصية",
    option_c_en: "Privacy Protection",
    option_d_ar: "المسؤولية",
    option_d_en: "Responsibility",
    correct_option: "B",
    explanation_ar: "الشفافية تعني وضوح المعلومات والإفصاح عن كيفية عمل النظام وحدوده.",
    explanation_en: "Transparency mandates open disclosure regarding algorithmic function and limitations."
  },

  // ==================== WEEKLY ASSESSMENT: MODEL A (التقييمات الأسبوعية - النموذج A) ====================
  {
    id: "off_l4_wka_w1",
    lesson: "1-4",
    unit: "1",
    type: "WRITTEN",
    source: "WEEKLY_ASSESSMENT",
    difficulty: "HARD",
    question_ar: "اشرح ماهية «التحيز الخوارزمي» في أنظمة الذكاء الاصطناعي مبيناً كيف ينشأ من بيانات التدريب أو تصميم النظام وطريقة استخدامه مع ذكر أمثلة.",
    question_en: "Explain what 'Algorithmic Bias' is in AI systems, showing how it originates from training data or system design and usage, citing examples.",
    ideal_answer_ar: "التحيز الخوارزمي هو انحراف منهجي في القرارات يؤدي لمعاملة فئات معينة بشكل غير عادل. ينشأ من:\n1. بيانات التدريب: انعكاس التمييز البشري التاريخي (مثل تدريب أنظمة الترجمة على ربط مهن معينة كـ'طبيب' بالذكور و'ممرضة' بالإناث).\n2. تصميم النظام: اختيار معايير تقييم أو مؤشرات غير دقيقة تميز ضد جماعات معينة.\n3. طريقة الاستخدام: تطبيق النظام في سياق غير الذي دُرّب عليه.\nمثال شهير: برامج التوظيف التي ترفض السير الذاتية للنساء إذا تضمنت اسم كلية نسائية، أو أنظمة التقييم الائتماني التي تعطي نقاطاً أقل لسكان أحياء معينة.",
    ideal_answer_en: "Algorithmic bias is a systemic distortion in decisions causing discriminatory prejudice. Originates via: 1. Skewed training data encapsulating human history. 2. Flawed feature engineering and loss functions. 3. Deploying models out-of-domain. Examples: Screening algorithms penalizing female applicants, or credit scoring algorithms discriminating against applicants by geographic zip codes.",
    explanation_ar: "التحيز الخوارزمي ونشأته من البيانات والتصميم والاستخدام مع أمثلة حية.",
    explanation_en: "Detailed exploration of bias root causes across lifecycle with tangible case studies."
  },
  {
    id: "off_l4_wka_w2",
    lesson: "1-4",
    unit: "1",
    type: "WRITTEN",
    source: "WEEKLY_ASSESSMENT",
    difficulty: "HARD",
    question_ar: "تكلم بالتفصيل عن «الذكاء الاصطناعي القابل للتفسير (XAI)» ومشكلة «الصندوق الأسود» وكيف يساهم في تقييم النظام واكتشاف الأخطاء؟",
    question_en: "Discuss in detail 'Explainable AI (XAI)' and the 'Black Box Problem', and how it contributes to system evaluation and debugging?",
    ideal_answer_ar: "مشكلة الصندوق الأسود تعني أن الشبكات العصبية العميقة تعالج ملايين المعاملات بصورة رياضية يستحيل على البشر فهم مسارها، مما يصعب كشف الأخطاء أو التأكد من سلامة القرارات. يأتي الذكاء الاصطناعي القابل للتفسير (XAI) ليقدم أدوات وطرقاً توضح أوزان الخصائص الأكثر تأثيراً في القرار (مثل إبراز المنطقة المشبوهة في الأشعة الطبية). يساهم ذلك في: كشف التحيز الخفي، وإصلاح الأخطاء، ومنح الأطباء والقضاة أسباباً مقنعة لقبول التوصية أو رفضها.",
    ideal_answer_en: "Deep neural networks are functionally black boxes due to millions of non-linear parametric calculations that defy human intuition. XAI exposes interpretable explanations (e.g. saliency maps, SHAP feature importance). This empowers engineers to audit and eliminate bugs, assists clinicians in validating automated scan classifications, and satisfies legal mandates for contestability.",
    explanation_ar: "XAI يحول الصندوق الأسود إلى نظام شفاف قابل للتقييم والمراجعة البشرية.",
    explanation_en: "XAI transforms opaque black boxes into transparent, verifiable computational systems."
  },
  {
    id: "off_l4_wka_w3",
    lesson: "1-4",
    unit: "1",
    type: "WRITTEN",
    source: "WEEKLY_ASSESSMENT",
    difficulty: "HARD",
    question_ar: "قارن بدقة بين مفهوم «المسؤولية» ومفهوم «المساءلة» موضحاً سبب اختلاف توزيع المسؤولية باختلاف السياقات والأطراف (المطور، المشغل، المستخدم)؟",
    question_en: "Carefully compare 'Responsibility' and 'Accountability', explaining why responsibility allocation varies across contexts and stakeholders (developer, operator, user)?",
    ideal_answer_ar: "المسؤولية تشير للواجبات الاستباقية، بينما المساءلة تشير للالتزام القانوني والتعويضي عند حدوث ضرر.\nيختلف توزيع المسؤولية بحسب السياق لأن الأدوار متعددة:\n1. المطور: مسؤول عن سلامة الكود، وخلو بيانات التدريب من التحيز، وتقديم وثائق واضحة.\n2. المشغل (المؤسسة المشغلة): مسؤول عن صيانة النظام وتدريب الموظفين ووضع إجراءات أمان تشغيلية.\n3. المستخدم (كالطبيب أو السائق): مسؤول عن التأكد من المخرجات وعدم الاعتماد الأعمى عليها، ومراعاة شروط الاستخدام.",
    ideal_answer_en: "Responsibility designates proactive obligations, whereas accountability assigns punitive or compensatory liability post-failure. Distribution depends on stakeholding: 1. Developers bear duty for algorithmic integrity, data bias mitigation, and architectural hygiene. 2. Deployers/Operators are accountable for operational safety envelopes and staff training. 3. End-Users must exert due diligence, avoiding blind over-reliance.",
    explanation_ar: "توزيع المسؤولية التشاركية بين المطور والمشغل والمستخدم.",
    explanation_en: "Shared stakeholder liability frameworks across development, deployment, and end-use."
  },
  {
    id: "off_l4_wka_w4",
    lesson: "1-4",
    unit: "1",
    type: "WRITTEN",
    source: "WEEKLY_ASSESSMENT",
    difficulty: "HARD",
    question_ar: "اذكر المبادئ الأربعة الأساسية لأخلاقيات الذكاء الاصطناعي واشرح باختصار المقصود بكل من «العدالة»، «الشفافية»، «حماية الخصوصية»، و«المساءلة».",
    question_en: "List the four fundamental principles of AI ethics and briefly explain each: Fairness, Transparency, Privacy Protection, and Accountability.",
    ideal_answer_ar: "1. العدالة (Fairness): تجنب التمييز والتحيز غير المبرر ضد أي فئة وضمان تكافؤ الفرص.\n2. الشفافية (Transparency): إيضاح آلية عمل النظام وحدوده وبياناته للمستخدمين بوضوح.\n3. حماية الخصوصية (Privacy Protection): صون البيانات الشخصية ومنع انتهاك سرية الأفراد أو مراقبتهم دون إذن.\n4. المساءلة (Accountability): تحديد الجهات المسؤولة عن الأخطاء والآثار الضارة وإمكانية محاسبتها وفق أدوارها.",
    ideal_answer_en: "1. Fairness: Eradication of biased disadvantages, fostering equal treatment across protected demographics.\n2. Transparency: Understandable disclosures regarding algorithmic constraints, logic, and dataset origins.\n3. Privacy Protection: Rigorous protection of individual personally identifiable information and protection from non-consensual surveillance.\n4. Accountability: Clearly demarcated liability channels enforcing responsibility and legal remedies upon failures.",
    explanation_ar: "شرح شامل وموجز للمبادئ الأربعة لأخلاقيات الذكاء الاصطناعي.",
    explanation_en: "Comprehensive summary of the 4 foundational AI ethics principles."
  },
  {
    id: "off_l4_wka_m1",
    lesson: "1-4",
    unit: "1",
    type: "MCQ",
    source: "WEEKLY_ASSESSMENT",
    difficulty: "EASY",
    question_ar: "نمط في مخرجات الذكاء الاصطناعي قد يؤدي إلى نتائج غري عادلة أو ضارة، وينشأ من البيانات أو التصميم يسمى:",
    question_en: "A pattern in AI outputs that may lead to unfair or harmful results, stemming from data or design, is called:",
    option_a_ar: "الذكاء الاصطناعي القابل للتفسير (XAI)",
    option_a_en: "Explainable AI (XAI)",
    option_b_ar: "التحيز الخوارزمي",
    option_b_en: "Algorithmic Bias",
    option_c_ar: "الشفافية المطلقة",
    option_c_en: "Absolute Transparency",
    option_d_ar: "حماية الخصوصية",
    option_d_en: "Privacy Protection",
    correct_option: "B",
    explanation_ar: "التحيز الخوارزمي هو النمط الذي يسبب نتائج غير متكافئة أو تمييزية.",
    explanation_en: "Algorithmic bias describes the pattern responsible for disparate adverse outcomes."
  },
  {
    id: "off_l4_wka_m2",
    lesson: "1-4",
    unit: "1",
    type: "MCQ",
    source: "WEEKLY_ASSESSMENT",
    difficulty: "EASY",
    question_ar: "تقنية تتيح للبشر فهم سبب اتخاذ الذكاء الاصطناعي حكماً معيناً وتساعد على تجنب مشكلة الصندوق الأسود هي:",
    question_en: "A technique allowing humans to understand why AI made a specific judgment and helping avoid the black box problem is:",
    option_a_ar: "الذكاء الاصطناعي القابل للتفسير (XAI)",
    option_a_en: "Explainable AI (XAI)",
    option_b_ar: "الحوسبة الطرفية",
    option_b_en: "Edge Computing",
    option_c_ar: "بيانات التدريب",
    option_c_en: "Training Data",
    option_d_ar: "التحيز الخوارزمي",
    option_d_en: "Algorithmic Bias",
    correct_option: "A",
    explanation_ar: "الذكاء الاصطناعي القابل للتفسير يزيل غموض الصندوق الأسود ويقدم أسباب المخرجات.",
    explanation_en: "Explainable AI (XAI) elucidates internal neural mechanisms."
  },
  {
    id: "off_l4_wka_m3",
    lesson: "1-4",
    unit: "1",
    type: "MCQ",
    source: "WEEKLY_ASSESSMENT",
    difficulty: "EASY",
    question_ar: "المبدأ الذي يعني التعامل مع المعلومات الشخصية بشكل مناسب وحمايتها هو:",
    question_en: "The principle that means dealing with personal information properly and protecting it is:",
    option_a_ar: "العدالة",
    option_a_en: "Fairness",
    option_b_ar: "الشفافية",
    option_b_en: "Transparency",
    option_c_ar: "حماية الخصوصية",
    option_c_en: "Privacy Protection",
    option_d_ar: "المساءلة",
    option_d_en: "Accountability",
    correct_option: "C",
    explanation_ar: "حماية الخصوصية تعني الحفاظ على البيانات الشخصية وسريتها.",
    explanation_en: "Privacy protection secures personal confidential data."
  },
  {
    id: "off_l4_wka_m4",
    lesson: "1-4",
    unit: "1",
    type: "MCQ",
    source: "WEEKLY_ASSESSMENT",
    difficulty: "EASY",
    question_ar: "تحديد الجهات المسؤولة عن النظام وقراراته وآثاره وإمكان محاسبتها وفق أدوارها يمثل مبدأ:",
    question_en: "Defining the entities liable for system decisions and consequences to be held accountable represents:",
    option_a_ar: "الشفافية",
    option_a_en: "Transparency",
    option_b_ar: "العدالة",
    option_b_en: "Fairness",
    option_c_ar: "المساءلة",
    option_c_en: "Accountability",
    option_d_ar: "حماية الخصوصية",
    option_d_en: "Privacy Protection",
    correct_option: "C",
    explanation_ar: "المساءلة (Accountability) هي مبدأ تحديد ومحاسبة المسؤولين عن القرارات والأضرار.",
    explanation_en: "Accountability enforces answerability and legal liability."
  },

  // ==================== WEEKLY ASSESSMENT: MODEL B (النموذج B) ====================
  {
    id: "off_l4_wkb_w1",
    lesson: "1-4",
    unit: "1",
    type: "WRITTEN",
    source: "WEEKLY_ASSESSMENT",
    difficulty: "HARD",
    question_ar: "وضح كيف يمكن أن تؤدي بيانات التدريب غير الممثلة أو المتحيزة (مثل انعكاس نزعات تمييزية سابقة) إلى تكرار الذكاء الاصطناعي لهذا التحيز في أحكامه.",
    question_en: "Explain how unrepresentative or biased training data (reflecting historical disparities) causes AI to replicate bias in judgments.",
    ideal_answer_ar: "يتعلم نموذج الذكاء الاصطناعي عن طريق استخلاص الأنماط الإحصائية من البيانات المعطاة له دون وعي بالسياق الأخلاقي. فإذا كانت البيانات تعكس ممارسات تاريخية غير منصفة (مثل قلة ترقية فئات معينة)، فإن النموذج يعتبر هذا التفاوت قاعدة صحيحة ينبغي اتباعها، وبالتالي يعيد إنتاج التمييز وتعميقه في أحكامه المستقبلية.",
    ideal_answer_en: "AI algorithms derive mathematical correlations strictly from observed input empirical frequencies without ethical context. If input corpora mirror systemic bias or historical prejudice, the model incorporates that prejudice as a legitimate predictive norm, mechanizing and magnifying future systemic bias.",
    explanation_ar: "النماذج تعيد إنتاج التحيز الكامن في البيانات لأنها تستنتج القواعد إحصائياً من الواقع المسجل.",
    explanation_en: "AI models mirror historical inequalities because statistical learning formalizes recorded asymmetries."
  },
  {
    id: "off_l4_wkb_w2",
    lesson: "1-4",
    unit: "1",
    type: "WRITTEN",
    source: "WEEKLY_ASSESSMENT",
    difficulty: "HARD",
    question_ar: "اشرح مشكلة «الصندوق الأسود» في خوارزميات الذكاء الاصطناعي المعقدة ولماذا يجعل تقييم الآلية واكتشاف الأخطاء أمراً صعباً دون استخدام تقنيات التفسير.",
    question_en: "Explain the 'Black Box' problem in complex AI algorithms and why evaluating mechanisms and debugging errors is difficult without interpretability.",
    ideal_answer_ar: "تتكون خوارزميات التعلم العميق من ملايين العقد والأوزان المتشابكة، وتعتمد على تحويلات رياضية غير خطية معقدة تجعل تتبع مسار القرار مستحيلاً على العقل البشري. بدون تقنيات التفسير (XAI)، لا يمكن للمهندس معرفة ما إذا كان النموذج قد اتخذ قراره بناءً على مؤشرات حقيقية سليمة أم بناءً على صدفة أو ارتباطات خاطئة مضللة، مما يعيق التصحيح والمراجعة.",
    ideal_answer_en: "Deep architectures contain millions of intertwined non-linear weight matrices. Without XAI, humans cannot trace why a decision was reached, making it impossible to determine whether decisions rest on legitimate features or spurious, invalid correlations (e.g. background noise), precluding reliable auditing.",
    explanation_ar: "الصندوق الأسود يخفي المنطق الداخلي، مما يجعل اكتشاف الأخطاء وتصحيحها مستحيلاً بدون XAI.",
    explanation_en: "Black-box opacity conceals root causes, obstructing bug identification and fairness validation without XAI."
  },
  {
    id: "off_l4_wkb_w3",
    lesson: "1-4",
    unit: "1",
    type: "WRITTEN",
    source: "WEEKLY_ASSESSMENT",
    difficulty: "MEDIUM",
    question_ar: "اذكر قضايا الخصوصية المرتبطة بانتشار تقنيات التعرف على الوجه في الأماكن العامة والجمع الجماعي للبيانات والسلوك عبر الإنترنت.",
    question_en: "Mention the privacy concerns linked to ubiquitous public facial recognition and mass collection of behavioral online data.",
    ideal_answer_ar: "1. تآكل المساحة الخاصة والحق في عدم الكشف عن الهوية في الأماكن العامة.\n2. إمكانية تتبع الأفراد دون إذن أو إخطار مسبق.\n3. مخاطر تسريب أو سرقة قواعد البيانات البيومترية التي لا يمكن تغييرها (مثل بصمة الوجه).\n4. بناء ملفات شخصية وسلوكية تفصيلية واستخدامها للتأثير على آراء وسلوكيات الأفراد أو المراقبة الاستبدادية.",
    ideal_answer_en: "1. Complete erosion of civilian anonymity in public environments.\n2. Unconsented, passive biometric tracking without notification.\n3. Catastrophic vulnerability to biometric database leaks, which cannot be reset unlike passwords.\n4. Invasive behavioral profiling exploited for psychological manipulation or authoritarian surveillance.",
    explanation_ar: "قضايا الخصوصية: انتهاك الهوية، المراقبة المستمرة، وتجميع البيانات البيومترية.",
    explanation_en: "Key privacy issues: Anonymity destruction, pervasive surveillance, and irreversible biometric hazards."
  },
  {
    id: "off_l4_wkb_w4",
    lesson: "1-4",
    unit: "1",
    type: "WRITTEN",
    source: "WEEKLY_ASSESSMENT",
    difficulty: "HARD",
    question_ar: "اشرح بالتفصيل المبادئ الأربعة الأساسية لأخلاقيات الذكاء الاصطناعي وكيف يوجه كل منها الاستخدام المسؤول لهذه التقنيات في المجتمع.",
    question_en: "Explain in detail the four fundamental principles of AI ethics and how each guides responsible deployment in society.",
    ideal_answer_ar: "1. العدالة: توجه نحو استبعاد التمييز وتكافؤ الفرص في التوظيف والتعليم والصحة.\n2. الشفافية: تلزم الشركات بإيضاح حدود النظام والبيانات المستخدمة وكيفية صدور التوصيات لضمان الفهم والثقة.\n3. حماية الخصوصية: توجه نحو تقليل البيانات المجموعة وتأمينها وضمان سيادة الأفراد على بياناتهم.\n4. المساءلة: تضمن وجود أطر قانونية تحدد الطرف المسؤول وتلزم بالتعويض ومراجعة القرارات الضارة.",
    ideal_answer_en: "1. Fairness directs developers to eliminate discriminatory bias across high-impact civic arenas.\n2. Transparency enforces open disclosure of model capabilities, boundary conditions, and rationale.\n3. Privacy Protection dictates data minimization, sovereign user consent, and robust encryption.\n4. Accountability establishes operational responsibility and judicial restitution channels for injured parties.",
    explanation_ar: "المبادئ الأربعة كدليل إرشادي شامل للاستخدام الآمن والمسؤول للذكاء الاصطناعي.",
    explanation_en: "The 4 ethics principles acting as a complete governance blueprint for safe societal deployment."
  },
  {
    id: "off_l4_wkb_m1",
    lesson: "1-4",
    unit: "1",
    type: "MCQ",
    source: "WEEKLY_ASSESSMENT",
    difficulty: "EASY",
    question_ar: "الأمثلة التي يتعلم منها نظام الذكاء الاصطناعي أنماطه قبل استخدامه وتؤثر بشكل مباشر على جودة مخرجاته تسمى:",
    question_en: "The examples from which an AI system learns patterns before deployment, directly affecting its output quality, are called:",
    option_a_ar: "بيانات التدريب",
    option_a_en: "Training Data",
    option_b_ar: "خوارزميات التشفير",
    option_b_en: "Encryption Algorithms",
    option_c_ar: "الأجهزة الطرفية",
    option_c_en: "Peripheral Devices",
    option_d_ar: "الذاكرة العشوائية",
    option_d_en: "Random Access Memory",
    correct_option: "A",
    explanation_ar: "بيانات التدريب هي التي تحدد دقة وجودة النموذج.",
    explanation_en: "Training datasets directly govern performance and predictive accuracy."
  },
  {
    id: "off_l4_wkb_m2",
    lesson: "1-4",
    unit: "1",
    type: "MCQ",
    source: "WEEKLY_ASSESSMENT",
    difficulty: "EASY",
    question_ar: "إتاحة معلومات واضحة ومناسبة عن النظام واستخدامه وعملية اتخاذ القرار وحدوده يعد تعريفاً دقيقاً لمبدأ:",
    question_en: "Providing clear and appropriate information about the system, its use, decision process, and limitations is a precise definition of:",
    option_a_ar: "العدالة",
    option_a_en: "Fairness",
    option_b_ar: "الشفافية",
    option_b_en: "Transparency",
    option_c_ar: "المساءلة",
    option_c_en: "Accountability",
    option_d_ar: "حماية الخصوصية",
    option_d_en: "Privacy Protection",
    correct_option: "B",
    explanation_ar: "الشفافية تشمل توضيح حدود النظام وكيفية اتخاذ القرار.",
    explanation_en: "Transparency encompasses clear disclosure of operational processes and limits."
  },
  {
    id: "off_l4_wkb_m3",
    lesson: "1-4",
    unit: "1",
    type: "MCQ",
    source: "WEEKLY_ASSESSMENT",
    difficulty: "EASY",
    question_ar: "عدم التمييز ظلماً ضد أي شخص أو مجموعة بعينها في أحكام ومخرجات الذكاء الاصطناعي يمثل مبدأ:",
    question_en: "Non-discrimination unfairly against any person or group in AI judgments and outputs represents the principle of:",
    option_a_ar: "العدالة",
    option_a_en: "Fairness",
    option_b_ar: "الشفافية",
    option_b_en: "Transparency",
    option_c_ar: "حماية الخصوصية",
    option_c_en: "Privacy Protection",
    option_d_ar: "المساءلة",
    option_d_en: "Accountability",
    correct_option: "A",
    explanation_ar: "العدالة تمنع التحيز والتمييز الظالم.",
    explanation_en: "Fairness precludes biased and unfair discrimination."
  },
  {
    id: "off_l4_wkb_m4",
    lesson: "1-4",
    unit: "1",
    type: "MCQ",
    source: "WEEKLY_ASSESSMENT",
    difficulty: "EASY",
    question_ar: "الأسلوب أو التقنية التي تساعد البشر على فهم العوامل التي أسهمت في وصول النظام إلى مخرج أو قرار معين هي:",
    question_en: "The method or technique that helps humans understand factors contributing to the system reaching a specific output or decision is:",
    option_a_ar: "التحيز الخوارزمي",
    option_a_en: "Algorithmic Bias",
    option_b_ar: "الذكاء الاصطناعي القابل للتفسير (XAI)",
    option_b_en: "Explainable AI (XAI)",
    option_c_ar: "الجمع الجماعي للبيانات",
    option_c_en: "Mass Data Collection",
    option_d_ar: "تدقيق الشبكات",
    option_d_en: "Network Auditing",
    correct_option: "B",
    explanation_ar: "الذكاء الاصطناعي القابل للتفسير (XAI) يساعد البشر على فهم العوامل المساهمة في اتخاذ القرار.",
    explanation_en: "Explainable AI (XAI) exposes the contributing factors behind conclusions."
  },

  // ==================== WEEKLY ASSESSMENT: MODEL C (النموذج C) ====================
  {
    id: "off_l4_wkc_w1",
    lesson: "1-4",
    unit: "1",
    type: "WRITTEN",
    source: "WEEKLY_ASSESSMENT",
    difficulty: "HARD",
    question_ar: "ناقش أسباب التحيز الخوارزمي وكيف يمكن أن ينشأ من الاختيار غير المناسب للمتغيرات، أو استخدام متغير بديل يمثل بشكل غير مباشر سمة محمية؟",
    question_en: "Discuss causes of algorithmic bias, specifically how it arises from improper feature selection or using proxy variables representing protected traits?",
    ideal_answer_ar: "ينشأ التحيز عند اختيار متغيرات تبدو ظاهرياً محايدة ولكنها ترتبط ارتباطاً وثيقاً بصفات محمية (كالرمز البريدي الذي يعكس التركيبة العرقية أو الدخل في مدينة معينة، أو نوع المدرسة الذي يعكس الطبقة الاجتماعية). عند تدريب النموذج على هذا المتغير البديل (Proxy Variable)، فإنه يمارس تمييزاً غير مباشر ضد تلك الفئة حتى ولو تم حذف المتغير المحمي الأصلي (كالنوع أو العرق)، مما يكرس الظلم دون قصد واضح.",
    ideal_answer_en: "Proxy variables appear neutral but are strongly correlated with protected demographic markers (e.g. zip codes serving as proxies for race or socioeconomic status, school types proxying wealth). Even if sensitive labels are withheld, algorithms deduce redundant encodings through proxies, producing covert discrimination.",
    explanation_ar: "استخدام المتغيرات البديلة (Proxies) يؤدي لتمييز غير مباشر ضد الفئات المحمية.",
    explanation_en: "Proxy features introduce latent bias and proxy discrimination despite omitting explicit protected labels."
  },
  {
    id: "off_l4_wkc_w2",
    lesson: "1-4",
    unit: "1",
    type: "WRITTEN",
    source: "WEEKLY_ASSESSMENT",
    difficulty: "HARD",
    question_ar: "بين أهمية «الذكاء الاصطناعي القابل للتفسير (XAI)» في معالجة صعوبة تقييم آلية الوصول إلى النتيجة عندما تكون غير واضحة للعين البشرية؟",
    question_en: "Demonstrate the significance of 'Explainable AI (XAI)' in overcoming difficulties of auditing decision mechanisms opaque to human inspection?",
    ideal_answer_ar: "تكمن أهمية XAI في أنه يقدم دليلاً مرئياً ورياضياً لأسباب القرار (مثل تظليل الأجزاء التي استند إليها النظام في الأشعة أو إظهار نسبة تأثير كل متغير في قرار التوظيف). يتيح ذلك للخبراء البشريين التحقق من صحة المنطق العلمي وراء النتيجة، واكتشاف الأخطاء والتحيزات الخفية، ورفض التوصيات غير المبررة، مما يضمن اتخاذ قرارات آمنة وعادلة.",
    ideal_answer_en: "XAI produces interpretable visual and mathematical evidence (e.g. saliency maps, SHAP impact scores) that justifies classifications. This enables domain experts to validate logical coherence, reject ungrounded predictions, isolate latent vulnerabilities, and safeguard human welfare.",
    explanation_ar: "XAI يُمكّن الخبراء من فحص المبررات العلمية للقرار وتفادي الوقوع في الأخطاء.",
    explanation_en: "XAI empowers human subject-matter experts to audit reasoning and prevent catastrophic mistakes."
  },
  {
    id: "off_l4_wkc_w3",
    lesson: "1-4",
    unit: "1",
    type: "WRITTEN",
    source: "WEEKLY_ASSESSMENT",
    difficulty: "HARD",
    question_ar: "وضح الأبعاد المختلفة لمسؤولية الأطراف المتعددة (المطور، الشركة المشغلة، المستخدم) عند اتخاذ نظام الذكاء الاصطناعي حكماً خاطئاً أو غير عادل.",
    question_en: "Clarify the multi-stakeholder liability dimensions (developer, deploying organization, end-user) when AI makes an erroneous or unfair determination.",
    ideal_answer_ar: "1. بعد المطور: يتحمل المسؤولية إذا كان الخطأ ناتجاً عن إهمال في فحص البيانات، أو وجود تحيز خوارزمي كان يمكن اكتشافه، أو وجود عيوب برمجية جسيمة.\n2. بعد الشركة المشغلة: تتحمل المسؤولية إذا قامت بنشر النظام في بيئة غير مناسبة، أو لم توفر تدريباً كافياً للعاملين، أو تجاهلت إجراءات السلامة والمراجعة الدورية.\n3. بعد المستخدم النهائي: يتحمل المسؤولية إذا اعتمد على النظام اعتماداً أعمى دون مراجعة، أو خالف تعليمات التشغيل السليمة في حالات تتطلب تدخلاً بشرياً.",
    ideal_answer_en: "1. Developer Liability: Accountable for negligence during dataset collation, undiscovered addressable algorithmic bias, and software defects.\n2. Deployer Organization Liability: Accountable for misapplication in non-certified environments, insufficient operator training, and absence of safety protocols.\n3. End-User Liability: Accountable for abdication of professional judgment, blind automation trust, or defying mandated human-in-the-loop policies.",
    explanation_ar: "المسؤولية المشتركة: لكل طرف نطاق واجبات محدد يُحاسب عليه قانونياً وأخلاقياً.",
    explanation_en: "Distributed liability framework detailing specific obligations across development, management, and execution."
  },
  {
    id: "off_l4_wkc_w4",
    lesson: "1-4",
    unit: "1",
    type: "WRITTEN",
    source: "WEEKLY_ASSESSMENT",
    difficulty: "HARD",
    question_ar: "اشرح كيف تتكامل المبادئ الأربعة لأخلاقيات الذكاء الاصطناعي (العدالة، الشفافية، حماية الخصوصية، المساءلة) لتشكيل إطار متكامل للاستخدام المسؤول.",
    question_en: "Explain how the four AI ethics principles (Fairness, Transparency, Privacy, Accountability) integrate into a unified responsible deployment framework.",
    ideal_answer_ar: "تتكامل المبادئ الأربعة كنظام مترابط لا غنى فيه عن أي مبدأ:\n- الشفافية تكشف كيفية عمل النظام والبيانات المستخدمة، وبدونها لا يمكن التحقق من العدالة.\n- والعدالة تضمن حماية الجميع من التحيز، لكنها تعتمد على حماية الخصوصية لضمان عدم استغلال البيانات الشخصية الحساسة.\n- وأخيراً فإن المساءلة هي الضمانة القانونية والعملية التي تُلزم الأطراف بالتمسك بالعدالة والشفافية والخصوصية ومحاسبة من يقصر فيها، مما يشكل منظومة أخلاقية متكاملة تصون كرامة الإنسان وحقوقه.",
    ideal_answer_en: "The four principles form an interdependent governance matrix: Transparency exposes internal reasoning and datasets, enabling auditing of Fairness. Fairness prevents demographic injury, requiring Privacy Protection to safeguard sensitive identities from exploitative profiling. Finally, Accountability enforces institutional liability and judicial compliance across all principles, cementing a human-centric ethical baseline.",
    explanation_ar: "تكامل المبادئ الأربعة يشكل منظومة أمان متكاملة تحمي المجتمع والمستخدم.",
    explanation_en: "Synergistic interplay of all 4 ethics principles creating a comprehensive governance barrier."
  },
  {
    id: "off_l4_wkc_m1",
    lesson: "1-4",
    unit: "1",
    type: "MCQ",
    source: "WEEKLY_ASSESSMENT",
    difficulty: "MEDIUM",
    question_ar: "تحديد أدوار وواجبات الأطراف المرتبطة بتطوير النظام وتشغيله واستخدامه (المطور، المشغل، المستخدم) يشير إلى مصطلح:",
    question_en: "Defining the roles and obligations of parties linked to system development, operation, and usage refers to the term:",
    option_a_ar: "المسؤولية",
    option_a_en: "Responsibility",
    option_b_ar: "التحيز الخوارزمي",
    option_b_en: "Algorithmic Bias",
    option_c_ar: "بيانات التدريب",
    option_c_en: "Training Data",
    option_d_ar: "الشفافية",
    option_d_en: "Transparency",
    correct_option: "A",
    explanation_ar: "المسؤولية (Responsibility) تختص بتحديد أدوار وواجبات كل طرف استباقياً.",
    explanation_en: "Responsibility refers to proactive allocation of operational roles and duties."
  },
  {
    id: "off_l4_wkc_m2",
    lesson: "1-4",
    unit: "1",
    type: "MCQ",
    source: "WEEKLY_ASSESSMENT",
    difficulty: "EASY",
    question_ar: "نظام أو تقنية تجمع كميات كبيرة من بيانات السلوك عبر الإنترنت وتسمح بتتبع الأفراد في الأماكن العامة تثير قضايا تتعلق بـ:",
    question_en: "A system or technology aggregating extensive online behavioral data and enabling tracking individuals in public spaces raises issues concerning:",
    option_a_ar: "سرعة المعالجة الحاسوبية",
    option_a_en: "Computer processing speed",
    option_b_ar: "حماية الخصوصية",
    option_b_en: "Privacy Protection",
    option_c_ar: "كفاءة الذاكرة المركزية",
    option_c_en: "Central memory efficiency",
    option_d_ar: "قانون مور",
    option_d_en: "Moore's Law",
    correct_option: "B",
    explanation_ar: "تتبع الأفراد والجمع الجماعي للبيانات يمس بشكل مباشر حماية الخصوصية.",
    explanation_en: "Mass surveillance and data scraping trigger acute privacy protection infringements."
  },
  {
    id: "off_l4_wkc_m3",
    lesson: "1-4",
    unit: "1",
    type: "MCQ",
    source: "WEEKLY_ASSESSMENT",
    difficulty: "MEDIUM",
    question_ar: "إحدى الآتي تمثل الوصف الدقيق لمبدأ «المساءلة»:",
    question_en: "Which of the following represents the precise description of the principle of 'Accountability':",
    option_a_ar: "إتاحة معلومات واضحة عن النظام وحدوده",
    option_a_en: "Providing clear information about the system and limits",
    option_b_ar: "عدم التمييز ظلماً ضد أي شخص أو مجموعة",
    option_b_en: "Non-discrimination unfairly against any person or group",
    option_c_ar: "تحديد الجهات المسؤولة عن النظام وقراراته وإمكان محاسبتها وفق أدوارها",
    option_c_en: "Identifying parties liable for system decisions and subjecting them to audit/sanctions based on roles",
    option_d_ar: "فهم العوامل التي أسهمت في وصول النظام إلى مخرج معين",
    option_d_en: "Understanding factors contributing to a specific system output",
    correct_option: "C",
    explanation_ar: "المساءلة هي تحديد الجهات المسؤولة عن النظام وإمكانية محاسبتها وفق أدوارها.",
    explanation_en: "Accountability is explicitly establishing liable parties answerable to sanction."
  },
  {
    id: "off_l4_wkc_m4",
    lesson: "1-4",
    unit: "1",
    type: "MCQ",
    source: "WEEKLY_ASSESSMENT",
    difficulty: "EASY",
    question_ar: "أي من الخيارات التالية يُعد مثالاً واضحاً على التحيز في أنظمة الذكاء الاصطناعي؟",
    question_en: "Which of the following is a clear example of bias in AI systems?",
    option_a_ar: "نظام توظيف يفضل فئة بصورة غير عادلة أو نظام تعرف على الوجه تقل دقته مع فئات معينة",
    option_a_en: "A hiring system unfairly favoring one group or a facial recognition system with lower accuracy for certain demographics",
    option_b_ar: "برنامج لتنظيم المجلدات والملفات الشخصية على الحاسوب المحلي",
    option_b_en: "A utility program for sorting folders and files on a local PC",
    option_c_ar: "تطبيق لحساب العمليات الرياضية البسيطة والعمليات الهندسية",
    option_c_en: "An application calculating basic math and geometric equations",
    option_d_ar: "أداة لتعديل صور المناظر الطبيعية وتحسين إضاءتها",
    option_d_en: "A photo tool adjusting landscape lighting and color tone",
    correct_option: "A",
    explanation_ar: "تفضيل فئة في التوظيف أو انخفاض دقة التعرف على الوجه مع فئات معينة هما المثالان الأبرز على التحيز الخوارزمي في الواقع.",
    explanation_en: "Hiring bias and demographic disparities in facial recognition accuracy are classic real-world examples of algorithmic bias."
  }
];
