import type { QuizQuestion } from './courseData';

export const OFFICIAL_WRITTEN_L1_L2: QuizQuestion[] = [
  // ==================== LESSON 1-1 WRITTEN QUESTIONS FROM MINISTRY PDF ====================
  {
    id: "off_l1_w_m1",
    lesson: "1-1",
    unit: "1",
    type: "WRITTEN",
    source: "WEEKLY_ASSESSMENT",
    difficulty: "MEDIUM",
    question_ar: "اشرح كيف أثر ظهور الحواسيب الشخصية (PCs) وانتشار الوصول العالمي إلى المعلومات والبريد الإلكتروني على المجتمع؟",
    question_en: "Explain how the advent of personal computers (PCs) and global access to info/email transformed society?",
    ideal_answer_ar: "في السبعينيات والثمانينيات، أتاح انتشار الحواسيب الشخصية للأفراد إمكانية امتلاك قدرات حوسبية داخل المنازل والمكاتب بعد أن كانت مقتصرة على المؤسسات العسكرية والجامعات. وفي التسعينيات، أدى ظهور الويب والبريد الإلكتروني إلى ثورة اتصالية جعلت تبادل البيانات فورياً وتجاوز الحدود الجغرافية، مما وضع حجر الأساس للعولمة واقتصاد المعرفة.",
    ideal_answer_en: "PCs decentralized compute power from military mainframes to individuals in homes and businesses. The 1990s Web and email emergence removed geographic borders, establishing instantaneous global communication and the digital knowledge economy.",
    explanation_ar: "التحول من الحواسيب المركزية العملاقة إلى الحواسيب الشخصية وثورة الإنترنت.",
    explanation_en: "Transition from monolithic mainframes to decentralized desktop computing and web communication."
  },
  {
    id: "off_l1_w_m2",
    lesson: "1-1",
    unit: "1",
    type: "WRITTEN",
    source: "WEEKLY_ASSESSMENT",
    difficulty: "HARD",
    question_ar: "اشرح كيف يؤدي استمرار تصغير مكونات الدوائر في قانون مور إلى ظهور تحديات هندسية وفيزيائية وما هي الحلول البديلة؟",
    question_en: "Explain how ongoing miniaturization in Moore's Law leads to physical limits and what alternate paradigms are emerging?",
    ideal_answer_ar: "مع وصول الترانزستورات إلى أحجام ذرية متناهية الصغر (بضعة نانومترات)، تنشأ ظواهر فيزيائية معقدة مثل النفق الكمومي (Quantum Tunneling) وتسرب التيار وتولد حرارة هائلة تعيق زيادة سرعة التردد. تشمل الحلول البديلة: المعالجة متعددة الأنوية المتوازية، وتطوير شرائح مخصصة، والحوسبة الكمومية (Quantum Computing) التي تعتمد على الكيوبت بدلاً من البت التقليدي.",
    ideal_answer_en: "Shrinking transistors to single-digit nanometers triggers quantum tunneling, severe thermal dissipation limits, and electron leakage. Emerging alternatives include multi-core parallelization, domain-specific accelerators, and quantum computing using qubits.",
    explanation_ar: "حدود قانون مور الفيزيائية والاتجاه نحو الحوسبة الكمومية والتوازي.",
    explanation_en: "Physical breakdown of Moore's Law and transition toward parallel architectures and quantum mechanics."
  },
  {
    id: "off_l1_w_m3",
    lesson: "1-1",
    unit: "1",
    type: "WRITTEN",
    source: "WEEKLY_ASSESSMENT",
    difficulty: "MEDIUM",
    question_ar: "وضح باختصار مفهوم كل من «شبكات التواصل الاجتماعي» و«التعلم عبر الإنترنت» و«الدفع غير النقدي»؟",
    question_en: "Briefly explain the concepts of: Social Networking Services (SNS), Online Learning, and Cashless Payments?",
    ideal_answer_ar: "1. شبكات التواصل الاجتماعي (SNS): منصات رقمية تتيح للمستخدمين التواصل السريع ونشر المحتوى وتبادل الآراء حول العالم.\n2. التعلم عبر الإنترنت: تقديم الفصول والمناهج الدراسية رقمياً عبر المنصات السحابية دون التقيد بموقع جغرافي.\n3. الدفع غير النقدي: تسوية المعاملات المالية بالوسائل الإلكترونية والبطاقات وتطبيقات المحافظ الذكية ورموز QR دون تداول النقود الورقية.",
    ideal_answer_en: "1. SNS: Web platforms facilitating real-time personal connections and viral content dissemination.\n2. Online Learning: Web-based delivery of scholastic curricula offering asynchronous spatial flexibility.\n3. Cashless Payments: Financial settlement via digital wallets, contactless cards, and QR codes eliminating physical legal tender.",
    explanation_ar: "ثلاثة من أهم التحولات المجتمعية الرقمية الناتجة عن تكنولوجيا المعلومات.",
    explanation_en: "Three primary pillars of contemporary societal digital transformation."
  },
  {
    id: "off_l1_w_m4",
    lesson: "1-1",
    unit: "1",
    type: "WRITTEN",
    source: "WEEKLY_ASSESSMENT",
    difficulty: "MEDIUM",
    question_ar: "وضح كيف تعالج الحوسبة الطرفية البيانات محلياً على متن المركبة ذاتية القيادة فوراً لتجنب التأخير؟",
    question_en: "Explain how edge computing processes telemetry locally onboard autonomous vehicles to avoid latency?",
    ideal_answer_ar: "السيارات ذاتية القيادة تعتمد على الحوسبة الطرفية (Edge Computing) بمعالجة بيانات الكاميرات ومستشعرات الرادار والليزر (LiDAR) بواسطة حواسيب مدمجة بالمركبة مباشرة. يمنع ذلك الاعتماد على السحابة وتجنب تأخير نقل البيانات عبر الشبكة (Latency) والذي قد يستغرق مئات الميلي ثواني، وهو فارق زمني حاسم لتفادي الحوادث والكبح الطارئ الفوري.",
    ideal_answer_en: "Edge computing equips autonomous cars with onboard processors analyzing LiDAR, camera, and radar feeds locally in sub-millisecond cycles. Bypassing cloud roundtrip latency ensures life-critical emergency braking and lane corrections execute instantly.",
    explanation_ar: "الحوسبة الطرفية تضمن معالجة لحظية بدون تأخير شبكي في الأنظمة الحساسة للسلامة.",
    explanation_en: "Edge computing delivers sub-millisecond local inference essential for real-time safety critical applications."
  },
  {
    id: "off_l1_w_m5",
    lesson: "1-1",
    unit: "1",
    type: "WRITTEN",
    source: "WEEKLY_ASSESSMENT",
    difficulty: "HARD",
    question_ar: "وضح الفروق الجوهرية بين «البت الكلاسيكي» و«الكيوبت (qubit)» مستخدماً مفهوم «التراكب الكمي» في الحوسبة الكمومية؟",
    question_en: "Clarify fundamental differences between a classical bit and a qubit using the principle of quantum superposition?",
    ideal_answer_ar: "البت الكلاسيكي (Classical Bit) هو الوحدة الأساسية في الحواسيب التقليدية، ولا يمكن أن يأخذ إلا قيمة واحدة محددة في اللحظة الزمنية الواحدة: إما (0) أو (1).\nبينما الكيوبت (Qubit) في الحوسبة الكمومية، يمكنه بفضل خاصية «التراكب الكمي» (Superposition) أن يتواجد في حالة تمثل (0) و(1) في آن واحد باحتمالات مختلفة، مما يمنح الحواسيب الكمومية قدرة معالجة هائلة لحل المشكلات الحسابية فائقة التعقيد بالتوازي.",
    ideal_answer_en: "A classical bit is strictly binary, holding either discrete 0 or 1 at any instant. A quantum bit (Qubit) harnesses quantum superposition, existing in linear combinations of both 0 and 1 states simultaneously. This grants exponential computational parallelism for complex cryptographic and molecular problems.",
    explanation_ar: "الفرق بين ثنائية البت الكلاسيكي وخاصية التراكب الكمي المتعدد للكيوبت.",
    explanation_en: "Dichotomy between deterministic binary bit states and probabilistic quantum superposition."
  },

  // ==================== LESSON 1-2 WRITTEN & EXAM QUESTIONS FROM MINISTRY PDF ====================
  {
    id: "off_l2_w_m1",
    lesson: "1-2",
    unit: "1",
    type: "WRITTEN",
    source: "WEEKLY_ASSESSMENT",
    difficulty: "MEDIUM",
    question_ar: "لماذا تعد معظم أنظمة الذكاء الاصطناعي الحالية «ضيق النطاق» (Narrow AI)، وما الفرق بينها وبين الذكاء الاصطناعي العام؟",
    question_en: "Why are most current AI systems classified as 'Narrow AI', and how do they differ from General AI?",
    ideal_answer_ar: "تعد أنظمة الذكاء الاصطناعي الحالية ضيقة النطاق (Narrow AI أو Weak AI) لأنها مصممة ومدربة لأداء مهمة واحدة محددة أو نطاق ضيق بكفاءة عالية (مثل لعب الشطرنج، أو التعرف على الوجوه، أو ترجمة النصوص)، ولكنها لا تستطيع نقل خبرتها لأداء مهام أخرى خارج نطاقها.\nأما الذكاء الاصطناعي العام (AGI)، فهو نظام نظري مستقبلي يمتلك قدرات إدراكية وفكرية شاملة تضاهي العقل البشري، بحيث يستطيع التفكير وحل المشكلات والتعلم الذاتي في أي مجال معرفي دون إعادة برمجة.",
    ideal_answer_en: "Current systems are Narrow AI (Weak AI) because they specialize in a single domain or bounded task (e.g. face unlock, chess, translation) without general transferable intellect. Artificial General Intelligence (AGI) is hypothetical human-level synthetic cognition capable of generalized reasoning, abstract problem-solving, and cross-domain learning autonomously.",
    explanation_ar: "الفرق بين الذكاء الاصطناعي الضيق المتخصص والذكاء الاصطناعي العام النظري.",
    explanation_en: "Contrast between domain-specific Narrow AI and hypothetical cross-domain Artificial General Intelligence."
  },
  {
    id: "off_l2_w_m2",
    lesson: "1-2",
    unit: "1",
    type: "WRITTEN",
    source: "WEEKLY_ASSESSMENT",
    difficulty: "MEDIUM",
    question_ar: "عرف الشبكة العصبية الاصطناعية ووضح وظيفة طبقة الإدخال والطبقات المخفية وطبقة الإخراج؟",
    question_en: "Define an Artificial Neural Network and explain functions of the input layer, hidden layers, and output layer?",
    ideal_answer_ar: "الشبكة العصبية الاصطناعية (ANN) هي نموذج حوسبي مستوحى من البنية البيولوجية للخلايا العصبية في الدماغ البشري، وتتكون من وحدات معالجة مترابطة تضبط أوزانها أثناء التدريب.\n1. طبقة الإدخال (Input Layer): تستقبل البيانات الأولية والخصائص من البيئة الخارجية (مثل بكسلات الصورة).\n2. الطبقات المخفية (Hidden Layers): تقوم باستخراج الأنماط المعقدة والمعالجة الرياضية وتجريد الميزات عبر طبقات متعددة (في التعلم العميق).\n3. طبقة الإخراج (Output Layer): تُنتج التوقع أو التصنيف النهائي للنظام (مثل احتمال أن الصورة لقطة أو كلب).",
    ideal_answer_en: "An Artificial Neural Network is a computational architecture inspired by biological neuronal synapses. 1. Input Layer: Ingests raw vector features (e.g. pixel luminance). 2. Hidden Layers: Perform non-linear mathematical transformations and extract hierarchical feature representations. 3. Output Layer: Emits probability distributions, regression values, or classification labels.",
    explanation_ar: "الهيكل الثلاثي للشبكة العصبية: طبقة الإدخال، الطبقات المخفية، وطبقة الإخراج.",
    explanation_en: "Three-tier neural network architecture: input, intermediate hidden transformation layers, and output."
  },
  {
    id: "off_l2_w_m3",
    lesson: "1-2",
    unit: "1",
    type: "WRITTEN",
    source: "WEEKLY_ASSESSMENT",
    difficulty: "HARD",
    question_ar: "ناقش مشكلة «الهلوسة» في الذكاء الاصطناعي التوليدي، موضحاً سبب خطورتها في السياقات الأكاديمية والطبية وكيفية تجنبها؟",
    question_en: "Discuss 'Hallucination' in Generative AI, explaining hazards in academic/medical domains and mitigation tactics?",
    ideal_answer_ar: "الهلوسة (Hallucination) هي توليد نماذج الذكاء الاصطناعي التوليدي لمعلومات أو حقائق أو استشهادات غير صحيحة بالمرة مع تقديمها بأسلوب واثق ومقنع للغاية. تكمن خطورتها في السياقات الطبية والأكاديمية في أنها قد تدفع لاتخاذ قرارات علاجية خاطئة تؤذي المرضى أو نشر دراسات مستندة لمراجع وهمية.\nلتجنبها: يجب على المستخدم التحقق دوماً من المصادر الأصلية المستقلة، واستخدام التوليد المعزز بالاسترجاع (RAG)، وعدم الاعتماد الأعمى على الإجابات التوليدية في المسائل الحساسة.",
    ideal_answer_en: "Hallucination refers to LLMs generating fabricated, factually false claims, synthetic citations, or bogus data packaged with linguistic fluency and confidence. In medicine and academia, it poses severe risks of malpractice, bogus citations, and lethal clinical advice. Mitigation demands independent source auditing, retrieval-augmented generation (RAG), and strict refusal of blind reliance.",
    explanation_ar: "الهلوسة التوليدية وأثرها على موثوقية المعلومات وطرق التحقق البشري.",
    explanation_en: "Hallucination mechanics in GenAI, real-world hazards, and cross-verification protocols."
  },
  {
    id: "off_l2_w_m4",
    lesson: "1-2",
    unit: "1",
    type: "WRITTEN",
    source: "WEEKLY_ASSESSMENT",
    difficulty: "MEDIUM",
    question_ar: "افترض أن مزارعاً يريد استخدام نظام ذكاء اصطناعي للتمييز بين صور المحاصيل السليمة والمصابة، اشرح كيف يتعلم النظام أداء هذه المهمة؟",
    question_en: "Suppose a farmer wants to deploy AI to distinguish healthy vs diseased crops; explain how the system learns this task?",
    ideal_answer_ar: "يتعلم النظام عبر مراحل التعلم الآلي والتعلم العميق الخاضع للإشراف (Supervised Learning):\n1. جمع البيانات: التقاط آلاف الصور لأوراق المحاصيل وتصنيفها بتسميات واضحة (سليمة / مصابة بنوع معين من الآفات).\n2. التدريب: تزويد الشبكة العصبية بهذه الصور لتتعلم الأنماط والخصائص المميزة للآفات (مثل البقع الصفراء أو التمزقات) مع ضبط أوزان الروابط العصبية تلقائياً لتقليل نسبة الخطأ.\n3. الاختبار والتشغيل: اختبار النموذج على صور جديدة لم يرها من قبل للتأكد من دقته، ثم نشره في كاميرا هاتف المزارع أو طائرة درون لفحص الحقل لحظياً.",
    ideal_answer_en: "Supervised computer vision pipeline: 1. Dataset Collection: Gathering thousands of labeled leaf images marked as healthy or diseased. 2. Training: Ingesting inputs into a convolutional neural network (CNN), adjusting synaptic weights via backpropagation to minimize classification loss on visual lesion features. 3. Inference: Deploying on drones or mobile devices to classify unobserved crop leaves in real-time.",
    explanation_ar: "خطوات تدريب نموذج رؤية حاسوبية خاضع للإشراف لتمييز الآفات الزراعية.",
    explanation_en: "End-to-end supervised deep learning training pipeline applied to precision agriculture."
  },
  {
    id: "off_l2_w_m5",
    lesson: "1-2",
    unit: "1",
    type: "WRITTEN",
    source: "WEEKLY_ASSESSMENT",
    difficulty: "MEDIUM",
    question_ar: "تحدث عن فائدة واحدة ومخاطرة واحدة لاستخدام الذكاء الاصطناعي التوليدي في كتابة تقرير مدرسي، وما هو الإجراء السليم للتعامل معه؟",
    question_en: "Discuss one benefit and one risk of using Generative AI in writing a school report, and state the proper procedure?",
    ideal_answer_ar: "الفائدة: المساعدة في العصف الذهني السريع، وتلخيص الأفكار والمراجع، واقتراح هياكل تنظيمية للتقرير.\nالمخاطرة: احتمالية تضمين معلومات مهلوسة وغير دقيقة علمياً أو الوقوع في الانتحال وسرقة الملكية الفكرية دون فهم حقيقي للموضوع.\nالإجراء السليم: استخدام الذكاء الاصطناعي كأداة مساعدة ملهمة فقط، والتحقق المستقل من كل معلومة ورقم من كتب ومصادر موثوقة، وإعادة صياغة الأفكار بأسلوب الطالب الخاص مع توثيق المصادر المستخدمة بأمانة.",
    ideal_answer_en: "Benefit: Accelerated brainstorming, thematic structuring, and rapid initial drafting.\nRisk: Inclusion of fabricated hallucinations, factual falsehoods, or uncritical plagiarism.\nProper Procedure: Treat AI solely as a brainstorming partner, independently fact-check every reference against verified scholarly literature, synthesize in one's own voice, and transparently cite tools.",
    explanation_ar: "الاستخدام المسؤول والأكاديمي لأدوات الذكاء الاصطناعي في التعليم.",
    explanation_en: "Responsible academic utilization and cross-validation protocols for students."
  },
  {
    id: "off_l2_w_m6",
    lesson: "1-2",
    unit: "1",
    type: "WRITTEN",
    source: "WEEKLY_ASSESSMENT",
    difficulty: "HARD",
    question_ar: "اشرح بالتفصيل العلاقة المتداخلة بين الذكاء الاصطناعي والتعلم الآلي والتعلم العميق مدعماً إجابتك بالمفاهيم الأساسية؟",
    question_en: "Explain the nested relationship between AI, Machine Learning, and Deep Learning supported by core concepts?",
    ideal_answer_ar: "العلاقة تمثل دوائر متداخلة:\n1. الذكاء الاصطناعي (AI): هو المظلة الشاملة الواسعة التي تضم أي نظام يحاكي السلوك والذكاء البشري.\n2. التعلم الآلي (Machine Learning): مجموعة فرعية داخل الذكاء الاصطناعي تركز على خوارزميات تتعلم الأنماط من البيانات تلقائياً دون كتابة قواعد برمجية صريحة.\n3. التعلم العميق (Deep Learning): مجموعة فرعية متقدمة داخل التعلم الآلي تعتمد على شبكات عصبية اصطناعية عميقة متعددة الطبقات (Deep Neural Networks)، وتتميز بقدرتها الفائقة على معالجة البيانات غير المهيكلة الضخمة كالصور والأصوات.",
    ideal_answer_en: "Hierarchical nested relationship: 1. AI: The overarching discipline constructing systems that mimic human intellect. 2. Machine Learning: A core subfield of AI focused on algorithms learning directly from data rather than hardcoded heuristics. 3. Deep Learning: A specialized vanguard subset of ML utilizing multi-layered neural network topologies that autonomously extract hierarchical abstract representations from massive unstructured media.",
    explanation_ar: "الهرمية المتداخلة: الذكاء الاصطناعي يشمل تعلم الآلة، وتعلم الآلة يشمل التعلم العميق.",
    explanation_en: "The nested Russian-doll hierarchy: AI encompasses ML, which in turn encapsulates Deep Learning."
  },
  {
    id: "off_l2_w_m7",
    lesson: "1-2",
    unit: "1",
    type: "WRITTEN",
    source: "WEEKLY_ASSESSMENT",
    difficulty: "MEDIUM",
    question_ar: "قارن بوضوح بين «التعلم الآلي» و«التعلم العميق» من حيث الاعتماد على الشبكات العصبية وحجم البيانات المطلوبة؟",
    question_en: "Clearly compare Machine Learning and Deep Learning in terms of neural network dependency and required data scale?",
    ideal_answer_ar: "1. الاعتماد على الشبكات العصبية: التعلم الآلي التقليدي يعتمد على خوارزميات إحصائية متنوعة (مثل أشجار القرار والانحدار الخطي) ويتطلب تدخلاً بشرياً لاستخراج الخصائص (Feature Engineering)، بينما التعلم العميق يعتمد كلياً وبشكل إلزامي على شبكات عصبية عميقة متعددة الطبقات تستخلص الخصائص ذاتياً.\n2. حجم البيانات: التعلم الآلي يمكنه العمل بفعالية مع مجموعات بيانات صغيرة أو متوسطة، بينما يتطلب التعلم العميق كميات ضخمة جداً من البيانات (Big Data) لضبط ملايين الأوزان وتحقيق دقة عالية.",
    ideal_answer_en: "1. Neural Architecture: Classical ML utilizes diverse algorithms (SVMs, Decision Trees, Regressions) requiring manual feature engineering; DL strictly hinges on multi-tiered deep artificial neural networks featuring automated feature representation. 2. Data Scale: Classical ML performs admirably on small-to-medium datasets; DL requires massive large-scale corpora to tune millions of parameters without overfitting.",
    explanation_ar: "مقارنة محورية بين تعلم الآلة التقليدي والتعلم العميق في استخراج الخصائص وحجم البيانات.",
    explanation_en: "Definitive comparison regarding feature engineering manual extraction vs autonomous deep hierarchical layers."
  },
  {
    id: "off_l2_w_m8",
    lesson: "1-2",
    unit: "1",
    type: "WRITTEN",
    source: "WEEKLY_ASSESSMENT",
    difficulty: "HARD",
    question_ar: "اشرح كيف يتمكن الذكاء الاصطناعي التوليدي من إنشاء محتوى جديد ومتنوع مثل النصوص والصور والأكواد البرمجية؟",
    question_en: "Explain how Generative AI generates novel, diverse content such as texts, images, and source code?",
    ideal_answer_ar: "يعتمد الذكاء الاصطناعي التوليدي (GenAI) على نماذج تعلم عميق ضخمة دُرِّبت على مليارات النصوص والصور والأكواد البرمجية. يتعلم النموذج التوزيع الاحتمالي الإحصائي للكلمات والبكسلات والأنماط المعقدة في لغة البشر. عند إدخال أمر (Prompt)، لا يقوم النموذج بنسخ مسبق، بل يقوم بحساب احتمالات تسلسل الكلمات أو البكسلات التالية خطوة بخطوة وتوليد محتوى جديد أصيل يطابق السياق المطلوب بدقة.",
    ideal_answer_en: "Generative AI leverages foundation deep learning models trained on billions of multimodal tokens. The model deciphers the underlying probability distribution of text, pixels, and syntax. Upon receiving a prompt, rather than retrieving indexed files, it iteratively samples from latent semantic probability distributions, synthesizing completely novel and coherent sequences in real time.",
    explanation_ar: "الذكاء التوليدي يحسب احتمالات التسلسلات التالية رياضياً لإنتاج محتوى فريد متوافق مع السياق.",
    explanation_en: "GenAI samples from complex learned probability manifolds to iteratively synthesize new tokens."
  },
  {
    id: "off_l2_w_m9",
    lesson: "1-2",
    unit: "1",
    type: "WRITTEN",
    source: "WEEKLY_ASSESSMENT",
    difficulty: "MEDIUM",
    question_ar: "ضع قاعدة مناسبة للتعامل مع الذكاء الاصطناعي التوليدي في الواجبات المدرسية مع ذكر سببين مقنعين؟",
    question_en: "State a sound policy rule for using Generative AI in school assignments, giving two persuasive justifications?",
    ideal_answer_ar: "القاعدة المقترحة: «استخدام الذكاء الاصطناعي التوليدي كمرشد ومحاور فكري للتخطيط وفهم المفاهيم المعقدة، مع حظر نسخ المخرجات مباشرة وإلزام الطالب بكتابة الحل بلغته الخاصة وتوثيق الأدوات المستخدمة».\nالسبب الأول: ضمان بناء المهارات الفكرية والتحليلية لدى الطالب بدلاً من الاعتماد السلبي وفقدان القدرة على التفكير النقدي.\nالسبب الثاني: تجنب مخاطر الأخطاء العلمية والهلوسة والانتحال الأدبي غير الأكاديمي.",
    ideal_answer_en: "Proposed Policy Rule: 'Employ Generative AI strictly as a tutor and ideation partner for clarifying concepts and structuring drafts, while prohibiting direct copy-pasting and requiring independent student drafting accompanied by transparent tool disclosure.'\nJustification 1: Preserving foundational cognitive writing and critical thinking muscle without atrophy from passive automation.\nJustification 2: Mitigating vulnerability to undetected factual hallucinations and academic dishonesty.",
    explanation_ar: "ميثاق وقواعد الاستخدام الآمن والأخلاقي للذكاء الاصطناعي التوليدي لدى الطلاب.",
    explanation_en: "Ethical policy balancing AI empowerment with critical cognitive independence and integrity."
  },
  {
    id: "off_l2_m_fast",
    lesson: "1-2",
    unit: "1",
    type: "MCQ",
    source: "WEEKLY_ASSESSMENT",
    difficulty: "EASY",
    question_ar: "ما هي الفائدة الأساسية للسرعة التي يوفرها الذكاء الاصطناعي التوليدي للطلاب عند إعداد التقارير؟",
    question_en: "What is the primary benefit of the speed provided by Generative AI to students preparing reports?",
    option_a_ar: "تسريع عملية العصف الذهني وتنظيم الأفكار الأولية وتوفير وقت البحث التمهيدي",
    option_a_en: "Accelerating brainstorming, organizing initial ideas, and saving preliminary research time",
    option_b_ar: "الاستغناء التام عن قراءة الكتب المدرسية والامتحانات",
    option_b_en: "Completely eliminating the need for textbooks and examinations",
    option_c_ar: "ضمان صحة 100% لجميع المعلومات دون مراجعة",
    option_c_en: "Guaranteeing 100% factual accuracy without human review",
    option_d_ar: "الحصول على درجات بدون بذل أي مجهود فكري",
    option_d_en: "Securing grades without intellectual effort",
    correct_option: "A",
    explanation_ar: "فائدة السرعة الأساسية هي مساعدة الطالب في العصف الذهني والتنظيم الأولي للموضوع.",
    explanation_en: "The legitimate speed benefit is reducing latency in ideation and thematic scoping."
  },
  {
    id: "off_l2_m_dl_cv",
    lesson: "1-2",
    unit: "1",
    type: "MCQ",
    source: "WEEKLY_ASSESSMENT",
    difficulty: "MEDIUM",
    question_ar: "أي من الخيارات الآتية يمثل التقنية الأنسب لمهام تحليل الصور المعقدة والتعرف المتقدم على الكلام؟",
    question_en: "Which of the following represents the most suitable technique for complex image analysis and advanced speech recognition?",
    option_a_ar: "البرمجة التقليدية المعتمدة على القواعد الصريحة",
    option_a_en: "Traditional rule-based programming",
    option_b_ar: "التعلم العميق (Deep Learning)",
    option_b_en: "Deep Learning",
    option_c_ar: "محركات البحث الخطية",
    option_c_en: "Linear search engines",
    option_d_ar: "قواعد البيانات العلائقية",
    option_d_en: "Relational databases",
    correct_option: "B",
    explanation_ar: "التعلم العميق هو التقنية المثلى والأكثر دقة في مهام معالجة الصور المعقدة والكلام والصوت.",
    explanation_en: "Deep Learning using multi-layered neural networks excels at complex perceptual tasks like computer vision and audio speech recognition."
  },
  {
    id: "off_l2_m_proper_use",
    lesson: "1-2",
    unit: "1",
    type: "MCQ",
    source: "WEEKLY_ASSESSMENT",
    difficulty: "EASY",
    question_ar: "ما هو الإجراء السليم الذي ينبغي اتباعه عند استخدام أدوات الذكاء الاصطناعي التوليدي في الواجبات المدرسية والبحث؟",
    question_en: "What is the proper procedure to follow when using Generative AI tools in school assignments and research?",
    option_a_ar: "نسخ ولصق النصوص المولدة مباشرة دون قراءتها أو ذكر الأداة",
    option_a_en: "Copying and pasting generated text directly without reading or citing the tool",
    option_b_ar: "الاعتماد الأعمى عليها كمرجع معصوم من الخطأ",
    option_b_en: "Blindly relying on it as an infallible source",
    option_c_ar: "التحقق المستقل من صحة المعلومات وصياغة الحل بالأسلوب الشخصي وتوثيق الأدوات المستخدمة بأمانة",
    option_c_en: "Independently verifying facts, phrasing answers in one's own voice, and transparently citing used tools",
    option_d_ar: "حظر التفكير الشخصي والاكتفاء بما يقدمه النموذج",
    option_d_en: "Suppressing personal thinking and relying entirely on model outputs",
    correct_option: "C",
    explanation_ar: "الإجراء السليم هو الفحص النقدي والتحقق المستقل والصياغة الذاتية والتوثيق الأمين.",
    explanation_en: "Proper academic practice demands independent verification, student synthesis, and transparent attribution."
  },
  {
    id: "off_l2_w_diagram",
    lesson: "1-2",
    unit: "1",
    type: "WRITTEN",
    source: "WEEKLY_ASSESSMENT",
    difficulty: "MEDIUM",
    question_ar: "وضح بمخطط مفاهيمي العلاقة بين الذكاء الاصطناعي والتعلم الآلي والتعلم العميق والذكاء الاصطناعي التوليدي؟",
    question_en: "Illustrate with a conceptual schema the relationship between AI, Machine Learning, Deep Learning, and Generative AI?",
    ideal_answer_ar: "المخطط يمثل أربع دوائر متحدة المركز ومتدرجة في التخصص:\\n1. الدائرة الكبرى الخارجية: الذكاء الاصطناعي (AI) — المظلة العامة التي تشمل كل حوسبة ذكية.\\n2. الدائرة الثانية داخلها: التعلم الآلي (Machine Learning) — النظم التي تتعلم من البيانات.\\n3. الدائرة الثالثة داخلها: التعلم العميق (Deep Learning) — النظم المعتمدة على شبكات عصبية عميقة متعددة الطبقات.\\n4. الدائرة المركزية الصغرى: الذكاء الاصطناعي التوليدي (GenAI) — نماذج تعلم عميق متطورة قادرة على توليد محتوى جديد أصيل (نصوص، صور، أكواد).",
    ideal_answer_en: "The schema consists of four nested concentric spheres of increasing specialization:\\n1. Outermost Sphere: Artificial Intelligence (AI) — The broad canopy of intelligent computing.\\n2. Second Sphere: Machine Learning (ML) — Data-driven statistical pattern learning.\\n3. Third Sphere: Deep Learning (DL) — Multi-layered artificial neural network topologies.\\n4. Core Sphere: Generative AI (GenAI) — Advanced deep architectures synthesizing novel multimodal artifacts (text, imagery, code).",
    explanation_ar: "هرمية الدوائر المتداخلة للمفاهيم الأربعة الأساسية في الذكاء الاصطناعي.",
    explanation_en: "Concentric hierarchy mapping AI -> ML -> DL -> GenAI."
  }
];

